# DORAnet → enzyme hypotheses → DNA design

This notebook converts DORAnet-generated reaction networks into concise downstream design tables: parsed reactions, enzyme hypotheses, enzyme-candidate templates, and non-operational DNA design plans for expert review.

In [24]:
from pathlib import Path
import glob
import json
import os
import re
import textwrap
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from rdkit import Chem, rdBase
from rdkit.Chem import rdmolfiles, Draw, AllChem
from IPython.display import display, Markdown
import time
import requests
from io import StringIO
import ast
import sys
import yaml
from tqdm.auto import tqdm
tqdm.pandas()

from DORA_XGB import DORA_XGB
by_desc_MW_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'by_descending_MW')
by_asc_MW_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'by_ascending_MW')
add_concat_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'add_concat')
add_subtract_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'add_subtract')

from Bio.Data import CodonTable

from dnachisel import (
    DnaOptimizationProblem,
    EnforceTranslation,
    EnforceGCContent,
    AvoidPattern,
    MaximizeCAI,
)

import hashlib

In [25]:
dataDir = '/mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/'
resultsDir = os.path.join(dataDir, 'Results/combinedEbolaVirus_bestMACAW_allDB_generative/')
DORANETmoleculesDataDir = os.path.join(resultsDir, 'DORAnet/InoAdeGuoXan/PATHWAY_reconstruction/')
DORANETmoleculesDataDir_run2 = os.path.join(resultsDir, 'DORAnet/InoAdeGuoXan/PATHWAY_reconstruction_run2/')
DNADesignResultsDir = os.path.join(resultsDir, 'DNA_design/')
os.makedirs(DNADesignResultsDir, exist_ok=True)

print("Reading DORAnet results from:", DORANETmoleculesDataDir)
print("DNA design results will be saved at:", DNADesignResultsDir)

Reading DORAnet results from: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction/
DNA design results will be saved at: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DNA_design/

## 1. Read list of target DORAnet compounds

In [26]:
targetCompound_DF = pd.read_csv(resultsDir + "/combinedEbola_allDORAnetGenerated_Antivirals_wARTprediction_top20.csv")
targetCompound_DF

,Rank,Canonical_SMILES,pPotency_prediction,pPotency_std,IC50 (µM)
0,1,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,6.156,0.476241,0.697981
1,2,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,5.989,0.473052,1.025573
2,3,Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O...,5.907,0.473610,1.238912
3,4,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)...,5.825,0.472941,1.495337
4,5,CC(=O)OP(=O)(O)OC(C)=O,5.758,0.479591,1.747229
5,6,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,5.729,0.473567,1.865382
6,7,CC(=O)OP(=O)(O)OP(=O)(O)O,5.693,0.478908,2.026785
7,8,Nc1ncnc2c1ncn2[C@@H]1OC(C(O)O)=C[C@H]1O,5.692,0.473252,2.030622
8,9,CC(Cl)[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](...,5.683,0.471067,2.074770
9,10,O=C(O)CC(=O)OP(=O)(O)O,5.679,0.476017,2.094051
10,11,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]c(NC=O)nc32)[C@H...,5.677,0.471412,2.104081
11,12,O=C1N=C2NC=Nc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@...,5.670,0.471980,2.136730
12,13,NC1=Nc2ncnc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@H]2O,5.669,0.470421,2.140884
13,14,C[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](O)[C@...,5.667,0.470071,2.155065
14,15,NC(=O)OP(=O)(O)O,5.664,0.478859,2.166036
15,16,O=C(O)CC(=O)O,5.651,0.475530,2.233832
16,17,O=CNc1ncnc2c1ncn2[C@@H]1O[C@H](C=O)[C@@H](O)[C...,5.645,0.472112,2.262352
17,18,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,5.638,0.472788,2.302842
18,19,CC(=O)CC(=O)O,5.637,0.474230,2.304127
19,20,Nc1nc2c(ncn2[C@@H]2OC(C(O)O)=C[C@H]2O)c(=O)[nH]1,5.629,0.475703,2.348605

In [27]:
DORANETmoleculesDataDir = Path(DORANETmoleculesDataDir)

def canonicalizeSmiles(smiles):
    mol = Chem.MolFromSmiles(str(smiles))
    return Chem.MolToSmiles(mol, canonical=True) if mol else None

def canonicalizeSmilesCollection(x):
    if not isinstance(x, (set, list, tuple)):
        return []
    out = []
    for s in x:
        c = canonicalizeSmiles(s)
        if c is not None:
            out.append(c)
    return sorted(set(out))

def parseLiteralFromScript(text, varName):
    # captures lines like: varName = {...} / [...] / "..."
    m = re.search(rf"^\s*{re.escape(varName)}\s*=\s*(.+)\s*$", text, flags=re.MULTILINE)
    if not m:
        return None
    raw = m.group(1).strip()
    try:
        return ast.literal_eval(raw)
    except Exception:
        return None

def parseHelpersFromScript(text):
    # Supports YAML-like line: helpers: ["O", ...]
    m = re.search(r"^\s*helpers\s*:\s*(.+)\s*$", text, flags=re.MULTILINE)
    if not m:
        # fallback in case file uses python assignment: helpers = [...]
        return parseLiteralFromScript(text, "helpers")
    raw = m.group(1).strip()
    try:
        return ast.literal_eval(raw)
    except Exception:
        return None

allReproFiles = sorted(
    DORANETmoleculesDataDir.rglob("reproDoranetJob.py"),
    key=lambda p: str(p).lower()
)

records = []
for reproPath in allReproFiles:
    txt = reproPath.read_text(encoding="utf-8", errors="ignore")

    startersRaw = parseLiteralFromScript(txt, "starters")
    targetRaw = parseLiteralFromScript(txt, "target")
    maxAtomsRaw = parseLiteralFromScript(txt, "maxAtoms")
    generationsRaw = parseLiteralFromScript(txt, "generations")
    helpersRaw = parseHelpersFromScript(txt)

    records.append({
        "dirName": reproPath.parent.name,
        "starters": canonicalizeSmilesCollection(startersRaw),
        "target": canonicalizeSmilesCollection(targetRaw),
        "helpers": canonicalizeSmilesCollection(helpersRaw),   # NEW
        "maxAtoms": maxAtomsRaw if isinstance(maxAtomsRaw, dict) else None,
        "generations": int(generationsRaw) if generationsRaw is not None else None,
    })

targetCompoundDir_DF = pd.DataFrame(
    records,
    columns=["dirName", "starters", "target", "helpers", "maxAtoms", "generations"]  # NEW
)

print(f"Total DORAnet configuration files: {len(targetCompoundDir_DF)}")

# join key from first target smiles
targetCompoundDir_DF = targetCompoundDir_DF.copy()
targetCompoundDir_DF["targetSmiles"] = targetCompoundDir_DF["target"].apply(
    lambda x: x[0] if isinstance(x, (list, tuple)) and len(x) > 0 else None
)

colsToAdd = ["Canonical_SMILES", "pPotency_prediction", "pPotency_std", "IC50 (µM)"]
targetCompoundDir_DF = targetCompoundDir_DF.merge(
    targetCompound_DF[colsToAdd].drop_duplicates(subset=["Canonical_SMILES"]),
    left_on="targetSmiles",
    right_on="Canonical_SMILES",
    how="left"
).drop(columns=["Canonical_SMILES"])

targetCompoundDir_DF = targetCompoundDir_DF.drop(columns=["targetSmiles"])
targetCompoundDir_DF = targetCompoundDir_DF.rename(columns={
    "starters": "starters_Canonical_SMILES",
    "target": "target_Canonical_SMILES",
    "helpers": "helpers_Canonical_SMILES",   
})

for c in ["starters_Canonical_SMILES", "target_Canonical_SMILES"]:
    targetCompoundDir_DF[c] = targetCompoundDir_DF[c].apply(
        lambda x: ".".join(x) if isinstance(x, (list, tuple)) else ("" if pd.isna(x) else str(x))
    )

# Keep helpers as separate entries joined by comma (not dot)
targetCompoundDir_DF["helpers_Canonical_SMILES"] = targetCompoundDir_DF["helpers_Canonical_SMILES"].apply(
    lambda x: ", ".join(x) if isinstance(x, (list, tuple)) else ("" if pd.isna(x) else str(x))
)

targetCompoundDir_DF = targetCompoundDir_DF.sort_values(
    by="pPotency_prediction", ascending=False
).reset_index(drop=True)

# safer path handling
outputPath = Path(DNADesignResultsDir) / "targetCompoundDir_DF.csv"
targetCompoundDir_DF.to_csv(outputPath, index=False)
targetCompoundDir_DF

Total DORAnet configuration files: 20

,dirName,starters_Canonical_SMILES,target_Canonical_SMILES,helpers_Canonical_SMILES,maxAtoms,generations,pPotency_prediction,pPotency_std,IC50 (µM)
0,high_pPotency_molecule_pathway1,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,6.156,0.476241,0.697981
1,high_pPotency_molecule_pathway2,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.989,0.473052,1.025573
2,high_pPotency_molecule_pathway3,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.907,0.473610,1.238912
3,high_pPotency_molecule_pathway4,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.825,0.472941,1.495337
4,high_pPotency_molecule_pathway5,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)OP(=O)(O)OC(C)=O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.758,0.479591,1.747229
5,high_pPotency_molecule_pathway6,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.729,0.473567,1.865382
6,high_pPotency_molecule_pathway7,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)OP(=O)(O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.693,0.478908,2.026785
7,high_pPotency_molecule_pathway8,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Nc1ncnc2c1ncn2[C@@H]1OC(C(O)O)=C[C@H]1O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.692,0.473252,2.030622
8,high_pPotency_molecule_pathway9,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(Cl)[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.683,0.471067,2.074770
9,high_pPotency_molecule_pathway10,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C(O)CC(=O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.679,0.476017,2.094051
10,high_pPotency_molecule_pathway11,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]c(NC=O)nc32)[C@H...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.677,0.471412,2.104081
11,high_pPotency_molecule_pathway12,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C1N=C2NC=Nc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.670,0.471980,2.136730
12,high_pPotency_molecule_pathway13,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC1=Nc2ncnc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@H]2O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.669,0.470421,2.140884
13,high_pPotency_molecule_pathway14,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](O)[C@...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.667,0.470071,2.155065
14,high_pPotency_molecule_pathway15,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.664,0.478859,2.166036
15,high_pPotency_molecule_pathway16,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C(O)CC(=O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.651,0.475530,2.233832
16,high_pPotency_molecule_pathway17,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=CNc1ncnc2c1ncn2[C@@H]1O[C@H](C=O)[C@@H](O)[C...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.645,0.472112,2.262352
17,high_pPotency_molecule_pathway18,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.638,0.472788,2.302842
18,high_pPotency_molecule_pathway19,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)CC(=O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.637,0.474230,2.304127
19,high_pPotency_molecule_pathway20,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Nc1nc2c(ncn2[C@@H]2OC(C(O)O)=C[C@H]2O)c(=O)[nH]1,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.629,0.475703,2.348605

## 2. Read the `reconstructed` pathways metadata for all `DORAnet` reactions

- go to the directory where pathway reconstruction DORAnet results are saved
- run this: `python pathwayReconstruction.py config.yaml`
- this will generate the csv file (`doranet_chain_reconstructed_pathway_steps_by_depth.csv`) with reconstructed pathways
- read the csv file for downstream processing

### Reconstruct pathway directly from multi generation DORAnet outputs

In [28]:
doranetMultiGenConfigPath = Path(DORANETmoleculesDataDir_run2) / "config_doranet_multiGen.yaml"

with open(doranetMultiGenConfigPath, "r", encoding="utf-8") as f:
    doranetCfg = yaml.safe_load(f) or {}

outputDir = Path(doranetCfg.get("outputDir", ".")).expanduser()

# If outputDir is relative, first try relative to config location.
if not outputDir.is_absolute():
    outputDirFromConfigDir = (doranetMultiGenConfigPath.parent / outputDir).resolve()
    outputDirFromCwd = (Path.cwd() / outputDir).resolve()

    summaryCsvName = doranetCfg.get("summaryCsv", "job_summary.csv")
    if (outputDirFromConfigDir / summaryCsvName).exists():
        outputDir = outputDirFromConfigDir
    else:
        outputDir = outputDirFromCwd

summaryPath = outputDir / doranetCfg.get("summaryCsv", "job_summary.csv")

if not summaryPath.exists():
    raise FileNotFoundError(f"Could not find job summary CSV: {summaryPath}")

jobSummaryDF = pd.read_csv(summaryPath)

print(f"Config file : {doranetMultiGenConfigPath}")
print(f"Output dir  : {outputDir}")
print(f"Summary CSV : {summaryPath}")
print(f"Jobs in summary: {len(jobSummaryDF):,}")

Config file : /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction_run2/config_doranet_multiGen.yaml
Output dir  : /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction_run2
Summary CSV : /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction_run2/job_summary.csv
Jobs in summary: 60

In [29]:
def splitMoleculeString(moleculeString):
    if pd.isna(moleculeString):
        return []
    return [mol for mol in str(moleculeString).split(".") if mol]


def sortedMoleculeString(moleculeString):
    mols = splitMoleculeString(moleculeString)
    return ".".join(sorted(mols))


def normalizeReactionSmiles(reactionSmiles):
    """
    Normalize a reaction SMILES by sorting reactant and product molecule strings.

    Input:
        A.B>>C.D

    Output:
        A.B>>C.D with molecules sorted on both sides.
    """
    if pd.isna(reactionSmiles) or ">>" not in str(reactionSmiles):
        return None

    reactants, products = str(reactionSmiles).split(">>", 1)

    reactantsNorm = sortedMoleculeString(reactants)
    productsNorm = sortedMoleculeString(products)

    return f"{reactantsNorm}>>{productsNorm}"


def extractFolderNum(name):
    match = re.search(r"pathway(\d+)", str(name))
    return int(match.group(1)) if match else -1


def splitPathwayBlocks(pathwaysTxtPath):
    if not Path(pathwaysTxtPath).exists():
        return []

    lines = Path(pathwaysTxtPath).read_text(encoding="utf-8").splitlines()

    blocks = []
    current = []

    for line in lines:
        if line.startswith("pathway number ") and current:
            blocks.append(current)
            current = [line]
        else:
            current.append(line)

    if current:
        blocks.append(current)

    blocks = [
        [x for x in block if str(x).strip()]
        for block in blocks
        if any(str(x).strip() for x in block)
    ]

    return blocks


def parsePathwayBlock(block):
    """
    Parse one block from DORAnet *_pathways.txt.

    Expected structure:
        pathway number 1
        place holder ...
        place holder ...
        place holder ...
        reaction SMILES stoichiometry [...]
        reaction SMILES, name, and enthalpy:
        rxn1
        rxn2
        ...
        name1
        name2
        ...
        dH1
        dH2
        ...
    """

    pathwayNumber = None
    for line in block:
        if line.startswith("pathway number "):
            pathwayNumber = str(line).replace("pathway number ", "").strip()
            break

    stoichList = []
    for line in block:
        prefix = "reaction SMILES stoichiometry "
        if line.startswith(prefix):
            payload = line[len(prefix):].strip()
            try:
                stoichList = ast.literal_eval(payload)
            except Exception:
                stoichList = []
            break

    marker = "reaction SMILES, name, and enthalpy:"
    try:
        markerIdx = block.index(marker)
    except ValueError:
        raise ValueError("Could not find reaction SMILES/name/enthalpy marker")

    payloadLines = [x.strip() for x in block[markerIdx + 1:] if str(x).strip()]

    if stoichList:
        numSteps = len(stoichList)
    else:
        if len(payloadLines) % 3 != 0:
            raise ValueError("Cannot infer number of steps from pathway block")
        numSteps = len(payloadLines) // 3
        stoichList = [None] * numSteps

    reactionSmilesList = payloadLines[:numSteps]
    reactionNameList = payloadLines[numSteps:2 * numSteps]
    enthalpyList = payloadLines[2 * numSteps:3 * numSteps]

    if len(reactionSmilesList) != numSteps:
        raise ValueError("Malformed pathway block: reaction count mismatch")

    return {
        "pathwayNumber": pathwayNumber,
        "numSteps": numSteps,
        "reactionSmilesList": reactionSmilesList,
        "reactionNameList": reactionNameList,
        "enthalpyList": enthalpyList,
        "stoichList": stoichList,
    }


def choosePathwayTxt(row):
    """
    Prefer exact-N pathway file generated by filterExactNumRxns.
    Fallback to default *_pathways.txt.
    """

    jobDir = Path(row["jobDir"])
    jobName = str(row["jobName"])
    generationRun = int(row["generationRun"])

    candidatePaths = []

    if "exactPathwaysTxt" in row and pd.notna(row["exactPathwaysTxt"]):
        p = Path(str(row["exactPathwaysTxt"]))
        if not p.is_absolute():
            p = jobDir / p
        candidatePaths.append(p)

    candidatePaths.extend([
        jobDir / f"{jobName}_pathways_exact{generationRun}.txt",
        jobDir / f"{jobName}_pathways.txt",
    ])

    for p in candidatePaths:
        if p.exists():
            return p

    return candidatePaths[0]


def parseReactionSmiles(reactionSmiles):
    if ">>" not in str(reactionSmiles):
        raise ValueError(f"Invalid reaction SMILES: {reactionSmiles}")

    reactants, products = str(reactionSmiles).split(">>", 1)
    return reactants, products


def parseStoich(stoichText):
    if stoichText is None or pd.isna(stoichText):
        return None, None

    parts = str(stoichText).split("$")
    reactantStoich = parts[0] if len(parts) > 0 else None
    productStoich = parts[1] if len(parts) > 1 else None

    return reactantStoich, productStoich


# -------------------------------------------------------------------
# Network JSON lookup functions to recover reactionType
# -------------------------------------------------------------------

def parseNetworkReactionForLookup(rxnString):
    """
    Parse one reaction from *_network_pretreated.json.

    Expected DORAnet format:
        reactants > ruleName > thermo$reactantStoich$productStoich$reactionType > products
    """

    parts = str(rxnString).split(">")

    if len(parts) != 4:
        return None

    reactants, ruleName, metaBlock, products = parts

    metaParts = (metaBlock.split("$") + [None, None, None, None])[:4]
    thermo, reactantStoich, productStoich, reactionType = metaParts

    reactionSmiles = f"{reactants}>>{products}"
    normalizedReactionSmiles = normalizeReactionSmiles(reactionSmiles)

    return {
        "reactionSMILES": reactionSmiles,
        "normalizedReactionSMILES": normalizedReactionSmiles,
        "ruleName": ruleName,
        "thermo": thermo,
        "reactantStoich": reactantStoich,
        "productStoich": productStoich,
        "reactionType": reactionType,
        "rawNetworkReactionString": str(rxnString),
    }


def buildNetworkReactionLookup(networkJsonPath):
    """
    Build lookup dictionaries from *_network_pretreated.json.

    Matching priority later:
        1. normalized reaction SMILES + ruleName
        2. normalized reaction SMILES only
    """

    networkJsonPath = Path(networkJsonPath)

    lookupByReactionAndRule = {}
    lookupByReactionOnly = {}

    if not networkJsonPath.exists():
        return lookupByReactionAndRule, lookupByReactionOnly

    try:
        with open(networkJsonPath, "r", encoding="utf-8") as f:
            reactionList = json.load(f)
    except Exception:
        return lookupByReactionAndRule, lookupByReactionOnly

    if not isinstance(reactionList, list):
        return lookupByReactionAndRule, lookupByReactionOnly

    for rxnString in reactionList:
        parsed = parseNetworkReactionForLookup(rxnString)

        if parsed is None:
            continue

        normRxn = parsed["normalizedReactionSMILES"]
        ruleName = parsed["ruleName"]

        if normRxn is None:
            continue

        lookupByReactionAndRule[(normRxn, ruleName)] = parsed

        if normRxn not in lookupByReactionOnly:
            lookupByReactionOnly[normRxn] = parsed

    return lookupByReactionAndRule, lookupByReactionOnly


def lookupNetworkReactionMetadata(reactionSmiles, ruleName, lookupByReactionAndRule, lookupByReactionOnly):
    """
    Match a pathway reaction back to *_network_pretreated.json.
    """

    normalizedReactionSmiles = normalizeReactionSmiles(reactionSmiles)

    if normalizedReactionSmiles is None:
        return {
            "reactionType": "",
            "rawNetworkReactionString": "",
            "networkMatchStatus": "invalid_reaction_smiles",
        }

    match = lookupByReactionAndRule.get((normalizedReactionSmiles, ruleName))

    if match is not None:
        out = dict(match)
        out["networkMatchStatus"] = "matched_by_reaction_and_rule"
        return out

    match = lookupByReactionOnly.get(normalizedReactionSmiles)

    if match is not None:
        out = dict(match)
        out["networkMatchStatus"] = "matched_by_reaction_only"
        return out

    return {
        "reactionType": "",
        "rawNetworkReactionString": "",
        "networkMatchStatus": "no_network_match",
    }


# -------------------------------------------------------------------
# Build reconstructedPathwaysDF from multi-generation DORAnet outputs
# -------------------------------------------------------------------

starterSet = set(doranetCfg.get("starters", []))
helperSet = set(doranetCfg.get("helpers", []))

records = []
parseErrors = []

networkLookupCache = {}

validJobsDF = jobSummaryDF.copy()

if "status" in validJobsDF.columns:
    validJobsDF = validJobsDF[validJobsDF["status"].eq("ok")].copy()

for _, jobRow in tqdm(validJobsDF.iterrows(), total=len(validJobsDF), desc="Reading DORAnet pathway files"):
    jobName = str(jobRow["jobName"])
    jobDir = Path(jobRow["jobDir"])
    dirName = jobDir.name
    generationRun = int(jobRow["generationRun"])
    targetSMILES = str(jobRow["targetSmiles"])

    pathwayTxtPath = choosePathwayTxt(jobRow)
    networkJsonPath = jobDir / f"{jobName}_network_pretreated.json"

    if jobName not in networkLookupCache:
        networkLookupCache[jobName] = buildNetworkReactionLookup(networkJsonPath)

    lookupByReactionAndRule, lookupByReactionOnly = networkLookupCache[jobName]

    try:
        blocks = splitPathwayBlocks(pathwayTxtPath)

        for blockIdx, block in enumerate(blocks, start=1):
            parsed = parsePathwayBlock(block)

            numSteps = parsed["numSteps"]
            pathwayNumber = parsed["pathwayNumber"] or str(blockIdx)

            routeId = (
                f"{jobName}_route_{int(pathwayNumber):06d}"
                if str(pathwayNumber).isdigit()
                else f"{jobName}_route_{blockIdx:06d}"
            )

            reconstructedPathwayString = "  ||  ".join(parsed["reactionSmilesList"])

            for stepIdx, reactionSmiles in enumerate(parsed["reactionSmilesList"], start=1):
                reactants, products = parseReactionSmiles(reactionSmiles)

                ruleName = (
                    parsed["reactionNameList"][stepIdx - 1]
                    if stepIdx - 1 < len(parsed["reactionNameList"])
                    else ""
                )

                thermoFromPathwayTxt = (
                    parsed["enthalpyList"][stepIdx - 1]
                    if stepIdx - 1 < len(parsed["enthalpyList"])
                    else ""
                )

                stoichText = (
                    parsed["stoichList"][stepIdx - 1]
                    if stepIdx - 1 < len(parsed["stoichList"])
                    else None
                )

                reactantStoichFromTxt, productStoichFromTxt = parseStoich(stoichText)

                networkMatch = lookupNetworkReactionMetadata(
                    reactionSmiles=reactionSmiles,
                    ruleName=ruleName,
                    lookupByReactionAndRule=lookupByReactionAndRule,
                    lookupByReactionOnly=lookupByReactionOnly,
                )

                reactionType = networkMatch.get("reactionType", "")
                rawNetworkReactionString = networkMatch.get("rawNetworkReactionString", "")
                networkMatchStatus = networkMatch.get("networkMatchStatus", "")

                # Prefer pathway file values where available, fallback to network JSON.
                thermo = thermoFromPathwayTxt if thermoFromPathwayTxt not in ["", None] else networkMatch.get("thermo", "")
                reactantStoich = (
                    reactantStoichFromTxt
                    if reactantStoichFromTxt not in ["", None]
                    else networkMatch.get("reactantStoich", None)
                )
                productStoich = (
                    productStoichFromTxt
                    if productStoichFromTxt not in ["", None]
                    else networkMatch.get("productStoich", None)
                )

                reactantMols = set(splitMoleculeString(reactants))
                productMols = set(splitMoleculeString(products))

                record = {
                    "dirName": dirName,
                    "jobName": jobName,
                    "sourceFolderNum": extractFolderNum(jobName),
                    "sourceDirectory": dirName,
                    "sourceDirectoryPath": str(jobDir),
                    "sourceJsonName": f"{jobName}_network_pretreated.json",
                    "sourceJsonPath": str(networkJsonPath),
                    "sourcePathwaysTxtPath": str(pathwayTxtPath),

                    "routeId": routeId,
                    "routeNumberInFile": pathwayNumber,
                    "generationRun": generationRun,
                    "searchDepthUsed": generationRun,
                    "step": stepIdx,
                    "numSteps": numSteps,

                    "starterSMILES": ";".join(sorted(starterSet)),
                    "targetSMILES": targetSMILES,

                    "reactants": reactants,
                    "products": products,
                    "reactionString": f"{reactants} >> {products}",
                    "reactionSMILES": reactionSmiles,
                    "reconstructedPathwayString": reconstructedPathwayString,

                    "ruleName": ruleName,
                    "thermo": thermo,
                    "reactantStoich": reactantStoich,
                    "productStoich": productStoich,
                    "reactionType": reactionType,

                    "rawNetworkReactionString": rawNetworkReactionString,
                    "networkMatchStatus": networkMatchStatus,

                    "numReactantMolecules": len(reactantMols),
                    "numProductMolecules": len(productMols),

                    "starterInReactants": bool(reactantMols & starterSet),
                    "targetInProducts": targetSMILES in productMols,

                    "isReconstructedPathwayStep": True,
                    "routeStepId": f"{routeId}_step_{stepIdx:02d}",
                }

                records.append(record)

    except Exception as exc:
        parseErrors.append({
            "jobName": jobName,
            "jobDir": str(jobDir),
            "generationRun": generationRun,
            "targetSMILES": targetSMILES,
            "pathwayTxtPath": str(pathwayTxtPath),
            "networkJsonPath": str(networkJsonPath),
            "error": str(exc),
        })


reconstructedPathwaysDF = (
    pd.DataFrame(records)
    .sort_values(["sourceFolderNum", "generationRun", "routeId", "step"])
    .reset_index(drop=True)
)

parseErrorsDF = pd.DataFrame(parseErrors)

print(f"Reconstructed pathway step rows : {len(reconstructedPathwaysDF):,}")
print(f"Unique routes                   : {reconstructedPathwaysDF['routeId'].nunique() if not reconstructedPathwaysDF.empty else 0:,}")
print(f"Unique job folders              : {reconstructedPathwaysDF['dirName'].nunique() if not reconstructedPathwaysDF.empty else 0:,}")
print(f"Parse errors                    : {len(parseErrorsDF):,}")

if not reconstructedPathwaysDF.empty:
    print("\nReaction type counts:")
    print(reconstructedPathwaysDF["reactionType"].value_counts(dropna=False).to_string())

    print("\nNetwork match status:")
    print(reconstructedPathwaysDF["networkMatchStatus"].value_counts(dropna=False).to_string())

reconstructedPathwaysDF.head()

Reading DORAnet pathway files: 100%|███████████████████████████████████████████████████████████████████████| 58/58 [00:02<00:00, 27.46it/s]

Reconstructed pathway step rows : 8,778
Unique routes                   : 2,968
Unique job folders              : 12
Parse errors                    : 0

Reaction type counts:
reactionType
Enzymatic    8778

Network match status:
networkMatchStatus
matched_by_reaction_and_rule    8778

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,productStoich,reactionType,rawNetworkReactionString,networkMatchStatus,numReactantMolecules,numProductMolecules,starterInReactants,targetInProducts,isReconstructedPathwayStep,routeStepId
0,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,1,...,"(1, 1)",Enzymatic,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,"(1, 1)",Enzymatic,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...
2,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,3,...,"(1, 1)",Enzymatic,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,"(1, 1)",Enzymatic,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen2_route_00...
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,"(1, 1, 1)",Enzymatic,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,matched_by_reaction_and_rule,3,3,False,False,True,high_pPotency_molecule_pathway2_wGen2_route_00...

In [7]:
completeRouteLevelDF = (
    reconstructedPathwaysDF
    .sort_values(["dirName", "routeId", "step"])
    .groupby("routeId", as_index=False)
    .agg(
        dirName=("dirName", "first"),
        jobName=("jobName", "first"),
        sourceFolderNum=("sourceFolderNum", "first"),
        generationRun=("generationRun", "first"),
        numSteps=("numSteps", "first"),
        searchDepthUsed=("searchDepthUsed", "first"),
        starterSMILES=("starterSMILES", "first"),
        targetSMILES=("targetSMILES", "first"),
        reconstructedPathwayString=("reconstructedPathwayString", "first"),
    )
)

starterTargetPathwayCountsDF = (
    completeRouteLevelDF
    .pivot_table(
        index=["dirName", "jobName", "generationRun", "starterSMILES", "targetSMILES"],
        columns="numSteps",
        values="routeId",
        aggfunc="nunique",
        fill_value=0,
    )
    .rename(columns={
        1: "numOneStepPathways",
        2: "numTwoStepPathways",
        3: "numThreeStepPathways",
    })
    .reset_index()
)

for c in ["numOneStepPathways", "numTwoStepPathways", "numThreeStepPathways"]:
    if c not in starterTargetPathwayCountsDF.columns:
        starterTargetPathwayCountsDF[c] = 0

starterTargetPathwayCountsDF["totalStarterToTargetPathways"] = (
    starterTargetPathwayCountsDF["numOneStepPathways"]
    + starterTargetPathwayCountsDF["numTwoStepPathways"]
    + starterTargetPathwayCountsDF["numThreeStepPathways"]
)

starterTargetPathwayCountsDF = (
    starterTargetPathwayCountsDF
    .sort_values("totalStarterToTargetPathways", ascending=False)
    .reset_index(drop=True)
)

print(f"Total reaction-step rows             : {len(reconstructedPathwaysDF):,}")
print(f"Complete starter --> target pathways: {len(completeRouteLevelDF):,}")
print(f"Job folders reached starter --> target: {starterTargetPathwayCountsDF['dirName'].nunique():,}")

starterTargetPathwayCountsDF

Total reaction-step rows             : 8,778
Complete starter --> target pathways: 2,968
Job folders reached starter --> target: 12

numSteps,dirName,jobName,generationRun,starterSMILES,targetSMILES,numOneStepPathways,numTwoStepPathways,numThreeStepPathways,totalStarterToTargetPathways
0,high_pPotency_molecule_pathway18_wGen3,high_pPotency_molecule_pathway18_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,0,0,1229,1229
1,high_pPotency_molecule_pathway6_wGen3,high_pPotency_molecule_pathway6_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,0,0,989,989
2,high_pPotency_molecule_pathway2_wGen3,high_pPotency_molecule_pathway2_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,0,0,611,611
3,high_pPotency_molecule_pathway6_wGen2,high_pPotency_molecule_pathway6_wGen2,2,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,0,46,0,46
4,high_pPotency_molecule_pathway18_wGen2,high_pPotency_molecule_pathway18_wGen2,2,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,0,39,0,39
5,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,0,27,0,27
6,high_pPotency_molecule_pathway16_wGen3,high_pPotency_molecule_pathway16_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,O=C(O)CC(=O)O,0,0,15,15
7,high_pPotency_molecule_pathway19_wGen3,high_pPotency_molecule_pathway19_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,CC(=O)CC(=O)O,0,0,4,4
8,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,1,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,3,0,0,3
9,high_pPotency_molecule_pathway6_wGen1,high_pPotency_molecule_pathway6_wGen1,1,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,3,0,0,3
10,high_pPotency_molecule_pathway18_wGen1,high_pPotency_molecule_pathway18_wGen1,1,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,1,0,0,1
11,high_pPotency_molecule_pathway12_wGen3,high_pPotency_molecule_pathway12_wGen3,3,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...,O=C1N=C2NC=Nc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@...,0,0,1,1

### `Thermodynamic` feasibility check

In [8]:
# -------------------------------------------------------------------
# Option B: post-hoc reaction enthalpy via Joback, computed directly
# from reconstructedPathwaysDF -- no DORAnet rerun required.
# -------------------------------------------------------------------
from thermo.group_contribution.joback import Joback

hfCacheKcalPerMol: dict[str, float | None] = {}

from rdkit import Chem

# Gas-phase ΔfH° (kcal/mol), small inorganics Joback's organic-only group scheme
# can't fragment at all (no carbon backbone). Sourced from NIST WebBook / CODATA
# unless noted. H2 and N2 are zero by definition (reference elemental states).
# Confidence is high for H2O/NH3/CO/H2/N2/CO2; lower for the sulfur/nitrogen
# oxoacids, since gas-phase data for those is less commonly tabulated -- verify
# against NIST WebBook directly if your network leans heavily on them.
knownHfKcalPerMol = {
    "O":          -57.80,   # H2O, NIST/CODATA gas phase
    "N":          -11.02,   # NH3, NIST/CODATA gas phase
    "S":           -4.93,   # H2S, NIST/CODATA gas phase
    "[H][H]":       0.00,   # H2, reference element
    "N#N":          0.00,   # N2, reference element
    "C=O":        -25.95,   # CH2O (formaldehyde), gas phase -- moderate confidence
    "[C-]#[O+]":  -26.42,   # CO, NIST/CODATA gas phase
    "O=[N+]([O-])O": -32.10,  # HNO3, gas phase -- lower confidence, verify
    "O=S(=O)(O)O":   None,    # H2SO4, gas-phase data too uncertain to assert -- left as None
    "O=S(O)O":       None,    # H2SO3, same caveat
}

def calculateHfCached(smiles: str) -> float | None:
    if smiles not in hfCacheKcalPerMol:
        canon = Chem.MolToSmiles(Chem.MolFromSmiles(smiles)) if Chem.MolFromSmiles(smiles) else smiles
        if canon in knownHfKcalPerMol:
            hfCacheKcalPerMol[smiles] = knownHfKcalPerMol[canon]
        else:
            try:
                j = Joback(smiles)
                hfCacheKcalPerMol[smiles] = j.Hf(j.counts) / 4184 if j.status == "OK" else None
            except Exception:
                hfCacheKcalPerMol[smiles] = None
    return hfCacheKcalPerMol[smiles]


def parseStoichTuple(stoichText):
    if stoichText is None or pd.isna(stoichText):
        return None
    try:
        parsed = ast.literal_eval(str(stoichText))
        return tuple(parsed) if isinstance(parsed, (list, tuple)) else None
    except Exception:
        return None


def computeStepDH(row) -> tuple[float | None, str, bool]:
    reactantMols = splitMoleculeString(row["reactants"])
    productMols = splitMoleculeString(row["products"])

    reactantStoich = parseStoichTuple(row.get("reactantStoich"))
    productStoich = parseStoichTuple(row.get("productStoich"))

    stoichWasInferred = False
    if reactantStoich is None or len(reactantStoich) != len(reactantMols):
        reactantStoich = (1,) * len(reactantMols)
        stoichWasInferred = True
    if productStoich is None or len(productStoich) != len(productMols):
        productStoich = (1,) * len(productMols)
        stoichWasInferred = True

    reactantHfs = [calculateHfCached(s) for s in reactantMols]
    productHfs = [calculateHfCached(s) for s in productMols]

    if any(hf is None for hf in reactantHfs + productHfs):
        return None, "missing_hf", stoichWasInferred

    dH = sum(hf * n for hf, n in zip(productHfs, productStoich)) \
       - sum(hf * n for hf, n in zip(reactantHfs, reactantStoich))
    return round(dH, 4), "ok", stoichWasInferred


dHResults = [
    computeStepDH(row)
    for _, row in tqdm(reconstructedPathwaysDF.iterrows(),
                        total=len(reconstructedPathwaysDF),
                        desc="Computing reaction enthalpies (Joback)")
]

reconstructedPathwaysDF["dH_kcal_per_mol"] = [r[0] for r in dHResults]
reconstructedPathwaysDF["dHStatus"] = [r[1] for r in dHResults]
reconstructedPathwaysDF["stoichWasInferred"] = [r[2] for r in dHResults]

print(reconstructedPathwaysDF["dHStatus"].value_counts(dropna=False).to_string())
print(f"Steps with inferred (1,1,...) stoichiometry: {reconstructedPathwaysDF['stoichWasInferred'].sum():,}")

# -------------------------------------------------------------------
# Roll step-level dH up to the route level, same logic DORAnet's own
# pathway_ranking() uses: a route is only as good as its worst step.
# -------------------------------------------------------------------
maxRxnThermoChange = 15  # kcal/mol -- tune this against your own dH distribution

routeThermoDF = (
    reconstructedPathwaysDF
    .groupby("routeId", as_index=False)
    .agg(
        maxStepDH=("dH_kcal_per_mol", "max"),
        minStepDH=("dH_kcal_per_mol", "min"),
        numStepsWithThermo=("dH_kcal_per_mol", lambda s: s.notna().sum()),
        numStepsTotal=("dH_kcal_per_mol", "size"),
        anyStoichInferred=("stoichWasInferred", "any"),
    )
)
routeThermoDF["allStepsHaveThermo"] = routeThermoDF["numStepsWithThermo"] == routeThermoDF["numStepsTotal"]
routeThermoDF["thermoFeasible"] = routeThermoDF["allStepsHaveThermo"] & (routeThermoDF["maxStepDH"] < maxRxnThermoChange)

completeRouteLevelDF = completeRouteLevelDF.merge(routeThermoDF, on="routeId", how="left")
print(f"\nRoutes with full thermo coverage: {routeThermoDF['allStepsHaveThermo'].sum():,} / {len(routeThermoDF):,}")
print(f"Routes passing {maxRxnThermoChange} kcal/mol cutoff: {routeThermoDF['thermoFeasible'].sum():,}")

Computing reaction enthalpies (Joback): 100%|████████████████████████████████████████████████████████| 8778/8778 [00:03<00:00, 2262.06it/s]

dHStatus
missing_hf    7639
ok            1139
Steps with inferred (1,1,...) stoichiometry: 0

Routes with full thermo coverage: 0 / 2,968
Routes passing 15 kcal/mol cutoff: 0

### Keep only `enzymatic` DORAnet reactions

In [9]:
enzymaticReactionDF = reconstructedPathwaysDF[
    reconstructedPathwaysDF["reactionType"].astype(str).str.lower().str.contains(
        "enzyme|enzymatic|bio|biological",
        na=False
    )
].copy()

print(f"Total reactions: {len(reconstructedPathwaysDF):,}")
print(f"Likely enzymatic reactions: {len(enzymaticReactionDF):,}")

enzymaticReactionDF.head()

Total reactions: 8,778
Likely enzymatic reactions: 8,778

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,networkMatchStatus,numReactantMolecules,numProductMolecules,starterInReactants,targetInProducts,isReconstructedPathwayStep,routeStepId,dH_kcal_per_mol,dHStatus,stoichWasInferred
0,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,1,...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...,NaN,missing_hf,False
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...,NaN,missing_hf,False
2,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,3,...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen1_route_00...,NaN,missing_hf,False
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,matched_by_reaction_and_rule,2,2,False,True,True,high_pPotency_molecule_pathway2_wGen2_route_00...,NaN,missing_hf,False
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,matched_by_reaction_and_rule,3,3,False,False,True,high_pPotency_molecule_pathway2_wGen2_route_00...,NaN,missing_hf,False

## 2. Use `DORA-XGB` to get feasibility score

In [10]:
reactionDF_DORAXGB = enzymaticReactionDF.copy()
#reactionDF_DORAXGB = enzymaticReactionDF.head(50).copy()

# Clean reaction string for model input
reactionDF_DORAXGB["rxn_str"] = (
    reactionDF_DORAXGB["reactionString"]
    .astype(str)
    .str.replace(" ", "", regex=False)
)

def getFeasibilityScoresAndLabels(rxnStr):
    return pd.Series({
        "feasibilityScore_rule1": by_desc_MW_model.predict_proba(rxnStr),
        "feasibilityLabel_rule1": by_desc_MW_model.predict_label(rxnStr),

        "feasibilityScore_rule2": by_asc_MW_model.predict_proba(rxnStr),
        "feasibilityLabel_rule2": by_asc_MW_model.predict_label(rxnStr),

        "feasibilityScore_rule3": add_concat_model.predict_proba(rxnStr),
        "feasibilityLabel_rule3": add_concat_model.predict_label(rxnStr),

        "feasibilityScore_rule4": add_subtract_model.predict_proba(rxnStr),
        "feasibilityLabel_rule4": add_subtract_model.predict_label(rxnStr),
    })


reactionDF_DORAXGB["rxn_str"] = (
    reactionDF_DORAXGB["reactionString"]
    .astype(str)
    .str.replace(" ", "", regex=False)
)

reactionDF_DORAXGB[
    [
        "feasibilityScore_rule1",
        "feasibilityLabel_rule1",
        "feasibilityScore_rule2",
        "feasibilityLabel_rule2",
        "feasibilityScore_rule3",
        "feasibilityLabel_rule3",
        "feasibilityScore_rule4",
        "feasibilityLabel_rule4",
    ]
] = reactionDF_DORAXGB["rxn_str"].apply(getFeasibilityScoresAndLabels)

reactionDF_DORAXGB.head()

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,stoichWasInferred,rxn_str,feasibilityScore_rule1,feasibilityLabel_rule1,feasibilityScore_rule2,feasibilityLabel_rule2,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4
0,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,1,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.000091,0.0,0.023566,0.0,0.133011,0.0,0.742495,1.0
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.331770,0.0,0.991104,1.0,0.992998,1.0,0.990675,1.0
2,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,3,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.000065,0.0,0.044277,0.0,0.096092,0.0,0.014657,0.0
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.021023,0.0,0.674617,1.0,0.928907,1.0,0.004875,0.0
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,False,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,0.000006,0.0,0.000189,0.0,0.003448,0.0,0.000042,0.0

### Keep only `high feasible` reactions

In [11]:
# Choose which feasibility label to use
feasibilityLabel = "feasibilityLabel_rule2"   # <- change to rule2/rule3/rule4 as needed
targetValue = 1                               # <- change if you want a different label value

# Optional safety check
validLabels = [
    "feasibilityLabel_rule1",
    "feasibilityLabel_rule2",
    "feasibilityLabel_rule3",
    "feasibilityLabel_rule4",
]
if feasibilityLabel not in validLabels:
    raise ValueError(f"Invalid feasibilityLabel: {feasibilityLabel}. Choose from {validLabels}")

if feasibilityLabel not in reactionDF_DORAXGB.columns:
    raise KeyError(f"Column '{feasibilityLabel}' not found in reactionDF_DORAXGB")

In [12]:
reactionDF_DORAXGB_highFeasibility = (
    reactionDF_DORAXGB[
        (reactionDF_DORAXGB[feasibilityLabel] == targetValue)
        & (reactionDF_DORAXGB[feasibilityLabel].notna())
    ]
    .sort_values(by=feasibilityLabel, ascending=False)
    .reset_index(drop=True)
)

uniqueReactantStrings_high = set(reactionDF_DORAXGB_highFeasibility["reactants"])
uniqueProductStrings_high = set(reactionDF_DORAXGB_highFeasibility["products"])

uniqueReactantMolecules_high = {
    mol.strip()
    for reactants in reactionDF_DORAXGB_highFeasibility["reactants"]
    for mol in str(reactants).split(".")
    if mol.strip()
}

uniqueProductMolecules_high = {
    mol.strip()
    for products in reactionDF_DORAXGB_highFeasibility["products"]
    for mol in str(products).split(".")
    if mol.strip()
}

print(f"Feasibility label used: {feasibilityLabel} == {targetValue}")
print(f"Number of high-feasibility reactions: {len(reactionDF_DORAXGB_highFeasibility)}")
print(f"Number of unique reactant strings: {len(uniqueReactantStrings_high)}")
print(f"Number of unique product strings: {len(uniqueProductStrings_high)}")
print(f"Number of unique individual reactant molecules: {len(uniqueReactantMolecules_high)}")
print(f"Number of unique individual product molecules: {len(uniqueProductMolecules_high)}")

reactionDF_DORAXGB_highFeasibility.to_csv(os.path.join(DNADesignResultsDir, f"DORAXGB_highFeasibility_{feasibilityLabel}.csv"),index=False)
reactionDF_DORAXGB_highFeasibility.head()

Feasibility label used: feasibilityLabel_rule2 == 1
Number of high-feasibility reactions: 2828
Number of unique reactant strings: 486
Number of unique product strings: 551
Number of unique individual reactant molecules: 234
Number of unique individual product molecules: 498

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,stoichWasInferred,rxn_str,feasibilityScore_rule1,feasibilityLabel_rule1,feasibilityScore_rule2,feasibilityLabel_rule2,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4
0,high_pPotency_molecule_pathway19_wGen3,high_pPotency_molecule_pathway19_wGen3,19,high_pPotency_molecule_pathway19_wGen3,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_network...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_route_0...,4,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.331770,0.0,0.991104,1.0,0.992998,1.0,0.990675,1.0
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.331770,0.0,0.991104,1.0,0.992998,1.0,0.990675,1.0
2,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.021023,0.0,0.674617,1.0,0.928907,1.0,0.004875,0.0
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,5,...,False,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,0.547657,0.0,0.846818,1.0,0.253301,0.0,0.196183,0.0
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,6,...,False,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,0.106657,0.0,0.810378,1.0,0.734912,1.0,0.619011,0.0

reactionDF_DORAXGB_highFeasibility = pd.read_csv(os.path.join(DNADesignResultsDir, "DORAXGB_highFeasibility_reactions.csv"))
reactionDF_DORAXGB_highFeasibility

### Summarize unique DORAnet rules

Many reactions may use the same rule. We do not want to annotate millions of reactions one by one. First annotate the rules.

In [13]:
enzymaticReactionDF = reactionDF_DORAXGB_highFeasibility.copy()
ruleSummaryDF = (
    enzymaticReactionDF
    .groupby(["ruleName", "reactionType"], dropna=False)
    .agg(
        numReactions=("reactionString", "count"),
        #numStarterSources=("sourceFolderNum", "nunique"),
        exampleReaction=("reactionString", "first"),
        exampleReactants=("reactants", "first"),
        exampleProducts=("products", "first"),
    )
    .reset_index()
    .sort_values("numReactions", ascending=False)
)

print(f"unique DORAnet rules    : {enzymaticReactionDF['ruleName'].nunique():,}")
ruleSummaryDF

unique DORAnet rules    : 37

,ruleName,reactionType,numReactions,exampleReaction,exampleReactants,exampleProducts
27,rule0062_18,Enzymatic,719,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
33,rule0165_2,Enzymatic,371,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...
16,rule0011_51,Enzymatic,370,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...
28,rule0062_19,Enzymatic,264,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)O[C@@H]1[C@H](O)[C@@H](C)O[C@H]1n1cnc2c(...
29,rule0073_5,Enzymatic,214,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
31,rule0121_1,Enzymatic,206,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[n+]1cn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c2n...
15,rule0011_50,Enzymatic,129,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...
36,rule0491_2,Enzymatic,92,COC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,COC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,C=O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP...
8,rule0003_176,Enzymatic,90,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...
24,rule0048_5,Enzymatic,59,C[n+]1cn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c2n...,C[n+]1cn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c2n...,C[n+]1cn([C@@H]2O[C@H](CO)[C@@H](OS(=O)(=O)O)[...
26,rule0062_17,Enzymatic,56,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC(C)O[C@H]1[C@@H](O)[C@]2(n3cnc4c(=O)[n...
9,rule0003_177,Enzymatic,43,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
23,rule0043_12,Enzymatic,40,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CCC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cn...
32,rule0164_2,Enzymatic,32,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
13,rule0007_198,Enzymatic,24,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@...
35,rule0169_1,Enzymatic,19,O=C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,O=C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,O=c1[nH]c2nc3c1ncn3[C@@H]1O[C@H](CO)[C@@H](O2)...
11,rule0007_161,Enzymatic,13,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@...
19,rule0017_16,Enzymatic,11,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)...
17,rule0015_21,Enzymatic,11,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...
34,rule0166_2,Enzymatic,11,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(N)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...
21,rule0028_35,Enzymatic,7,O=c1[nH]cnc2c1ncn2[C@@]1(CO)OC[C@@H](O)[C@H]1O...,O=c1[nH]cnc2c1ncn2[C@@]1(CO)OC[C@@H](O)[C@H]1O,O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@H](O)[C@H]1O
14,rule0011_49,Enzymatic,6,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,COC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...
22,rule0042_09,Enzymatic,6,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)NC(C)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc3...
30,rule0083_11,Enzymatic,5,CC(=O)O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP...,CC(=O)O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP...,COC(=O)O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)...
10,rule0004_13,Enzymatic,5,CC(=O)O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP...,CC(=O)O.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
0,rule0002_153,Enzymatic,4,CC(O)OC[C@H]1O[C@@]2(n3cnc4c(=O)[nH]cnc43)O[C@...,CC(O)OC[C@H]1O[C@@]2(n3cnc4c(=O)[nH]cnc43)O[C@...,CC(=O)OC[C@H]1O[C@@]2(n3cnc4c(=O)[nH]cnc43)O[C...
5,rule0003_173,Enzymatic,4,CCC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cn...,CCC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cn...,CCC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...
4,rule0003_171,Enzymatic,2,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
1,rule0002_154,Enzymatic,2,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1c(C)n...,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1c(C)n...,CC(=O)O[C@@H]1[C@H](O)[C@@H](C=O)O[C@H]1n1c(C)...
12,rule0007_195,Enzymatic,2,O.O=C(O)CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O...,O.O=C(O)CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O...,O=C(O)CC(=O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](...
20,rule0024_52,Enzymatic,2,O=C(O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...,O=C(O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...,O=C=O.O=c1[nH]cnc2c1ncn2[C@@H]1OC[C@@H](O)[C@H]1O
6,rule0003_174,Enzymatic,2,CC(=O)[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(...,CC(=O)[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(...,CC(O)[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(=...
18,rule0015_34,Enzymatic,2,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](OP(=...
25,rule0048_6,Enzymatic,2,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...
2,rule0003_152,Enzymatic,1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
3,rule0003_170,Enzymatic,1,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...
7,rule0003_175,Enzymatic,1,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...

### Add required placeholder columns

In [14]:
enzymeAnnotationDF = ruleSummaryDF.copy()

enzymeAnnotationDF["suggestedEnzymeClass"] = ""
enzymeAnnotationDF["ecNumber"] = ""
enzymeAnnotationDF["enzymeName"] = ""
enzymeAnnotationDF["uniprotAccession"] = ""
enzymeAnnotationDF["sourceDatabase"] = ""
enzymeAnnotationDF["reactionSimilarity"] = ""
enzymeAnnotationDF["enzymeConfidence"] = ""
enzymeAnnotationDF["notes"] = ""
enzymeAnnotationDF.head()

,ruleName,reactionType,numReactions,exampleReaction,exampleReactants,exampleProducts,suggestedEnzymeClass,ecNumber,enzymeName,uniprotAccession,sourceDatabase,reactionSimilarity,enzymeConfidence,notes
27,rule0062_18,Enzymatic,719,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,,,,,,,,
33,rule0165_2,Enzymatic,371,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,,,,,,,,
16,rule0011_51,Enzymatic,370,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,,,,,,,,
28,rule0062_19,Enzymatic,264,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)O[C@@H]1[C@H](O)[C@@H](C)O[C@H]1n1cnc2c(...,,,,,,,,
29,rule0073_5,Enzymatic,214,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,,,,,,,,

## 3. Read DORAnet reaction ruleset file to extract `UniProt ID` for each `reaction rule`

In [15]:
doranetRulesetDF = pd.read_csv(dataDir + "/DORAnet/JN3604IMT_rules.tsv", sep="\t")

print(doranetRulesetDF.shape)
print(doranetRulesetDF.columns.tolist())
doranetRulesetDF.head()

(3604, 5)
['Name', 'Reactants', 'SMARTS', 'Products', 'Comments']

,Name,Reactants,SMARTS,Products,Comments
0,rule0001_01,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,P97259;P97402;Q08834;Q09328;Q16408;Q3V5L5;Q765...
1,rule0001_02,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,A0K8D0;A0KHH6;A0KZ10;A0L8R9;A0Q7X9;A1A7M6;A1K6...
2,rule0001_03,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,P0DMP6;P0DMP7;P16442;Q15951;Q1RLK6;Q3USF0;Q5HZ...
3,rule0001_04,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,A4IID1;O19071;O77836;P23336;P26572;P27115;P278...
4,rule0001_05,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,NaN

### Find the number of common reaction rules between `DORAnet` diversification and ruleset table from actual package

In [16]:
reactionRuleSet = set(reactionDF_DORAXGB_highFeasibility["ruleName"].dropna().astype(str).str.strip())
tsvRuleSet = set(doranetRulesetDF["Name"].dropna().astype(str).str.strip())

matchedRuleSet = reactionRuleSet.intersection(tsvRuleSet)
missingRuleSet = reactionRuleSet.difference(tsvRuleSet)

print(f"Rules present in DORAnet diversification run: {len(reactionRuleSet):,}")
print(f"Rules matched from DORAnet package: {len(matchedRuleSet):,}")
print(f"Rules missing from DORAnet package: {len(missingRuleSet):,}")

print("\nMatched rules:")
print(sorted(list(matchedRuleSet))[:20])

print("\nMissing rules:")
print(sorted(list(missingRuleSet))[:20])

Rules present in DORAnet diversification run: 37
Rules matched from DORAnet package: 37
Rules missing from DORAnet package: 0

Matched rules:
['rule0002_153', 'rule0002_154', 'rule0003_152', 'rule0003_170', 'rule0003_171', 'rule0003_173', 'rule0003_174', 'rule0003_175', 'rule0003_176', 'rule0003_177', 'rule0004_13', 'rule0007_161', 'rule0007_195', 'rule0007_198', 'rule0011_49', 'rule0011_50', 'rule0011_51', 'rule0015_21', 'rule0015_34', 'rule0017_16']

Missing rules:
[]

### Extract `UniProt IDs` from `DORAnet` reaction rules

In [17]:
def splitUniProtIds(idString):
    if pd.isna(idString):
        return []
    return [x.strip() for x in str(idString).split(";") if x.strip()]


ruleInfoDF = doranetRulesetDF.copy()

ruleInfoDF = ruleInfoDF.rename(columns={
    "Name": "ruleName",
    "Reactants": "ruleReactants",
    "SMARTS": "ruleSMARTS",
    "Products": "ruleProducts",
    "Comments": "candidateUniProtRaw",
})

ruleInfoDF["ruleName"] = ruleInfoDF["ruleName"].astype(str).str.strip()
ruleInfoDF["candidateUniProtList"] = ruleInfoDF["candidateUniProtRaw"].apply(splitUniProtIds)
ruleInfoDF["numCandidateUniProt"] = ruleInfoDF["candidateUniProtList"].apply(len)

ruleInfoDF = ruleInfoDF[
    [
        "ruleName",
        "ruleReactants",
        "ruleProducts",
        "ruleSMARTS",
        "candidateUniProtRaw",
        "numCandidateUniProt",
    ]
].copy()



print(f"ruleInfoDF rows: {len(ruleInfoDF):,}")
ruleInfoDF

ruleInfoDF rows: 3,604

,ruleName,ruleReactants,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt
0,rule0001_01,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,P97259;P97402;Q08834;Q09328;Q16408;Q3V5L5;Q765...,10
1,rule0001_02,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,A0K8D0;A0KHH6;A0KZ10;A0L8R9;A0Q7X9;A1A7M6;A1K6...,263
2,rule0001_03,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,P0DMP6;P0DMP7;P16442;Q15951;Q1RLK6;Q3USF0;Q5HZ...,29
3,rule0001_04,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,A4IID1;O19071;O77836;P23336;P26572;P27115;P278...,42
4,rule0001_05,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,NaN,0
...,...,...,...,...,...,...
3599,rule1152_1,Any;Any,Any;Any,[#6;$([#6&R]1-&@[#8&R]-&@[#6&R]-&@[#6&R](-&@[#...,Q8ZUN8,1
3600,rule1152_2,Any;Any,Any;Any,[#6;!$([#6&R]1-&@[#8&R]-&@[#6&R]-&@[#6&R](-&@[...,B9TTF1,1
3601,rule1164_1,Any;WATER,Any;H2O2,[#6;$([#6&!R]-&!@[#6&R]1:&@[#6&R]:&@[#6&R]:&@[...,Q972I2,1
3602,rule1165_1,Any;H2O2,Any;WATER,[#6;$([#6&!R]-[#6&R]1:&@[#6&R]:&@[#6&R]:&@[#6&...,Q972I2,1
3603,rule1165_2,Any;H2O2,Any;WATER,[#6;$([#6&R]1:[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R...,B0CN28;B9W4V6;O31440;Q2HHI5,4

## 4. Merge rule information into `reactionDF`

This connects DORAnet reactions with the rule SMARTS and UniProt candidate list.

In [18]:
reactionDF_wUniprotID = reactionDF_DORAXGB_highFeasibility.merge(ruleInfoDF,on="ruleName",how="left")

reactionDF_wUniprotID["hasRuleLookup"] = reactionDF_wUniprotID["ruleSMARTS"].notna()

print(reactionDF_wUniprotID["hasRuleLookup"].value_counts(dropna=False))
reactionDF_wUniprotID

hasRuleLookup
True    2828
Name: count, dtype: int64

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4,ruleReactants,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt,hasRuleLookup
0,high_pPotency_molecule_pathway19_wGen3,high_pPotency_molecule_pathway19_wGen3,19,high_pPotency_molecule_pathway19_wGen3,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_network...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_route_0...,4,...,0.992998,1.0,0.990675,1.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,0.992998,1.0,0.990675,1.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True
2,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,0.928907,1.0,0.004875,0.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,5,...,0.253301,0.0,0.196183,0.0,METHYL_DONOR_CoF;Any,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,6,...,0.734912,1.0,0.619011,0.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,16,...,0.938749,1.0,0.635091,0.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True
2824,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,18,...,0.992645,1.0,0.981038,1.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True
2825,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,18,...,0.292121,0.0,0.025673,0.0,METHYL_DONOR_CoF;Any,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True
2826,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,20,...,0.983387,1.0,0.768436,1.0,ACETYL-COA;Any,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True
2827,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,20,...,0.253301,0.0,0.196183,0.0,METHYL_DONOR_CoF;Any,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True

reactionDF_wUniprotID_display = reactionDF_wUniprotID[
    ["reactants", "products", "reactionString", "ruleName", "candidateUniProtRaw", "feasibilityScore_rule1"]].copy()
reactionDF_wUniprotID_display = reactionDF_wUniprotID_display.drop_duplicates(
    subset=["ruleName"], keep="first"
).copy()
reactionDF_wUniprotID_display

## 4. Find best `UniProt ID` per rule by `Reaction Center Morgan Fingerprint (RCMFP)` enzyme retrieval similarity search 

Implements workflow from the DORAnet/DORA-XGB → atom mapping → RCMFP → known enzyme retrieval. It uses `ruleBase` as the practical bridge between expanded DORAnet rule names such as `rule0003_170` and known reference coarse operator IDs such as `rule0003`, then ranks candidate natural enzyme precedents by RCMFP Tanimoto similarity.

Use this tool: https://github.com/stefanpate/ergochemics/tree/main#

### Patch `RDKit/ergochemics` compatibility

This preserves atom-map labels. Do not use a patch that clears atom-map numbers, because RCMFP needs atom maps to infer reaction centers.

In [19]:
# User paths
ERGOCHEMICS_SRC = "/users/sghosh6/DTRA_project/MACAW/ergochemics/src"
if ERGOCHEMICS_SRC not in sys.path: sys.path.insert(0, ERGOCHEMICS_SRC)

import ergochemics.mapping as egmap
import ergochemics.similarity as egsim
print("RDKit version:", rdBase.rdkitVersion); print("ergochemics mapping file:", egmap.__file__)

_RDKit_MolToSmiles_original = rdmolfiles.MolToSmiles

def MolToSmiles_compat(mol, *args, **kwargs):
    kwargs.pop("ignoreAtomMapNumbers", None)
    return _RDKit_MolToSmiles_original(mol, *args, **kwargs)

Chem.MolToSmiles = MolToSmiles_compat; egmap.Chem.MolToSmiles = MolToSmiles_compat; egsim.Chem.MolToSmiles = MolToSmiles_compat
operator_map_reaction, get_reaction_center = egmap.operator_map_reaction, egmap.get_reaction_center
ReactionFingerprinter, MolFeaturizer = egsim.ReactionFingerprinter, egsim.MolFeaturizer
print("Patch test:", Chem.MolToSmiles(Chem.MolFromSmiles("[CH3:1][OH:2]"), ignoreAtomMapNumbers=True))

RDKit version: 2023.09.5
ergochemics mapping file: /users/sghosh6/DTRA_project/MACAW/ergochemics/src/ergochemics/mapping.py
Patch test: [CH3:1][OH:2]

### Normalize DORAnet reaction strings and `atom-map` all reactions

In [20]:
def normalize_reaction_string(rxn):
    if pd.isna(rxn): return None
    rxn = str(rxn).strip().replace(" ", "")
    if rxn.count(">") == 2 and ">>" in rxn: return rxn
    parts = rxn.split(">")
    return f"{parts[0]}>>{parts[2]}" if len(parts) == 3 else None

def map_query_reaction_with_rule(row):
    rxn, ruleSMARTS = row.get("queryReaction"), row.get("ruleSMARTS")
    if pd.isna(rxn) or str(rxn).strip() == "": return None, "missing_queryReaction"
    if pd.isna(ruleSMARTS) or str(ruleSMARTS).strip() == "": return None, "missing_ruleSMARTS"
    rxn, ruleSMARTS, lastError = str(rxn).replace(" ", ""), str(ruleSMARTS).strip(), None
    if ">>" not in rxn: return None, "invalid_queryReaction_no_double_arrow"
    if ">>" not in ruleSMARTS: return None, "invalid_ruleSMARTS_no_double_arrow"
    for explicitHsFlag, statusLabel in [(False, "mapped"), (True, "mapped_explicit_h")]:
        try:
            result = operator_map_reaction(rxn=rxn, operator=ruleSMARTS, explicit_hs=explicitHsFlag, quiet=True)
            if result.did_map and result.atom_mapped_smarts is not None: return result.atom_mapped_smarts, statusLabel
            lastError = f"{statusLabel}_failed"
        except Exception as exc: lastError = f"mapping_error:{type(exc).__name__}:{exc}"
    return None, lastError

AtomMapDF = reactionDF_wUniprotID.copy()
AtomMapDF["queryReaction"] = AtomMapDF["reactionString"].apply(normalize_reaction_string)
AtomMapDF = AtomMapDF[AtomMapDF["queryReaction"].notna() & AtomMapDF["ruleSMARTS"].notna()].drop(columns=["queryMappedReaction", "rcmfpMappingStatus"], errors="ignore").copy()

mappedPairs = AtomMapDF.progress_apply(map_query_reaction_with_rule, axis=1)
AtomMapDF[["queryMappedReaction", "rcmfpMappingStatus"]] = pd.DataFrame(mappedPairs.tolist(), index=AtomMapDF.index)
sucessAtomMapDF = AtomMapDF[AtomMapDF["queryMappedReaction"].notna()].copy() 
failedAtomMapDF = AtomMapDF[AtomMapDF["queryMappedReaction"].isna()].copy()
print(AtomMapDF["rcmfpMappingStatus"].value_counts(dropna=False))
print("Successful atom mapping:", len(sucessAtomMapDF), "| Failed:", len(failedAtomMapDF))
sucessAtomMapDF.shape

100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2828/2828 [00:29<00:00, 94.64it/s]

rcmfpMappingStatus
mapped    2828
Name: count, dtype: int64
Successful atom mapping: 2828 | Failed: 0

(2828, 55)

### Compute `RCMFP fingerprints`

In [21]:
TOP_K, MIN_SIMILARITY, FP_SIDE_LENGTH, FP_RADIUS = 20, 0.0, 2048, 2

In [22]:
reactionFingerprinter = ReactionFingerprinter(radius=FP_RADIUS, length=FP_SIDE_LENGTH, mol_featurizer=MolFeaturizer())

def compute_rcmfp_with_status(mappedRxn):
    try:
        if pd.isna(mappedRxn) or str(mappedRxn).strip() == "": return None, "missing_mapped_reaction"
        mappedRxn = str(mappedRxn).replace(" ", "")
        if ">>" not in mappedRxn: return None, "invalid_mapped_reaction_no_double_arrow"
        if not pd.Series([mappedRxn]).str.contains(r":\d+\]", regex=True).iloc[0]: return None, "no_atom_map_labels"
        lrc, rrc = get_reaction_center(mappedRxn, mode="combined")
        if len(lrc) == 0 or len(rrc) == 0: return None, f"empty_reaction_center:lrc={len(lrc)}:rrc={len(rrc)}"
        fp = reactionFingerprinter.fingerprint(mappedRxn, output_type="bit", use_rc=True, rc_dist_ub=None)
        return fp.astype(bool), "rcmfp_success"
    except Exception as exc: return None, f"rcmfp_error:{type(exc).__name__}:{exc}"


rcmfpPairs = sucessAtomMapDF["queryMappedReaction"].progress_apply(compute_rcmfp_with_status)
sucessAtomMapDF[["queryRCMFP", "rcmfpStatus"]] = pd.DataFrame(rcmfpPairs.tolist(), index=sucessAtomMapDF.index)
queryRcmfpFailureDF = sucessAtomMapDF[sucessAtomMapDF["queryRCMFP"].isna()].copy()
sucessAtomMapDF = sucessAtomMapDF[sucessAtomMapDF["queryRCMFP"].notna()].copy().reset_index(drop=True)
sucessAtomMapDF

  0%|                                                                                                     | 3/2828 [00:00<02:44, 17.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

  0%|▏                                                                                                    | 5/2828 [00:00<03:03, 15.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  0%|▎                                                                                                    | 9/2828 [00:01<06:40,  7.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  0%|▍                                                                                                   | 13/2828 [00:01<07:22,  6.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 56, 53: 59, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 57, 64: 54, 65: 55, 66: 58, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 64, 65, 52, 63, 66, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 56, 53: 59, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 57, 64: 54, 65: 55, 66: 58, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 64, 65, 52, 63, 66, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  1%|▌                                                                                                   | 17/2828 [00:02<08:41,  5.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

  1%|▊                                                                                                   | 22/2828 [00:03<04:58,  9.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]

  1%|▊                                                                                                   | 24/2828 [00:03<04:23, 10.63it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  1%|▉                                                                                                   | 26/2828 [00:03<04:09, 11.25it/s]

{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  1%|█                                                                                                   | 30/2828 [00:04<08:42,  5.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]

  1%|█▏                                                                                                  | 32/2828 [00:05<08:14,  5.66it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

  1%|█▏                                                                                                  | 33/2828 [00:05<08:26,  5.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

  1%|█▏                                                                                                  | 34/2828 [00:05<09:05,  5.12it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

  1%|█▎                                                                                                  | 37/2828 [00:05<06:56,  6.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  1%|█▍                                                                                                  | 39/2828 [00:06<05:54,  7.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  1%|█▍                                                                                                  | 41/2828 [00:06<06:28,  7.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  1%|█▍                                                                                                  | 42/2828 [00:06<07:23,  6.28it/s]

{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

  2%|█▋                                                                                                  | 46/2828 [00:07<07:48,  5.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  2%|█▊                                                                                                  | 50/2828 [00:08<08:15,  5.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 61, 58: 64, 59: 65, 60: 67, 61: 69, 62: 66, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 61, 58: 64, 59: 65, 60: 67, 61: 69, 62: 66, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 56, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 57, 58, 54, 70, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 56, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 57, 58, 54, 70, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 64, 56: 65, 57: 58, 58: 61, 59: 62, 60: 59, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 60, 54, 58, 59, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 64, 56: 65, 57: 58, 58: 61, 59: 62, 60: 59, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 60, 54, 58, 59, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

  2%|█▊                                                                                                  | 52/2828 [00:08<07:00,  6.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 60, 58: 63, 59: 65, 60: 66, 61: 68, 62: 70, 63: 67, 64: 69, 65: 71, 66: 73, 67: 72, 68: 74, 69: 59, 70: 62, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 69, 57, 55, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 60, 58: 63, 59: 65, 60: 66, 61: 68, 62: 70, 63: 67, 64: 69, 65: 71, 66: 73, 67: 72, 68: 74, 69: 59, 70: 62, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 69, 57, 55, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]

  2%|█▉                                                                                                  | 56/2828 [00:08<05:10,  8.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]

  2%|██                                                                                                  | 58/2828 [00:08<04:51,  9.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

  2%|██▏                                                                                                 | 62/2828 [00:09<04:07, 11.16it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

  2%|██▎                                                                                                 | 64/2828 [00:09<04:08, 11.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 60, 58: 62, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 57, 69, 58, 70, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 60, 58: 62, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 57, 69, 58, 70, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 61, 58: 64, 59: 62, 60: 60, 61: 63, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 61, 58: 64, 59: 62, 60: 60, 61: 63, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

  2%|██▍                                                                                                 | 68/2828 [00:09<04:06, 11.18it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 66, 55: 56, 56: 60, 57: 64, 58: 67, 59: 69, 60: 65, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 55, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 55, 52, 68, 66, 56, 53, 69, 70, 57, 60, 54, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 66, 55: 56, 56: 60, 57: 64, 58: 67, 59: 69, 60: 65, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 55, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 55, 52, 68, 66, 56, 53, 69, 70, 57, 60, 54, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 38, 38: 40, 39: 42, 40: 39, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46, 46: 36, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 38, 38: 40, 39: 42, 40: 39, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46, 46: 36, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

  2%|██▍                                                                                                 | 70/2828 [00:09<03:54, 11.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 58, 53: 60, 54: 61, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 67, 55, 52, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 58, 53: 60, 54: 61, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 67, 55, 52, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  3%|██▌                                                                                                 | 74/2828 [00:10<05:49,  7.89it/s]

{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 64, 56: 57, 57: 60, 58: 63, 59: 58, 60: 62, 61: 65, 62: 66, 63: 68, 64: 71, 65: 70, 66: 67, 67: 69, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 56, 59, 53, 57, 54, 60, 58, 55, 61, 62, 66, 63, 67, 65, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 64, 56: 57, 57: 60, 58: 63, 59: 58, 60: 62, 61: 65, 62: 66, 63: 68, 64: 71, 65: 70, 66: 67, 67: 69, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 56, 59, 53, 57, 54, 60, 58, 55, 61, 62, 66, 63, 67, 65, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  3%|██▋                                                                                                 | 76/2828 [00:11<08:34,  5.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 63, 58: 66, 59: 60, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 55, 59, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 63, 58: 66, 59: 60, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 55, 59, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

  3%|██▊                                                                                                 | 80/2828 [00:11<06:15,  7.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

  3%|██▉                                                                                                 | 84/2828 [00:12<05:55,  7.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 72, 63: 71, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 68, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 58, 69, 56, 59, 57, 70, 71, 60, 63, 62, 61, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 72, 63: 71, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 68, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 58, 69, 56, 59, 57, 70, 71, 60, 63, 62, 61, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  3%|███                                                                                                 | 86/2828 [00:12<05:23,  8.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 55, 52: 54, 53: 58, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 56, 67: 59, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 52, 51, 66, 54, 53, 67, 65, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 55, 52: 54, 53: 58, 54: 57, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 56, 67: 59, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 52, 51, 66, 54, 53, 67, 65, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 56, 55: 58, 56: 59, 57: 60, 58: 62, 59: 65, 60: 67, 61: 69, 62: 71, 63: 68, 64: 70, 65: 72, 66: 74, 67: 73, 68: 75, 69: 63, 70: 66, 71: 61, 72: 64, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 54, 53, 55, 56, 57, 71, 58, 69, 72, 59, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 56, 55: 58, 56: 59, 57: 60, 58: 62, 59: 65, 60: 67, 61: 69, 62: 71, 63: 68, 64: 70, 65: 72, 66: 74, 67: 73, 68: 75, 69: 63, 70: 66, 71: 61, 72: 64, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 54, 53, 55, 56, 57, 71, 58, 69, 72, 59, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

  3%|███▏                                                                                                | 90/2828 [00:12<04:43,  9.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 63, 57: 66, 58: 67, 59: 61, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 63, 57: 66, 58: 67, 59: 61, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 61, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

  3%|███▎                                                                                                | 92/2828 [00:12<04:31, 10.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  3%|███▎                                                                                                | 94/2828 [00:13<05:12,  8.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  3%|███▎                                                                                                | 95/2828 [00:13<08:46,  5.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  3%|███▍                                                                                                | 98/2828 [00:14<08:55,  5.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 66, 56: 65, 57: 61, 58: 64, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 59, 65: 62, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 63, 52, 67, 64, 53, 57, 65, 54, 58, 56, 55, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 66, 56: 65, 57: 61, 58: 64, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 59, 65: 62, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 63, 52, 67, 64, 53, 57, 65, 54, 58, 56, 55, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 61, 66: 64, 67: 68, 68: 69, 69: 56, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 64, 70, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 61, 66: 64, 67: 68, 68: 69, 69: 56, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 64, 70, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]

  4%|███▌                                                                                               | 100/2828 [00:14<07:16,  6.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 61, 57: 63, 58: 66, 59: 59, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 61, 57: 63, 58: 66, 59: 59, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

  4%|███▋                                                                                               | 104/2828 [00:14<04:53,  9.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

  4%|███▋                                                                                               | 106/2828 [00:14<04:10, 10.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  4%|███▉                                                                                               | 111/2828 [00:15<05:23,  8.40it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

  4%|███▉                                                                                               | 114/2828 [00:16<05:20,  8.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

  4%|████                                                                                               | 116/2828 [00:16<05:37,  8.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  4%|████▏                                                                                              | 120/2828 [00:17<06:25,  7.03it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 67, 60: 71, 61: 59, 62: 61, 63: 63, 64: 68, 65: 70, 66: 64, 67: 69, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 54, 53, 61, 55, 62, 56, 63, 66, 57, 58, 59, 64, 67, 65, 60, 68, 70, 69, 71]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 67, 60: 71, 61: 59, 62: 61, 63: 63, 64: 68, 65: 70, 66: 64, 67: 69, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 54, 53, 61, 55, 62, 56, 63, 66, 57, 58, 59, 64, 67, 65, 60, 68, 70, 69, 71]
[1, 49, 50]

  4%|████▎                                                                                              | 124/2828 [00:17<04:44,  9.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

  4%|████▍                                                                                              | 126/2828 [00:17<04:23, 10.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

  5%|████▍                                                                                              | 128/2828 [00:17<04:03, 11.10it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

  5%|████▌                                                                                              | 132/2828 [00:18<07:02,  6.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]

  5%|████▋                                                                                              | 134/2828 [00:18<06:09,  7.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 60, 66: 62, 67: 57, 68: 59, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 53, 67, 54, 68, 65, 55, 66, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 60, 66: 62, 67: 57, 68: 59, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 53, 67, 54, 68, 65, 55, 66, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|████▊                                                                                              | 136/2828 [00:19<08:44,  5.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

  5%|████▊                                                                                              | 138/2828 [00:19<07:17,  6.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|████▊                                                                                              | 139/2828 [00:20<10:28,  4.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|█████                                                                                              | 143/2828 [00:21<09:17,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]

  5%|█████                                                                                              | 145/2828 [00:21<07:39,  5.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 71, 60: 70, 61: 68, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 69, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 56, 65, 54, 57, 55, 66, 58, 61, 67, 60, 59, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 71, 60: 70, 61: 68, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 69, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 56, 65, 54, 57, 55, 66, 58, 61, 67, 60, 59, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|█████▏                                                                                             | 149/2828 [00:22<07:48,  5.72it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|█████▎                                                                                             | 150/2828 [00:22<10:58,  4.06it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|█████▎                                                                                             | 153/2828 [00:23<10:14,  4.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 60, 65: 56, 66: 58, 67: 62, 68: 65, 69: 66, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 70, 64, 54, 67, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 60, 65: 56, 66: 58, 67: 62, 68: 65, 69: 66, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 70, 64, 54, 67, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]

  5%|█████▍                                                                                             | 155/2828 [00:23<08:05,  5.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 69, 66: 55, 67: 58, 68: 62, 69: 67, 70: 68, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 69, 70, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  6%|█████▌                                                                                             | 159/2828 [00:24<06:07,  7.26it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  6%|█████▋                                                                                             | 163/2828 [00:24<04:47,  9.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 61, 58: 64, 59: 68, 60: 69, 61: 59, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 55, 53, 52, 56, 61, 54, 57, 62, 65, 58, 63, 66, 64, 59, 60, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 61, 58: 64, 59: 68, 60: 69, 61: 59, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 55, 53, 52, 56, 61, 54, 57, 62, 65, 58, 63, 66, 64, 59, 60, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 61, 58: 64, 59: 68, 60: 69, 61: 59, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 55, 53, 52, 56, 61, 54, 57, 62, 65, 58, 63, 66, 64, 59, 60, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 61, 58: 64, 59: 68, 60: 69, 61: 59, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 55, 53, 52, 56, 61, 54, 57, 62, 65, 58, 63, 66, 64, 59, 60, 67, 69, 68, 70]
[1, 49, 50]

  6%|█████▊                                                                                             | 165/2828 [00:24<04:30,  9.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|█████▊                                                                                             | 167/2828 [00:25<07:33,  5.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 61, 57: 63, 58: 67, 59: 69, 60: 64, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 58, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 52, 54, 66, 55, 67, 56, 68, 57, 60, 69, 70, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 61, 57: 63, 58: 67, 59: 69, 60: 64, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 58, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 52, 54, 66, 55, 67, 56, 68, 57, 60, 69, 70, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 65, 58: 64, 59: 66, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 69, 66: 67, 67: 61, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 65, 58: 64, 59: 66, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 69, 66: 67, 67: 61, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

  6%|█████▉                                                                                             | 171/2828 [00:26<07:43,  5.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

  6%|██████▏                                                                                            | 175/2828 [00:26<05:15,  8.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  6%|██████▎                                                                                            | 179/2828 [00:26<05:58,  7.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 58, 54: 56, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 55, 67: 59, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 54, 52, 53, 67, 65, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 58, 54: 56, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 55, 67: 59, 68: 62, 69: 65, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 54, 52, 53, 67, 65, 55, 68, 56, 59, 69, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  6%|██████▎                                                                                            | 181/2828 [00:27<05:22,  8.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

  6%|██████▍                                                                                            | 183/2828 [00:27<04:42,  9.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

  7%|██████▌                                                                                            | 187/2828 [00:27<04:47,  9.19it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]

  7%|██████▋                                                                                            | 191/2828 [00:28<04:10, 10.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 68, 66: 69, 67: 55, 68: 58, 69: 62, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 62, 52, 68, 63, 53, 56, 69, 64, 54, 57, 55, 70, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 68, 66: 69, 67: 55, 68: 58, 69: 62, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 62, 52, 68, 63, 53, 56, 69, 64, 54, 57, 55, 70, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|██████▊                                                                                            | 195/2828 [00:29<08:32,  5.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 65, 56: 67, 57: 69, 58: 66, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 55, 65: 59, 66: 61, 67: 63, 68: 64, 69: 57, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 64, 52, 69, 70, 65, 53, 66, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 65, 56: 67, 57: 69, 58: 66, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 55, 65: 59, 66: 61, 67: 63, 68: 64, 69: 57, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 64, 52, 69, 70, 65, 53, 66, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 63, 65: 67, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  7%|██████▉                                                                                            | 199/2828 [00:29<06:44,  6.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████                                                                                            | 202/2828 [00:30<07:40,  5.70it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

  7%|███████▏                                                                                           | 204/2828 [00:30<06:15,  7.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 64, 57: 61, 58: 57, 59: 59, 60: 55, 61: 58, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 52, 58, 61, 59, 53, 57, 62, 65, 56, 54, 55, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 64, 57: 61, 58: 57, 59: 59, 60: 55, 61: 58, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 52, 58, 61, 59, 53, 57, 62, 65, 56, 54, 55, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

  7%|███████▏                                                                                           | 206/2828 [00:30<05:29,  7.97it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████▎                                                                                           | 210/2828 [00:31<06:44,  6.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 33, 45: 36, 46: 39, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 47, 44, 34, 48, 45, 35, 38, 46, 36, 39, 37, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 33, 45: 36, 46: 39, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 47, 44, 34, 48, 45, 35, 38, 46, 36, 39, 37, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]

  7%|███████▍                                                                                           | 212/2828 [00:31<05:41,  7.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]

  8%|███████▌                                                                                           | 216/2828 [00:32<04:22,  9.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  8%|███████▋                                                                                           | 218/2828 [00:32<07:24,  5.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  8%|███████▋                                                                                           | 221/2828 [00:33<07:48,  5.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 64, 57: 61, 58: 57, 59: 59, 60: 55, 61: 58, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 52, 58, 61, 59, 53, 57, 62, 65, 56, 54, 55, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 64, 57: 61, 58: 57, 59: 59, 60: 55, 61: 58, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 52, 58, 61, 59, 53, 57, 62, 65, 56, 54, 55, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 64, 59: 59, 60: 62, 61: 65, 62: 63, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 69, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 62, 58, 61, 63, 70, 64, 69, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 64, 59: 59, 60: 62, 61: 65, 62: 63, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 69, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 62, 58, 61, 63, 70, 64, 69, 65, 67, 66, 68]
[1, 49, 50]

  8%|███████▊                                                                                           | 223/2828 [00:33<06:31,  6.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 61, 66: 64, 67: 68, 68: 69, 69: 57, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 69, 53, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 61, 66: 64, 67: 68, 68: 69, 69: 57, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 69, 53, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

  8%|███████▉                                                                                           | 227/2828 [00:34<05:06,  8.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  8%|████████                                                                                           | 229/2828 [00:34<04:29,  9.64it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

  8%|████████▏                                                                                          | 233/2828 [00:34<04:12, 10.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 65, 58: 68, 59: 58, 60: 61, 61: 59, 62: 62, 63: 66, 64: 69, 65: 71, 66: 67, 67: 70, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 53, 59, 61, 54, 60, 62, 55, 56, 57, 63, 66, 58, 64, 67, 65, 68, 70, 69, 71]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 65, 58: 68, 59: 58, 60: 61, 61: 59, 62: 62, 63: 66, 64: 69, 65: 71, 66: 67, 67: 70, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 53, 59, 61, 54, 60, 62, 55, 56, 57, 63, 66, 58, 64, 67, 65, 68, 70, 69, 71]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  8%|████████▎                                                                                          | 237/2828 [00:35<08:20,  5.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 68, 57: 71, 58: 59, 59: 55, 60: 58, 61: 61, 62: 64, 63: 69, 64: 72, 65: 70, 66: 73, 67: 65, 68: 67, 69: 62, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 59, 53, 52, 60, 58, 54, 61, 69, 55, 62, 67, 70, 68, 56, 63, 65, 57, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 68, 57: 71, 58: 59, 59: 55, 60: 58, 61: 61, 62: 64, 63: 69, 64: 72, 65: 70, 66: 73, 67: 65, 68: 67, 69: 62, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 59, 53, 52, 60, 58, 54, 61, 69, 55, 62, 67, 70, 68, 56, 63, 65, 57, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 66, 56: 62, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 60, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 66, 56: 62, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 60, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

  8%|████████▎                                                                                          | 239/2828 [00:36<06:59,  6.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|████████▌                                                                                          | 243/2828 [00:36<05:14,  8.23it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 56, 60: 62, 61: 66, 62: 70, 63: 71, 64: 67, 65: 68, 66: 65, 67: 69, 68: 72, 69: 73, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 57, 58, 54, 70, 60, 55, 56, 66, 61, 64, 65, 67, 62, 63, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 56, 60: 62, 61: 66, 62: 70, 63: 71, 64: 67, 65: 68, 66: 65, 67: 69, 68: 72, 69: 73, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 57, 58, 54, 70, 60, 55, 56, 66, 61, 64, 65, 67, 62, 63, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 57, 66: 51, 67: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 66, 67, 50, 51, 64, 52, 65, 53, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 57, 66: 51, 67: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 66, 67, 50, 51, 64, 52, 65, 53, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|████████▋                                                                                          | 247/2828 [00:37<06:12,  6.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|████████▋                                                                                          | 249/2828 [00:37<08:24,  5.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|████████▊                                                                                          | 253/2828 [00:38<07:59,  5.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 69, 59: 64, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 61, 67: 58, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 66, 68, 56, 59, 69, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 69, 59: 64, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 61, 67: 58, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 66, 68, 56, 59, 69, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|████████▉                                                                                          | 256/2828 [00:39<08:15,  5.19it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|█████████                                                                                          | 259/2828 [00:39<06:40,  6.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 59, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 57, 59, 55, 58, 60, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 59, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 57, 59, 55, 58, 60, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

  9%|█████████▏                                                                                         | 261/2828 [00:39<05:42,  7.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 69, 59: 72, 60: 70, 61: 73, 62: 56, 63: 59, 64: 62, 65: 66, 66: 71, 67: 67, 68: 68, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 67, 68, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 69, 59: 72, 60: 70, 61: 73, 62: 56, 63: 59, 64: 62, 65: 66, 66: 71, 67: 67, 68: 68, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 67, 68, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|█████████▏                                                                                         | 263/2828 [00:40<08:22,  5.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|█████████▎                                                                                         | 266/2828 [00:40<07:01,  6.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 63, 67: 58, 68: 62, 69: 61, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 63, 67: 58, 68: 62, 69: 61, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 57, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 67, 54, 65, 68, 55, 66, 69, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 57, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 67, 54, 65, 68, 55, 66, 69, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]

  9%|█████████▍                                                                                         | 268/2828 [00:41<05:34,  7.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 65, 58: 68, 59: 67, 60: 64, 61: 66, 62: 70, 63: 71, 64: 72, 65: 73, 66: 69, 67: 61, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 65, 58: 68, 59: 67, 60: 64, 61: 66, 62: 70, 63: 71, 64: 72, 65: 73, 66: 69, 67: 61, 68: 58, 69: 62, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 55, 54: 56, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 54, 52, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 55, 54: 56, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 54, 52, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 55, 67: 57, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 67, 53, 54, 56, 55, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 55, 67: 57, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 67, 53, 54, 56, 55, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]

 10%|█████████▌                                                                                         | 272/2828 [00:41<04:36,  9.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 58, 55: 61, 56: 64, 57: 68, 58: 70, 59: 65, 60: 69, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 63, 67: 57, 68: 59, 69: 62, 70: 66, 71: 67, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 53, 52, 67, 54, 68, 65, 55, 69, 66, 56, 59, 70, 71, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 58, 55: 61, 56: 64, 57: 68, 58: 70, 59: 65, 60: 69, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 63, 67: 57, 68: 59, 69: 62, 70: 66, 71: 67, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 53, 52, 67, 54, 68, 65, 55, 69, 66, 56, 59, 70, 71, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 57, 67: 56, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 57, 67: 56, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 10%|█████████▋                                                                                         | 276/2828 [00:41<04:49,  8.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 57, 67: 56, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 57, 67: 56, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 68, 64: 70, 65: 64, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 59, 55, 60, 56, 61, 65, 57, 58, 62, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 68, 64: 70, 65: 64, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 59, 55, 60, 56, 61, 65, 57, 58, 62, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 10%|█████████▋                                                                                         | 278/2828 [00:42<04:30,  9.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 59, 57, 58, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 59, 57, 58, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 10%|█████████▊                                                                                         | 280/2828 [00:42<05:15,  8.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 59, 57, 58, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 59, 57, 58, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 67, 56: 65, 57: 59, 58: 64, 59: 68, 60: 70, 61: 69, 62: 71, 63: 56, 64: 60, 65: 61, 66: 66, 67: 57, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 63, 67, 53, 57, 64, 65, 68, 54, 58, 56, 66, 55, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 67, 56: 65, 57: 59, 58: 64, 59: 68, 60: 70, 61: 69, 62: 71, 63: 56, 64: 60, 65: 61, 66: 66, 67: 57, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 63, 67, 53, 57, 64, 65, 68, 54, 58, 56, 66, 55, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 10%|█████████▉                                                                                         | 284/2828 [00:42<04:21,  9.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 58, 60: 62, 61: 65, 62: 64, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 69, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 58, 60: 62, 61: 65, 62: 64, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 69, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 55, 67: 57, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 67, 53, 54, 56, 55, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 55, 67: 57, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 67, 53, 54, 56, 55, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]

 10%|██████████                                                                                         | 286/2828 [00:42<04:10, 10.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 66, 62: 61, 63: 65, 64: 67, 65: 70, 66: 72, 67: 71, 68: 73, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 62, 60, 54, 55, 63, 61, 64, 69, 70, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 66, 62: 61, 63: 65, 64: 67, 65: 70, 66: 72, 67: 71, 68: 73, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 62, 60, 54, 55, 63, 61, 64, 69, 70, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 55, 52, 68, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 55, 52, 68, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 10%|██████████                                                                                         | 288/2828 [00:43<04:43,  8.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 10%|██████████                                                                                         | 289/2828 [00:43<08:06,  5.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 55, 52, 68, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 55, 52, 68, 56, 53, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 10%|██████████▎                                                                                        | 293/2828 [00:44<07:34,  5.58it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 9, 5: 11, 6: 13, 7: 10, 8: 12, 9: 14, 10: 16, 11: 15, 12: 17, 13: 5, 14: 8, 15: 3, 16: 6, 17: 18, 18: 19, 19: 20}
[0, 1, 15, 2, 13, 16, 3, 14, 4, 7, 5, 8, 6, 9, 11, 10, 12, 17, 18, 19]
[1, 18, 19]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 9, 5: 11, 6: 13, 7: 10, 8: 12, 9: 14, 10: 16, 11: 15, 12: 17, 13: 5, 14: 8, 15: 3, 16: 6, 17: 18, 18: 19, 19: 20}
[0, 1, 15, 2, 13, 16, 3, 14, 4, 7, 5, 8, 6, 9, 11, 10, 12, 17, 18, 19]
[1, 18, 19]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 57, 56: 55, 57: 61, 58: 63, 59: 62, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 56, 52, 55, 53, 54, 70, 57, 59, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 57, 56: 55, 57: 61, 58: 63, 59: 62, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 56, 52, 55, 53, 54, 70, 57, 59, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

 11%|██████████▍                                                                                        | 297/2828 [00:44<05:18,  7.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 59, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 68, 61: 72, 62: 69, 63: 73, 64: 58, 65: 57, 66: 60, 67: 63, 68: 67, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 52, 65, 64, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 62, 69, 70, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 59, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 68, 61: 72, 62: 69, 63: 73, 64: 58, 65: 57, 66: 60, 67: 63, 68: 67, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 53, 52, 65, 64, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 62, 69, 70, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 11%|██████████▍                                                                                        | 299/2828 [00:45<04:49,  8.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 71, 61: 73, 62: 72, 63: 74, 64: 59, 65: 62, 66: 56, 67: 58, 68: 61, 69: 65, 70: 66, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 71, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 71, 61: 73, 62: 72, 63: 74, 64: 59, 65: 62, 66: 56, 67: 58, 68: 61, 69: 65, 70: 66, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 71, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 57, 57: 59, 58: 55, 59: 58, 60: 63, 61: 67, 62: 69, 63: 64, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 69, 70, 60, 63, 54, 55, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 65, 55: 66, 56: 57, 57: 59, 58: 55, 59: 58, 60: 63, 61: 67, 62: 69, 63: 64, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 69, 70, 60, 63, 54, 55, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 11%|██████████▌                                                                                        | 303/2828 [00:45<04:06, 10.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 11%|██████████▋                                                                                        | 305/2828 [00:45<03:59, 10.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 11%|██████████▊                                                                                        | 309/2828 [00:45<03:38, 11.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 11%|██████████▉                                                                                        | 311/2828 [00:46<03:40, 11.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 59, 57: 61, 58: 64, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 62, 69: 65, 70: 60, 71: 63, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 53, 54, 55, 56, 70, 57, 68, 71, 58, 69, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 59, 57: 61, 58: 64, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 62, 69: 65, 70: 60, 71: 63, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 53, 54, 55, 56, 70, 57, 68, 71, 58, 69, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]

 11%|██████████▉                                                                                        | 313/2828 [00:46<03:39, 11.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 11%|███████████                                                                                        | 315/2828 [00:46<04:37,  9.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 71, 61: 73, 62: 72, 63: 74, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 69, 70: 70, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 64, 54, 67, 71, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 71, 61: 73, 62: 72, 63: 74, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 69, 70: 70, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 64, 54, 67, 71, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 11%|███████████▏                                                                                       | 319/2828 [00:46<04:10, 10.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 64, 55: 65, 56: 57, 57: 61, 58: 66, 59: 68, 60: 70, 61: 67, 62: 69, 63: 71, 64: 73, 65: 72, 66: 74, 67: 59, 68: 55, 69: 58, 70: 62, 71: 63, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 71, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 64, 55: 65, 56: 57, 57: 61, 58: 66, 59: 68, 60: 70, 61: 67, 62: 69, 63: 71, 64: 73, 65: 72, 66: 74, 67: 59, 68: 55, 69: 58, 70: 62, 71: 63, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 68, 52, 56, 69, 67, 53, 57, 70, 71, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 11%|███████████▏                                                                                       | 321/2828 [00:47<04:03, 10.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 11%|███████████▍                                                                                       | 325/2828 [00:47<04:31,  9.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 73, 68: 74, 69: 67, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 69, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 73, 68: 74, 69: 67, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 69, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 64, 57: 68, 58: 69, 59: 59, 60: 55, 61: 58, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 54, 52, 61, 59, 55, 53, 62, 65, 56, 63, 66, 64, 57, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 64, 57: 68, 58: 69, 59: 59, 60: 55, 61: 58, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 54, 52, 61, 59, 55, 53, 62, 65, 56, 63, 66, 64, 57, 58, 67, 69, 68, 70]
[1, 49, 50]

 12%|███████████▍                                                                                       | 327/2828 [00:47<04:18,  9.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 65, 56: 67, 57: 63, 58: 66, 59: 68, 60: 70, 61: 69, 62: 71, 63: 57, 64: 55, 65: 58, 66: 61, 67: 60, 68: 64, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 64, 52, 63, 65, 53, 67, 66, 54, 57, 68, 55, 58, 56, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 65, 56: 67, 57: 63, 58: 66, 59: 68, 60: 70, 61: 69, 62: 71, 63: 57, 64: 55, 65: 58, 66: 61, 67: 60, 68: 64, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 64, 52, 63, 65, 53, 67, 66, 54, 57, 68, 55, 58, 56, 59, 61, 60, 62]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|███████████▌                                                                                       | 329/2828 [00:48<07:05,  5.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 64, 58: 58, 59: 61, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 58, 60, 54, 59, 61, 55, 57, 62, 65, 56, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 70, 58: 72, 59: 71, 60: 73, 61: 67, 62: 69, 63: 64, 64: 68, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 63, 70, 56, 61, 64, 62, 57, 59, 58, 60]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 70, 58: 72, 59: 71, 60: 73, 61: 67, 62: 69, 63: 64, 64: 68, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 63, 70, 56, 61, 64, 62, 57, 59, 58, 60]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 12%|███████████▌                                                                                       | 331/2828 [00:48<06:04,  6.86it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 12%|███████████▋                                                                                       | 334/2828 [00:49<05:31,  7.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 66, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 12%|███████████▊                                                                                       | 336/2828 [00:49<04:30,  9.22it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 60, 58: 63, 59: 64, 60: 66, 61: 68, 62: 65, 63: 67, 64: 69, 65: 71, 66: 70, 67: 72, 68: 57, 69: 55, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 69, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 60, 58: 63, 59: 64, 60: 66, 61: 68, 62: 65, 63: 67, 64: 69, 65: 71, 66: 70, 67: 72, 68: 57, 69: 55, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 69, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|███████████▉                                                                                       | 340/2828 [00:49<06:01,  6.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 60, 58: 63, 59: 64, 60: 66, 61: 68, 62: 65, 63: 67, 64: 69, 65: 71, 66: 70, 67: 72, 68: 57, 69: 55, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 69, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 60, 58: 63, 59: 64, 60: 66, 61: 68, 62: 65, 63: 67, 64: 69, 65: 71, 66: 70, 67: 72, 68: 57, 69: 55, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 69, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 12%|████████████                                                                                       | 344/2828 [00:50<05:21,  7.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 71, 63: 74, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 72, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 71, 60, 62, 70, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 71, 63: 74, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 72, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 71, 60, 62, 70, 61, 63]
[1, 49, 50]

 12%|████████████                                                                                       | 346/2828 [00:50<04:50,  8.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 12%|████████████▎                                                                                      | 350/2828 [00:50<04:04, 10.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|████████████▎                                                                                      | 352/2828 [00:51<06:52,  6.00it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▍                                                                                      | 355/2828 [00:52<07:29,  5.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▌                                                                                      | 359/2828 [00:53<07:36,  5.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 58, 70, 56, 59, 57, 60, 63, 61, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 58, 70, 56, 59, 57, 60, 63, 61, 62, 64]
[1, 49, 50]

 13%|████████████▋                                                                                      | 361/2828 [00:53<06:24,  6.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 13%|████████████▋                                                                                      | 363/2828 [00:53<05:32,  7.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▊                                                                                      | 365/2828 [00:54<07:54,  5.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 13%|████████████▊                                                                                      | 367/2828 [00:54<07:18,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 58, 65: 61, 66: 55, 67: 57, 68: 60, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 58, 65: 61, 66: 55, 67: 57, 68: 60, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▉                                                                                      | 371/2828 [00:55<07:16,  5.63it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 13%|█████████████                                                                                      | 373/2828 [00:55<06:09,  6.64it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 60, 65: 56, 66: 58, 67: 59, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 60, 65: 56, 66: 58, 67: 59, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 13%|█████████████▏                                                                                     | 377/2828 [00:55<05:29,  7.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 60, 65: 56, 66: 58, 67: 59, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 60, 65: 56, 66: 58, 67: 59, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 59, 54, 58, 60, 55, 56, 61, 65, 62, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 59, 54, 58, 60, 55, 56, 61, 65, 62, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 13%|█████████████▎                                                                                     | 379/2828 [00:56<04:56,  8.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 68, 60: 70, 61: 67, 62: 69, 63: 71, 64: 73, 65: 72, 66: 74, 67: 63, 68: 65, 69: 60, 70: 62, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 68, 60: 70, 61: 67, 62: 69, 63: 71, 64: 73, 65: 72, 66: 74, 67: 63, 68: 65, 69: 60, 70: 62, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 67, 62: 69, 63: 66, 64: 61, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 64, 60, 54, 55, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 67, 62: 69, 63: 66, 64: 61, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 64, 60, 54, 55, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 14%|█████████████▍                                                                                     | 383/2828 [00:56<04:16,  9.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 62, 58: 58, 59: 61, 60: 64, 61: 67, 62: 69, 63: 65, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 66, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 62, 58: 58, 59: 61, 60: 64, 61: 67, 62: 69, 63: 65, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 66, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|█████████████▍                                                                                     | 385/2828 [00:57<06:57,  5.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 14%|█████████████▌                                                                                     | 388/2828 [00:57<06:09,  6.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 66, 58: 68, 59: 63, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 59, 69, 56, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 66, 58: 68, 59: 63, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 69, 71: 70, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 59, 69, 56, 57, 60, 58, 70, 71, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|█████████████▋                                                                                     | 392/2828 [00:58<06:54,  5.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 58, 54: 61, 55: 64, 56: 66, 57: 62, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 60, 65: 63, 66: 67, 67: 70, 68: 73, 69: 74, 70: 55, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 53, 71, 64, 54, 57, 65, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 58, 54: 61, 55: 64, 56: 66, 57: 62, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 60, 65: 63, 66: 67, 67: 70, 68: 73, 69: 74, 70: 55, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 53, 71, 64, 54, 57, 65, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 14%|█████████████▊                                                                                     | 395/2828 [00:58<05:45,  7.05it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 69, 63: 63, 64: 59, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 70, 66, 64, 53, 56, 67, 63, 54, 57, 55, 68, 69, 62, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 69, 63: 63, 64: 59, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 70, 66, 64, 53, 56, 67, 63, 54, 57, 55, 68, 69, 62, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 57, 57: 61, 58: 64, 59: 66, 60: 68, 61: 65, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 59, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 52, 56, 69, 67, 53, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 57, 57: 61, 58: 64, 59: 66, 60: 68, 61: 65, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 59, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 52, 56, 69, 67, 53, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 57, 57: 61, 58: 64, 59: 66, 60: 68, 61: 65, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 59, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 52, 56, 69, 67, 53, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 57, 57: 61, 58: 64, 59: 66, 60: 68, 61: 65, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 59, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 52, 56, 69, 67, 53, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 14%|█████████████▉                                                                                     | 399/2828 [00:59<04:33,  8.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 56, 67, 69, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 56, 67, 69, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 14%|██████████████                                                                                     | 401/2828 [00:59<04:03,  9.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 61, 58: 65, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 69, 65: 66, 66: 58, 67: 62, 68: 60, 69: 64, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 61, 58: 65, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 69, 65: 66, 66: 58, 67: 62, 68: 60, 69: 64, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|██████████████                                                                                     | 403/2828 [00:59<06:51,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

 14%|██████████████▏                                                                                    | 407/2828 [01:00<05:01,  8.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 60, 56: 63, 57: 59, 58: 64, 59: 61, 60: 58, 61: 62, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 57, 55, 59, 61, 56, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 60, 56: 63, 57: 59, 58: 64, 59: 61, 60: 58, 61: 62, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 57, 55, 59, 61, 56, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 60, 55: 62, 56: 64, 57: 65, 58: 67, 59: 69, 60: 66, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 57, 68: 55, 69: 61, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 67, 53, 66, 54, 69, 55, 70, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 60, 55: 62, 56: 64, 57: 65, 58: 67, 59: 69, 60: 66, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 57, 68: 55, 69: 61, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 67, 53, 66, 54, 69, 55, 70, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 14%|██████████████▎                                                                                    | 409/2828 [01:00<04:33,  8.85it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 59, 57: 55, 58: 58, 59: 61, 60: 65, 61: 67, 62: 62, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 57, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 52, 68, 58, 56, 53, 59, 62, 54, 55, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 59, 57: 55, 58: 58, 59: 61, 60: 65, 61: 67, 62: 62, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 57, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 52, 68, 58, 56, 53, 59, 62, 54, 55, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|██████████████▍                                                                                    | 411/2828 [01:01<07:09,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 61, 58: 64, 59: 67, 60: 69, 61: 65, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 58, 57: 61, 58: 64, 59: 67, 60: 69, 61: 65, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 15%|██████████████▍                                                                                    | 413/2828 [01:01<06:08,  6.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|██████████████▌                                                                                    | 416/2828 [01:01<06:46,  5.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]

 15%|██████████████▋                                                                                    | 418/2828 [01:02<05:45,  6.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 70, 59: 66, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 60, 55, 61, 56, 62, 65, 57, 59, 63, 66, 64, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 59, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 55, 53, 52, 56, 57, 54, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 55, 56: 58, 57: 59, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 55, 53, 52, 56, 57, 54, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|██████████████▋                                                                                    | 420/2828 [01:02<08:04,  4.97it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 15%|██████████████▊                                                                                    | 422/2828 [01:03<08:19,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

 15%|██████████████▊                                                                                    | 424/2828 [01:03<06:30,  6.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 60, 56: 61, 57: 63, 58: 65, 59: 62, 60: 64, 61: 66, 62: 68, 63: 67, 64: 69, 65: 55, 66: 57, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 52, 66, 53, 54, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 60, 56: 61, 57: 63, 58: 65, 59: 62, 60: 64, 61: 66, 62: 68, 63: 67, 64: 69, 65: 55, 66: 57, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 52, 66, 53, 54, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 61, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 58, 68: 62, 69: 60, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 61, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 58, 68: 62, 69: 60, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 15%|██████████████▉                                                                                    | 426/2828 [01:03<05:29,  7.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 15%|███████████████                                                                                    | 429/2828 [01:04<06:59,  5.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 66, 56: 67, 57: 58, 58: 55, 59: 57, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 58, 52, 59, 57, 53, 60, 63, 54, 61, 64, 62, 55, 56, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 66, 56: 67, 57: 58, 58: 55, 59: 57, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 58, 52, 59, 57, 53, 60, 63, 54, 61, 64, 62, 55, 56, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 58, 67: 61, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 58, 67: 61, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|███████████████▏                                                                                   | 433/2828 [01:05<07:03,  5.66it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 15%|███████████████▏                                                                                   | 435/2828 [01:05<05:55,  6.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 15%|███████████████▎                                                                                   | 438/2828 [01:05<05:31,  7.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 61, 67: 64, 68: 68, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 63, 61, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 61, 67: 64, 68: 68, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 63, 61, 62, 64]
[1, 49, 50]

 16%|███████████████▍                                                                                   | 440/2828 [01:05<04:53,  8.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 68, 58: 69, 59: 56, 60: 59, 61: 62, 62: 60, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 67, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 54, 60, 62, 55, 61, 63, 56, 70, 64, 69, 57, 58, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 68, 58: 69, 59: 56, 60: 59, 61: 62, 62: 60, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 67, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 54, 60, 62, 55, 61, 63, 56, 70, 64, 69, 57, 58, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 16%|███████████████▍                                                                                   | 442/2828 [01:06<07:18,  5.44it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 16%|███████████████▌                                                                                   | 446/2828 [01:07<07:15,  5.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 64, 56: 65, 57: 58, 58: 59, 59: 62, 60: 60, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 58, 60, 54, 59, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 64, 56: 65, 57: 58, 58: 59, 59: 62, 60: 60, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 58, 60, 54, 59, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 16%|███████████████▋                                                                                   | 449/2828 [01:07<06:16,  6.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 62, 58: 58, 59: 61, 60: 64, 61: 67, 62: 70, 63: 72, 64: 71, 65: 73, 66: 68, 67: 69, 68: 65, 69: 66, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 62, 58: 58, 59: 61, 60: 64, 61: 67, 62: 70, 63: 72, 64: 71, 65: 73, 66: 68, 67: 69, 68: 65, 69: 66, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]

 16%|███████████████▊                                                                                   | 453/2828 [01:07<04:18,  9.18it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 70, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 67, 59, 61, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 70, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 67, 59, 61, 68]
[1, 49, 50]

 16%|███████████████▉                                                                                   | 455/2828 [01:08<03:51, 10.25it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 58, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]

 16%|███████████████▉                                                                                   | 457/2828 [01:08<03:22, 11.71it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 16%|████████████████▏                                                                                  | 461/2828 [01:09<07:16,  5.42it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 62, 54: 65, 55: 67, 56: 63, 57: 66, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 61, 64: 60, 65: 55, 66: 59, 67: 64, 68: 68, 69: 69, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 70, 66, 64, 63, 53, 56, 67, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 62, 54: 65, 55: 67, 56: 63, 57: 66, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 61, 64: 60, 65: 55, 66: 59, 67: 64, 68: 68, 69: 69, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 70, 66, 64, 63, 53, 56, 67, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 16%|████████████████▏                                                                                  | 463/2828 [01:09<06:07,  6.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 17%|████████████████▎                                                                                  | 467/2828 [01:09<04:33,  8.64it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 64, 57: 68, 58: 69, 59: 60, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 55, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 52, 70, 53, 54, 59, 55, 60, 63, 56, 61, 64, 62, 57, 58, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 64, 57: 68, 58: 69, 59: 60, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 55, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 52, 70, 53, 54, 59, 55, 60, 63, 56, 61, 64, 62, 57, 58, 65, 67, 66, 68]
[1, 49, 50]

 17%|████████████████▍                                                                                  | 469/2828 [01:10<04:13,  9.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 17%|████████████████▌                                                                                  | 473/2828 [01:10<03:48, 10.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 59, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 59, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 17%|████████████████▋                                                                                  | 475/2828 [01:11<06:30,  6.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 64, 69: 59, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 17%|████████████████▋                                                                                  | 477/2828 [01:11<05:35,  7.00it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 17%|████████████████▊                                                                                  | 481/2828 [01:11<04:56,  7.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 17%|████████████████▉                                                                                  | 483/2828 [01:11<04:27,  8.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 17%|█████████████████                                                                                  | 487/2828 [01:12<03:43, 10.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 62, 57: 64, 58: 66, 59: 63, 60: 65, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 54, 67, 65, 53, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 62, 57: 64, 58: 66, 59: 63, 60: 65, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 54, 67, 65, 53, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 62, 57: 64, 58: 66, 59: 63, 60: 65, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 54, 67, 65, 53, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 62, 57: 64, 58: 66, 59: 63, 60: 65, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 52, 54, 67, 65, 53, 55, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]

 17%|█████████████████                                                                                  | 489/2828 [01:12<03:26, 11.31it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 42, 37: 44, 38: 43, 39: 45, 40: 32, 41: 35, 42: 38, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 40, 30, 44, 41, 31, 34, 42, 32, 35, 33, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 42, 37: 44, 38: 43, 39: 45, 40: 32, 41: 35, 42: 38, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 40, 30, 44, 41, 31, 34, 42, 32, 35, 33, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 17%|█████████████████▏                                                                                 | 491/2828 [01:12<04:07,  9.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 66, 59: 61, 60: 65, 61: 70, 62: 71, 63: 72, 64: 73, 65: 68, 66: 58, 67: 62, 68: 60, 69: 64, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 66, 59: 61, 60: 65, 61: 70, 62: 71, 63: 72, 64: 73, 65: 68, 66: 58, 67: 62, 68: 60, 69: 64, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 64, 59: 59, 60: 62, 61: 65, 62: 68, 63: 67, 64: 63, 65: 66, 66: 70, 67: 71, 68: 72, 69: 73, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 64, 59: 59, 60: 62, 61: 65, 62: 68, 63: 67, 64: 63, 65: 66, 66: 70, 67: 71, 68: 72, 69: 73, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69]
[1, 49, 50]

 18%|█████████████████▎                                                                                 | 495/2828 [01:13<03:45, 10.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 57, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 69, 54, 65, 70, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 57, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 69, 54, 65, 70, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 61, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 64, 69: 59, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 70, 56, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 61, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 64, 69: 59, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 70, 56, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 18%|█████████████████▍                                                                                 | 497/2828 [01:13<03:40, 10.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|█████████████████▍                                                                                 | 499/2828 [01:13<06:21,  6.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|█████████████████▌                                                                                 | 500/2828 [01:14<09:10,  4.23it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|█████████████████▌                                                                                 | 501/2828 [01:15<11:42,  3.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|█████████████████▋                                                                                 | 505/2828 [01:15<09:02,  4.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 63, 53, 56, 71, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 63, 53, 56, 71, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 18%|█████████████████▊                                                                                 | 509/2828 [01:16<05:41,  6.79it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 63, 53, 56, 71, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 63, 65: 67, 66: 70, 67: 73, 68: 74, 69: 55, 70: 58, 71: 62, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 69, 62, 52, 70, 63, 53, 56, 71, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 18%|█████████████████▉                                                                                 | 511/2828 [01:16<04:58,  7.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 18%|█████████████████▉                                                                                 | 513/2828 [01:16<05:10,  7.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 18%|██████████████████                                                                                 | 515/2828 [01:16<04:37,  8.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 18%|██████████████████                                                                                 | 516/2828 [01:17<05:13,  7.38it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|██████████████████▏                                                                                | 519/2828 [01:17<06:42,  5.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 64, 57: 68, 58: 69, 59: 60, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 55, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 52, 70, 53, 54, 59, 55, 60, 63, 56, 61, 64, 62, 57, 58, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 59, 55: 61, 56: 64, 57: 68, 58: 69, 59: 60, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 70, 66: 72, 67: 71, 68: 73, 69: 55, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 52, 70, 53, 54, 59, 55, 60, 63, 56, 61, 64, 62, 57, 58, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 18%|██████████████████▏                                                                                | 521/2828 [01:17<05:33,  6.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 64, 69: 59, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 62, 68: 64, 69: 59, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]

 19%|██████████████████▍                                                                                | 525/2828 [01:18<04:03,  9.48it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 65, 57: 70, 58: 71, 59: 56, 60: 59, 61: 62, 62: 66, 63: 64, 64: 60, 65: 63, 66: 68, 67: 69, 68: 72, 69: 73, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 54, 60, 64, 55, 61, 65, 63, 56, 62, 70, 66, 67, 57, 58, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 65, 57: 70, 58: 71, 59: 56, 60: 59, 61: 62, 62: 66, 63: 64, 64: 60, 65: 63, 66: 68, 67: 69, 68: 72, 69: 73, 70: 67, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 59, 53, 54, 60, 64, 55, 61, 65, 63, 56, 62, 70, 66, 67, 57, 58, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 19%|██████████████████▌                                                                                | 529/2828 [01:18<03:21, 11.39it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]

 19%|██████████████████▌                                                                                | 531/2828 [01:18<03:11, 11.97it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 19%|██████████████████▋                                                                                | 533/2828 [01:19<06:01,  6.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 66, 66: 70, 67: 67, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 67, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 19%|██████████████████▊                                                                                | 537/2828 [01:19<04:28,  8.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 59, 59: 62, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 58, 54, 56, 59, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 19%|██████████████████▉                                                                                | 541/2828 [01:19<03:25, 11.11it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 57, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 67, 54, 65, 68, 55, 66, 69, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 57, 68: 60, 69: 63, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 67, 54, 65, 68, 55, 66, 69, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]

 19%|███████████████████                                                                                | 543/2828 [01:20<03:24, 11.15it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 19%|███████████████████                                                                                | 545/2828 [01:20<04:16,  8.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 33, 45: 36, 46: 39, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 44, 34, 48, 45, 35, 38, 46, 36, 39, 37, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 33, 45: 36, 46: 39, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 44, 34, 48, 45, 35, 38, 46, 36, 39, 37, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 19%|███████████████████▏                                                                               | 549/2828 [01:20<03:32, 10.70it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 64, 55: 65, 56: 66, 57: 56, 58: 60, 59: 62, 60: 67, 61: 69, 62: 63, 63: 68, 64: 70, 65: 72, 66: 71, 67: 73, 68: 59, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 57, 52, 70, 68, 58, 53, 59, 62, 54, 55, 56, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 20%|███████████████████▎                                                                               | 553/2828 [01:21<05:18,  7.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 58, 65: 56, 66: 59, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 58, 65: 56, 66: 59, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 20%|███████████████████▍                                                                               | 557/2828 [01:22<04:54,  7.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 58, 65: 56, 66: 59, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 58, 65: 56, 66: 59, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 62, 55: 64, 56: 57, 57: 60, 58: 61, 59: 59, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 56, 53, 59, 57, 58, 54, 60, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 62, 55: 64, 56: 57, 57: 60, 58: 61, 59: 59, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 56, 53, 59, 57, 58, 54, 60, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]

 20%|███████████████████▌                                                                               | 559/2828 [01:22<04:25,  8.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 20%|███████████████████▋                                                                               | 563/2828 [01:22<03:51,  9.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]

 20%|███████████████████▊                                                                               | 565/2828 [01:22<03:41, 10.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 63, 58: 59, 59: 61, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 63, 58: 59, 59: 61, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 57, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 20%|███████████████████▊                                                                               | 567/2828 [01:22<03:34, 10.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 20%|███████████████████▉                                                                               | 569/2828 [01:24<08:54,  4.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 59, 55: 55, 56: 58, 57: 62, 58: 65, 59: 67, 60: 63, 61: 66, 62: 68, 63: 70, 64: 69, 65: 71, 66: 60, 67: 61, 68: 64, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 55, 53, 52, 56, 54, 66, 67, 57, 60, 68, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 59, 55: 55, 56: 58, 57: 62, 58: 65, 59: 67, 60: 63, 61: 66, 62: 68, 63: 70, 64: 69, 65: 71, 66: 60, 67: 61, 68: 64, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 55, 53, 52, 56, 54, 66, 67, 57, 60, 68, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 20%|████████████████████                                                                               | 573/2828 [01:24<07:43,  4.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 20%|████████████████████▏                                                                              | 576/2828 [01:25<06:22,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 57, 67: 60, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 57, 67: 60, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 59, 55: 55, 56: 58, 57: 60, 58: 62, 59: 64, 60: 61, 61: 63, 62: 65, 63: 67, 64: 66, 65: 68, 66: 51, 67: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 66, 67, 50, 51, 55, 53, 52, 56, 54, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 59, 55: 55, 56: 58, 57: 60, 58: 62, 59: 64, 60: 61, 61: 63, 62: 65, 63: 67, 64: 66, 65: 68, 66: 51, 67: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 66, 67, 50, 51, 55, 53, 52, 56, 54, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 20%|████████████████████▎                                                                              | 579/2828 [01:25<06:43,  5.58it/s]

{0: 1, 1: 2, 2: 4, 3: 7, 4: 9, 5: 11, 6: 13, 7: 10, 8: 12, 9: 14, 10: 16, 11: 15, 12: 17, 13: 5, 14: 8, 15: 3, 16: 6, 17: 18, 18: 19, 19: 20}
[0, 1, 15, 2, 13, 16, 3, 14, 4, 7, 5, 8, 6, 9, 11, 10, 12, 17, 18, 19]
[1, 18, 19]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 9, 5: 11, 6: 13, 7: 10, 8: 12, 9: 14, 10: 16, 11: 15, 12: 17, 13: 5, 14: 8, 15: 3, 16: 6, 17: 18, 18: 19, 19: 20}
[0, 1, 15, 2, 13, 16, 3, 14, 4, 7, 5, 8, 6, 9, 11, 10, 12, 17, 18, 19]
[1, 18, 19]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 61, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 71, 61: 73, 62: 72, 63: 74, 64: 60, 65: 55, 66: 58, 67: 62, 68: 65, 69: 69, 70: 70, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 71, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 61, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 71, 61: 73, 62: 72, 63: 74, 64: 60, 65: 55, 66: 58, 67: 62, 68: 65, 69: 69, 70: 70, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 65, 53, 52, 66, 71, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 21%|████████████████████▍                                                                              | 583/2828 [01:26<06:41,  5.60it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 57, 58: 55, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 57, 53, 55, 59, 54, 56, 60, 70, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 59, 56: 62, 57: 57, 58: 55, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 57, 53, 55, 59, 54, 56, 60, 70, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 72, 64: 69, 65: 71, 66: 59, 67: 61, 68: 56, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 68, 53, 69, 66, 54, 67, 55, 59, 56, 60, 58, 57, 61, 64, 62, 65, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 72, 64: 69, 65: 71, 66: 59, 67: 61, 68: 56, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 68, 53, 69, 66, 54, 67, 55, 59, 56, 60, 58, 57, 61, 64, 62, 65, 63]
[1, 49, 50]

 21%|████████████████████▍                                                                              | 585/2828 [01:26<05:25,  6.88it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 58, 67: 57, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 58, 67: 57, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 67, 66, 53, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 21%|████████████████████▌                                                                              | 587/2828 [01:27<07:34,  4.93it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 21%|████████████████████▋                                                                              | 590/2828 [01:28<07:20,  5.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 57, 67: 60, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 56, 66: 57, 67: 60, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 21%|████████████████████▋                                                                              | 592/2828 [01:28<05:52,  6.35it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 69, 59: 71, 60: 70, 61: 72, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 69, 59: 71, 60: 70, 61: 72, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 21%|████████████████████▊                                                                              | 596/2828 [01:28<04:28,  8.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 69, 59: 71, 60: 70, 61: 72, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 69, 59: 71, 60: 70, 61: 72, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 61, 57: 58, 58: 62, 59: 63, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 61, 57: 58, 58: 62, 59: 63, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

 21%|████████████████████▉                                                                              | 598/2828 [01:28<03:58,  9.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 21%|█████████████████████                                                                              | 602/2828 [01:29<03:16, 11.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 21%|█████████████████████▏                                                                             | 604/2828 [01:29<03:07, 11.87it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 62, 57: 59, 58: 55, 59: 58, 60: 57, 61: 61, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 60, 59, 57, 53, 61, 56, 54, 55, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 21%|█████████████████████▎                                                                             | 608/2828 [01:29<03:00, 12.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 66, 59: 67, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 55, 60, 54, 56, 61, 57, 62, 65, 58, 59, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 66, 59: 67, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 55, 60, 54, 56, 61, 57, 62, 65, 58, 59, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 22%|█████████████████████▎                                                                             | 610/2828 [01:29<03:07, 11.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 66, 59: 67, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 55, 60, 54, 56, 61, 57, 62, 65, 58, 59, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 63, 58: 66, 59: 67, 60: 59, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 55, 60, 54, 56, 61, 57, 62, 65, 58, 59, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 63, 68: 59, 69: 62, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 70, 69, 67, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 63, 68: 59, 69: 62, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 70, 69, 67, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 22%|█████████████████████▍                                                                             | 614/2828 [01:30<03:04, 12.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 22%|█████████████████████▌                                                                             | 616/2828 [01:30<03:07, 11.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]

 22%|█████████████████████▋                                                                             | 620/2828 [01:30<03:09, 11.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 62, 52, 69, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 22%|█████████████████████▊                                                                             | 622/2828 [01:30<03:10, 11.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 59, 57: 55, 58: 58, 59: 61, 60: 64, 61: 67, 62: 66, 63: 62, 64: 65, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 53, 52, 58, 56, 54, 59, 63, 55, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 59, 57: 55, 58: 58, 59: 61, 60: 64, 61: 67, 62: 66, 63: 62, 64: 65, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 53, 52, 58, 56, 54, 59, 63, 55, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 22%|█████████████████████▉                                                                             | 626/2828 [01:31<03:41,  9.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 55, 52: 54, 53: 58, 54: 61, 55: 64, 56: 66, 57: 62, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 57, 64: 60, 65: 63, 66: 67, 67: 70, 68: 73, 69: 74, 70: 56, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 52, 51, 70, 63, 53, 71, 64, 54, 57, 65, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 55, 52: 54, 53: 58, 54: 61, 55: 64, 56: 66, 57: 62, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 57, 64: 60, 65: 63, 66: 67, 67: 70, 68: 73, 69: 74, 70: 56, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 52, 51, 70, 63, 53, 71, 64, 54, 57, 65, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 22%|█████████████████████▉                                                                             | 628/2828 [01:31<04:23,  8.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 63, 67: 56, 68: 58, 69: 62, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 55, 69, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 64, 57: 67, 58: 69, 59: 65, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 63, 67: 56, 68: 58, 69: 62, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 55, 69, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 58, 55: 61, 56: 63, 57: 66, 58: 67, 59: 60, 60: 62, 61: 64, 62: 68, 63: 70, 64: 65, 65: 69, 66: 71, 67: 73, 68: 72, 69: 74, 70: 57, 71: 55, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 71, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 58, 55: 61, 56: 63, 57: 66, 58: 67, 59: 60, 60: 62, 61: 64, 62: 68, 63: 70, 64: 65, 65: 69, 66: 71, 67: 73, 68: 72, 69: 74, 70: 57, 71: 55, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 71, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

 22%|██████████████████████                                                                             | 632/2828 [01:32<03:36, 10.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 22%|██████████████████████▏                                                                            | 634/2828 [01:32<06:07,  5.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▎                                                                            | 637/2828 [01:33<06:39,  5.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 59, 57: 55, 58: 58, 59: 61, 60: 64, 61: 67, 62: 66, 63: 62, 64: 65, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 53, 52, 58, 56, 54, 59, 63, 55, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 59, 57: 55, 58: 58, 59: 61, 60: 64, 61: 67, 62: 66, 63: 62, 64: 65, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 53, 52, 58, 56, 54, 59, 63, 55, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 23%|██████████████████████▍                                                                            | 641/2828 [01:33<04:29,  8.12it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 65, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 69, 56, 59, 57, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 65, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 69, 56, 59, 57, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 23%|██████████████████████▌                                                                            | 643/2828 [01:33<04:04,  8.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 69, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 56, 59, 57, 69, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 69, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 56, 59, 57, 69, 60, 62, 61, 63]
[1, 49, 50]

 23%|██████████████████████▌                                                                            | 645/2828 [01:34<03:48,  9.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 60, 56: 64, 57: 67, 58: 63, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 66, 65: 69, 66: 71, 67: 73, 68: 72, 69: 74, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 59, 55, 54, 60, 58, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 60, 56: 64, 57: 67, 58: 63, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 66, 65: 69, 66: 71, 67: 73, 68: 72, 69: 74, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 59, 55, 54, 60, 58, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▋                                                                            | 647/2828 [01:34<06:17,  5.77it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▋                                                                            | 649/2828 [01:35<07:47,  4.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▊                                                                            | 652/2828 [01:36<07:36,  4.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 59, 69: 62, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 67, 66: 70, 67: 73, 68: 74, 69: 63, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 69, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 68, 59: 71, 60: 69, 61: 72, 62: 56, 63: 59, 64: 62, 65: 67, 66: 70, 67: 73, 68: 74, 69: 63, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 69, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 23%|██████████████████████▉                                                                            | 656/2828 [01:36<04:51,  7.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 61, 60: 62, 61: 64, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 23%|███████████████████████                                                                            | 658/2828 [01:36<04:20,  8.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 61, 60: 62, 61: 64, 62: 65, 63: 67, 64: 69, 65: 66, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 23%|███████████████████████                                                                            | 660/2828 [01:36<03:59,  9.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 71, 63: 74, 64: 59, 65: 61, 66: 64, 67: 68, 68: 69, 69: 72, 70: 56, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 70, 53, 71, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 69, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 71, 63: 74, 64: 59, 65: 61, 66: 64, 67: 68, 68: 69, 69: 72, 70: 56, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 70, 53, 71, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 69, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 61, 57: 60, 58: 63, 59: 62, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 70, 57, 56, 59, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 61, 57: 60, 58: 63, 59: 62, 60: 64, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 70, 57, 56, 59, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]

 23%|███████████████████████▏                                                                           | 664/2828 [01:37<03:37,  9.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 60, 57: 64, 58: 67, 59: 63, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 60, 56, 55, 61, 59, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 60, 57: 64, 58: 67, 59: 63, 60: 59, 61: 62, 62: 65, 63: 68, 64: 70, 65: 66, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 54, 60, 56, 55, 61, 59, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 61, 65: 57, 66: 59, 67: 60, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 61, 65: 57, 66: 59, 67: 60, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 66, 67, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▎                                                                           | 666/2828 [01:37<06:05,  5.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▎                                                                           | 667/2828 [01:38<08:38,  4.17it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▍                                                                           | 670/2828 [01:38<08:09,  4.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 59, 59: 62, 60: 64, 61: 67, 62: 69, 63: 66, 64: 63, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 59, 59: 62, 60: 64, 61: 67, 62: 69, 63: 66, 64: 63, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 24%|███████████████████████▌                                                                           | 672/2828 [01:39<06:14,  5.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 64, 56: 66, 57: 61, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 67, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 64, 56: 66, 57: 61, 58: 65, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 67, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 55, 58, 56, 66, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 24%|███████████████████████▋                                                                           | 676/2828 [01:39<04:12,  8.52it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 64, 56: 65, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 59, 54, 58, 60, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 64, 56: 65, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 53, 57, 59, 54, 58, 60, 61, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 24%|███████████████████████▋                                                                           | 678/2828 [01:39<03:43,  9.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 57, 66: 60, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 57, 66: 60, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▊                                                                           | 680/2828 [01:40<06:09,  5.81it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 62, 67: 65, 68: 69, 69: 70, 70: 57, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 53, 52, 70, 54, 71, 65, 55, 66, 56, 59, 67, 57, 60, 58, 68, 69, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 71, 62: 73, 63: 72, 64: 74, 65: 60, 66: 62, 67: 65, 68: 69, 69: 70, 70: 57, 71: 59, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 53, 52, 70, 54, 71, 65, 55, 66, 56, 59, 67, 57, 60, 58, 68, 69, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▉                                                                           | 684/2828 [01:41<06:15,  5.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 70, 63: 72, 64: 59, 65: 55, 66: 58, 67: 61, 68: 65, 69: 62, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 65, 53, 52, 66, 64, 54, 67, 69, 55, 58, 68, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▉                                                                           | 685/2828 [01:41<08:44,  4.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 24%|████████████████████████                                                                           | 686/2828 [01:41<08:44,  4.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|████████████████████████                                                                           | 688/2828 [01:42<09:46,  3.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 57, 54: 60, 55: 62, 56: 65, 57: 66, 58: 55, 59: 58, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 53, 59, 60, 54, 61, 55, 62, 65, 56, 57, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 57, 54: 60, 55: 62, 56: 65, 57: 66, 58: 55, 59: 58, 60: 59, 61: 61, 62: 63, 63: 67, 64: 69, 65: 64, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 53, 59, 60, 54, 61, 55, 62, 65, 56, 57, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|████████████████████████▏                                                                          | 690/2828 [01:43<10:24,  3.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 25%|████████████████████████▎                                                                          | 694/2828 [01:43<07:02,  5.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]

 25%|████████████████████████▎                                                                          | 696/2828 [01:43<05:39,  6.27it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 38, 38: 40, 39: 42, 40: 39, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46, 46: 36, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 47, 30: 48, 31: 49, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 38, 38: 40, 39: 42, 40: 39, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46, 46: 36, 47: 32, 48: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]

 25%|████████████████████████▌                                                                          | 700/2828 [01:44<04:11,  8.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 70, 59: 72, 60: 71, 61: 73, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 67, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 69, 70, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 25%|████████████████████████▌                                                                          | 702/2828 [01:44<03:42,  9.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 25%|████████████████████████▋                                                                          | 706/2828 [01:44<03:14, 10.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 25%|████████████████████████▊                                                                          | 708/2828 [01:44<03:12, 11.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 25%|████████████████████████▊                                                                          | 710/2828 [01:44<03:10, 11.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 25%|████████████████████████▉                                                                          | 712/2828 [01:45<05:40,  6.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 57, 55, 58, 56, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 57, 55, 58, 56, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 57, 55, 58, 56, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 57, 55, 58, 56, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]

 25%|█████████████████████████                                                                          | 716/2828 [01:45<03:55,  8.96it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 59, 59: 61, 60: 63, 61: 66, 62: 68, 63: 64, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 54, 53, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 25%|█████████████████████████▏                                                                         | 720/2828 [01:46<03:24, 10.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 58, 57: 62, 58: 59, 59: 63, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 55, 57, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 61, 56: 58, 57: 62, 58: 59, 59: 63, 60: 64, 61: 66, 62: 68, 63: 65, 64: 67, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 56, 58, 54, 55, 57, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 59, 55: 61, 56: 62, 57: 58, 58: 57, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 53, 52, 58, 57, 54, 59, 55, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 59, 55: 61, 56: 62, 57: 58, 58: 57, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 53, 52, 58, 57, 54, 59, 55, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 26%|█████████████████████████▎                                                                         | 724/2828 [01:47<06:37,  5.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 54, 52, 68, 56, 55, 53, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 54, 52, 68, 56, 55, 53, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]

 26%|█████████████████████████▍                                                                         | 726/2828 [01:47<05:25,  6.46it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 57, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 69, 54, 65, 70, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 58, 55: 61, 56: 63, 57: 66, 58: 68, 59: 64, 60: 67, 61: 70, 62: 72, 63: 71, 64: 73, 65: 59, 66: 62, 67: 65, 68: 69, 69: 57, 70: 60, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 69, 54, 65, 70, 55, 66, 56, 59, 67, 57, 60, 58, 68, 61, 63, 62, 64]
[1, 49, 50]

 26%|█████████████████████████▌                                                                         | 730/2828 [01:47<04:07,  8.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 62, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 70, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 62, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 59, 68: 55, 69: 58, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 68, 52, 56, 69, 67, 53, 70, 57, 54, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 26%|█████████████████████████▋                                                                         | 732/2828 [01:48<04:25,  7.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 26%|█████████████████████████▊                                                                         | 736/2828 [01:48<03:38,  9.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 72, 60: 69, 61: 73, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 69, 70, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 72, 60: 69, 61: 73, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 69, 70, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 72, 60: 69, 61: 73, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 69, 70, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 68, 59: 72, 60: 69, 61: 73, 62: 55, 63: 58, 64: 62, 65: 67, 66: 57, 67: 61, 68: 66, 69: 70, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 68, 65, 58, 60, 69, 70, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 26%|█████████████████████████▊                                                                         | 738/2828 [01:48<03:29,  9.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 63, 57: 66, 58: 67, 59: 59, 60: 61, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 59, 55, 60, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 63, 57: 66, 58: 67, 59: 59, 60: 61, 61: 62, 62: 64, 63: 68, 64: 70, 65: 65, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 54, 53, 59, 55, 60, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 26%|█████████████████████████▉                                                                         | 742/2828 [01:49<04:47,  7.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 56, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 57, 58, 54, 70, 59, 55, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 59, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 56, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 57, 58, 54, 70, 59, 55, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 26%|██████████████████████████                                                                         | 745/2828 [01:49<04:30,  7.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 59, 60: 61, 61: 63, 62: 67, 63: 69, 64: 64, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 54, 53, 59, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 67, 56: 65, 57: 61, 58: 64, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 58, 56, 66, 55, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 67, 56: 65, 57: 61, 58: 64, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 58, 56, 66, 55, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]

 26%|██████████████████████████▏                                                                        | 749/2828 [01:50<03:28,  9.95it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 67, 56: 65, 57: 61, 58: 64, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 58, 56, 66, 55, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 67, 56: 65, 57: 61, 58: 64, 59: 68, 60: 71, 61: 69, 62: 72, 63: 56, 64: 59, 65: 62, 66: 66, 67: 70, 68: 73, 69: 74, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 63, 52, 71, 64, 53, 57, 65, 54, 58, 56, 66, 55, 59, 61, 67, 60, 62, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 27%|██████████████████████████▎                                                                        | 751/2828 [01:50<03:10, 10.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 57, 54, 56, 58, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 57, 54, 56, 58, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 57, 54, 56, 58, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 68, 62: 67, 63: 64, 64: 66, 65: 69, 66: 71, 67: 70, 68: 72, 69: 56, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 52, 69, 53, 55, 57, 54, 56, 58, 59, 63, 60, 64, 62, 61, 65, 67, 66, 68]
[1, 49, 50]

 27%|██████████████████████████▍                                                                        | 755/2828 [01:50<02:41, 12.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 65, 60: 69, 61: 70, 62: 68, 63: 64, 64: 60, 65: 63, 66: 67, 67: 66, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 64, 58, 55, 65, 63, 59, 67, 66, 62, 60, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 65, 60: 69, 61: 70, 62: 68, 63: 64, 64: 60, 65: 63, 66: 67, 67: 66, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 64, 58, 55, 65, 63, 59, 67, 66, 62, 60, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 27%|██████████████████████████▌                                                                        | 759/2828 [01:51<03:25, 10.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 64, 57: 58, 58: 61, 59: 59, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 57, 59, 54, 58, 60, 55, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]

 27%|██████████████████████████▋                                                                        | 761/2828 [01:51<03:20, 10.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 55, 66: 57, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 66, 64, 53, 67, 54, 68, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 55, 66: 57, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 66, 64, 53, 67, 54, 68, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 57, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 57, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61]
[1, 49, 50]

 27%|██████████████████████████▊                                                                        | 765/2828 [01:51<03:00, 11.43it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 57, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 57, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 62, 52, 67, 63, 53, 56, 68, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▊                                                                        | 767/2828 [01:52<05:29,  6.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 68, 61: 67, 62: 64, 63: 66, 64: 69, 65: 71, 66: 70, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 55, 52, 69, 56, 53, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 68, 61: 67, 62: 64, 63: 66, 64: 69, 65: 71, 66: 70, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 55, 52, 69, 56, 53, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▉                                                                        | 771/2828 [01:53<05:51,  5.85it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 55, 55: 58, 56: 61, 57: 63, 58: 64, 59: 60, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 54, 52, 70, 55, 53, 59, 56, 60, 57, 58, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 55, 55: 58, 56: 61, 57: 63, 58: 64, 59: 60, 60: 62, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 57, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 54, 52, 70, 55, 53, 59, 56, 60, 57, 58, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 27%|███████████████████████████                                                                        | 773/2828 [01:53<04:42,  7.28it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|███████████████████████████▏                                                                       | 775/2828 [01:54<09:05,  3.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|███████████████████████████▏                                                                       | 777/2828 [01:54<09:32,  3.58it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▎                                                                       | 781/2828 [01:55<07:39,  4.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 68, 61: 67, 62: 64, 63: 66, 64: 69, 65: 71, 66: 70, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 55, 52, 69, 56, 53, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 61, 55: 56, 56: 59, 57: 62, 58: 63, 59: 65, 60: 68, 61: 67, 62: 64, 63: 66, 64: 69, 65: 71, 66: 70, 67: 72, 68: 55, 69: 58, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 68, 55, 52, 69, 56, 53, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▍                                                                       | 783/2828 [01:56<08:42,  3.91it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▍                                                                       | 785/2828 [01:56<09:16,  3.67it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▌                                                                       | 787/2828 [01:57<09:39,  3.52it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▌                                                                       | 788/2828 [01:58<11:23,  2.98it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▊                                                                       | 793/2828 [01:58<07:24,  4.58it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 28%|███████████████████████████▊                                                                       | 795/2828 [01:59<05:47,  5.84it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▉                                                                       | 799/2828 [01:59<06:00,  5.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 66, 59: 61, 60: 59, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 63, 58: 66, 59: 61, 60: 59, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|████████████████████████████                                                                       | 801/2828 [02:00<07:31,  4.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 55, 65: 59, 66: 57, 67: 58, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 64, 52, 66, 67, 65, 53, 68, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 55, 65: 59, 66: 57, 67: 58, 68: 61, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 64, 52, 66, 67, 65, 53, 68, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|████████████████████████████▏                                                                      | 805/2828 [02:01<06:52,  4.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]

 29%|████████████████████████████▎                                                                      | 807/2828 [02:01<05:24,  6.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 65, 60: 69, 61: 70, 62: 68, 63: 64, 64: 60, 65: 63, 66: 67, 67: 66, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 64, 58, 55, 65, 63, 59, 67, 66, 62, 60, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 65, 60: 69, 61: 70, 62: 68, 63: 64, 64: 60, 65: 63, 66: 67, 67: 66, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 64, 58, 55, 65, 63, 59, 67, 66, 62, 60, 61]
[1, 49, 50]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 65, 56: 57, 57: 60, 58: 64, 59: 67, 60: 63, 61: 58, 62: 62, 63: 66, 64: 69, 65: 70, 66: 71, 67: 68, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 56, 61, 53, 57, 54, 62, 60, 58, 55, 63, 59, 67, 64, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 65, 56: 57, 57: 60, 58: 64, 59: 67, 60: 63, 61: 58, 62: 62, 63: 66, 64: 69, 65: 70, 66: 71, 67: 68, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 56, 61, 53, 57, 54, 62, 60, 58, 55, 63, 59, 67, 64, 65, 66]
[1, 49, 50]

 29%|████████████████████████████▎                                                                      | 809/2828 [02:01<04:23,  7.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▍                                                                      | 813/2828 [02:02<05:01,  6.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 66, 58: 60, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 58, 59, 61, 56, 62, 65, 57, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 66, 58: 60, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 58, 59, 61, 56, 62, 65, 57, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 29%|████████████████████████████▌                                                                      | 815/2828 [02:02<04:14,  7.91it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 112, 106: 113, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 102, 107, 101, 103, 108, 104, 109, 112, 105, 106, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 112, 106: 113, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 102, 107, 101, 103, 108, 104, 109, 112, 105, 106, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▌                                                                      | 817/2828 [02:03<06:11,  5.42it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 112, 106: 113, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 102, 107, 101, 103, 108, 104, 109, 112, 105, 106, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 112, 106: 113, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 102, 107, 101, 103, 108, 104, 109, 112, 105, 106, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▋                                                                      | 820/2828 [02:04<07:25,  4.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▋                                                                      | 821/2828 [02:04<09:49,  3.41it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▊                                                                      | 824/2828 [02:05<08:19,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 29%|████████████████████████████▉                                                                      | 826/2828 [02:05<06:22,  5.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 29%|█████████████████████████████                                                                      | 830/2828 [02:05<04:16,  7.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]

 29%|█████████████████████████████▏                                                                     | 834/2828 [02:06<03:02, 10.90it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▎                                                                     | 836/2828 [02:07<07:53,  4.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 30%|█████████████████████████████▎                                                                     | 838/2828 [02:07<06:59,  4.75it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 30%|█████████████████████████████▍                                                                     | 841/2828 [02:07<05:32,  5.98it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▌                                                                     | 844/2828 [02:08<05:56,  5.57it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▌                                                                     | 846/2828 [02:09<10:19,  3.20it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▋                                                                     | 849/2828 [02:10<08:45,  3.77it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▊                                                                     | 850/2828 [02:11<10:47,  3.06it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 30%|█████████████████████████████▊                                                                     | 851/2828 [02:11<10:15,  3.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▊                                                                     | 853/2828 [02:11<10:26,  3.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▉                                                                     | 854/2828 [02:12<12:12,  2.69it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▉                                                                     | 855/2828 [02:13<13:52,  2.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|██████████████████████████████                                                                     | 859/2828 [02:13<08:44,  3.75it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 30%|██████████████████████████████                                                                     | 860/2828 [02:14<08:34,  3.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 107, 114: 110, 115: 114, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 105, 114, 103, 106, 104, 115, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 107, 114: 110, 115: 114, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 105, 114, 103, 106, 104, 115, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 31%|██████████████████████████████▏                                                                    | 863/2828 [02:14<07:21,  4.45it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]

 31%|██████████████████████████████▎                                                                    | 867/2828 [02:15<04:11,  7.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 31%|██████████████████████████████▍                                                                    | 869/2828 [02:15<06:09,  5.30it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 31%|██████████████████████████████▍                                                                    | 871/2828 [02:16<07:30,  4.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|██████████████████████████████▋                                                                    | 875/2828 [02:16<05:11,  6.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|██████████████████████████████▊                                                                    | 879/2828 [02:17<04:14,  7.65it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 31%|██████████████████████████████▊                                                                    | 881/2828 [02:17<04:37,  7.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 31%|██████████████████████████████▉                                                                    | 885/2828 [02:17<03:07, 10.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|███████████████████████████████                                                                    | 889/2828 [02:18<03:11, 10.14it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 32%|███████████████████████████████▎                                                                   | 893/2828 [02:18<02:47, 11.56it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 32%|███████████████████████████████▎                                                                   | 895/2828 [02:18<02:30, 12.82it/s]

{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▍                                                                   | 897/2828 [02:19<04:32,  7.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▍                                                                   | 899/2828 [02:19<07:00,  4.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 32%|███████████████████████████████▌                                                                   | 900/2828 [02:20<07:12,  4.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▌                                                                   | 902/2828 [02:20<08:17,  3.87it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▌                                                                   | 903/2828 [02:21<10:11,  3.15it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▊                                                                   | 907/2828 [02:22<07:21,  4.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▊                                                                   | 908/2828 [02:22<09:25,  3.39it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▉                                                                   | 911/2828 [02:23<07:52,  4.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 32%|████████████████████████████████                                                                   | 915/2828 [02:23<04:39,  6.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 109, 105: 105, 106: 107, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 109, 105: 105, 106: 107, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|████████████████████████████████▏                                                                  | 919/2828 [02:24<05:08,  6.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|████████████████████████████████▏                                                                  | 921/2828 [02:24<05:03,  6.28it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|████████████████████████████████▎                                                                  | 922/2828 [02:25<05:32,  5.74it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▎                                                                  | 924/2828 [02:25<07:00,  4.52it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▍                                                                  | 925/2828 [02:26<09:21,  3.39it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▍                                                                  | 927/2828 [02:26<09:37,  3.29it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|████████████████████████████████▍                                                                  | 928/2828 [02:27<09:13,  3.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▌                                                                  | 931/2828 [02:27<07:42,  4.10it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 33%|████████████████████████████████▋                                                                  | 933/2828 [02:28<05:45,  5.48it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 33%|████████████████████████████████▊                                                                  | 937/2828 [02:28<03:55,  8.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 33%|████████████████████████████████▉                                                                  | 941/2828 [02:28<02:48, 11.19it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 33%|█████████████████████████████████                                                                  | 943/2828 [02:28<02:39, 11.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|█████████████████████████████████                                                                  | 945/2828 [02:29<05:49,  5.39it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|█████████████████████████████████▏                                                                 | 947/2828 [02:30<07:01,  4.46it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|█████████████████████████████████▎                                                                 | 950/2828 [02:30<06:31,  4.79it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 34%|█████████████████████████████████▍                                                                 | 954/2828 [02:31<04:04,  7.66it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 34%|█████████████████████████████████▌                                                                 | 958/2828 [02:31<02:52, 10.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]

 34%|█████████████████████████████████▋                                                                 | 962/2828 [02:31<02:29, 12.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|█████████████████████████████████▋                                                                 | 964/2828 [02:32<04:56,  6.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 107, 105: 110, 106: 113, 107: 108, 108: 105, 109: 109, 110: 111, 111: 114, 112: 116, 113: 112, 114: 115, 115: 117, 116: 119, 117: 118, 118: 120, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 108, 103, 104, 107, 109, 105, 110, 113, 106, 111, 114, 112, 115, 117, 116, 118]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 107, 105: 110, 106: 113, 107: 108, 108: 105, 109: 109, 110: 111, 111: 114, 112: 116, 113: 112, 114: 115, 115: 117, 116: 119, 117: 118, 118: 120, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 108, 103, 104, 107, 109, 105, 110, 113, 106, 111, 114, 112, 115, 117, 116, 118]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|█████████████████████████████████▉                                                                 | 968/2828 [02:33<06:46,  4.57it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 34%|█████████████████████████████████▉                                                                 | 970/2828 [02:33<05:17,  5.86it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 34%|██████████████████████████████████                                                                 | 972/2828 [02:34<05:12,  5.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|██████████████████████████████████                                                                 | 974/2828 [02:34<07:13,  4.27it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 35%|██████████████████████████████████▏                                                                | 978/2828 [02:35<04:26,  6.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 35%|██████████████████████████████████▎                                                                | 980/2828 [02:35<03:39,  8.42it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 35%|██████████████████████████████████▍                                                                | 984/2828 [02:36<04:59,  6.16it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]

 35%|██████████████████████████████████▌                                                                | 988/2828 [02:36<03:26,  8.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▋                                                                | 992/2828 [02:37<05:58,  5.13it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▊                                                                | 994/2828 [02:38<07:02,  4.34it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 35%|██████████████████████████████████▊                                                                | 996/2828 [02:38<05:35,  5.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 35%|██████████████████████████████████▉                                                                | 998/2828 [02:38<05:25,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 35%|██████████████████████████████████▋                                                               | 1000/2828 [02:38<04:34,  6.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▋                                                               | 1002/2828 [02:39<06:15,  4.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 56, 68: 59, 69: 61}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 66, 68, 56, 69, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 56, 68: 59, 69: 61}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 66, 68, 56, 69, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]

 36%|██████████████████████████████████▊                                                               | 1004/2828 [02:39<05:42,  5.33it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 109, 104: 112, 105: 113, 106: 107, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 106, 108, 103, 109, 112, 104, 105, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 109, 104: 112, 105: 113, 106: 107, 107: 105, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 106, 108, 103, 109, 112, 104, 105, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|██████████████████████████████████▉                                                               | 1007/2828 [02:40<05:50,  5.20it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]

 36%|███████████████████████████████████                                                               | 1011/2828 [02:40<03:48,  7.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]

 36%|███████████████████████████████████                                                               | 1013/2828 [02:40<03:11,  9.49it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▏                                                              | 1015/2828 [02:41<05:57,  5.07it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▎                                                              | 1019/2828 [02:42<06:00,  5.01it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 36%|███████████████████████████████████▍                                                              | 1023/2828 [02:42<03:51,  7.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 36%|███████████████████████████████████▌                                                              | 1027/2828 [02:43<02:49, 10.64it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1029/2828 [02:43<04:46,  6.28it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1031/2828 [02:44<06:12,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▊                                                              | 1032/2828 [02:45<08:13,  3.64it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▊                                                              | 1035/2828 [02:45<07:08,  4.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]

 37%|███████████████████████████████████▉                                                              | 1037/2828 [02:45<05:18,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 37%|████████████████████████████████████                                                              | 1041/2828 [02:46<04:05,  7.28it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 37%|████████████████████████████████████▏                                                             | 1045/2828 [02:46<02:58, 10.01it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]

 37%|████████████████████████████████████▎                                                             | 1047/2828 [02:46<02:35, 11.48it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▎                                                             | 1049/2828 [02:47<04:39,  6.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 110, 103: 111, 104: 104, 105: 107, 106: 108, 107: 105, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 107, 101, 105, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 110, 103: 111, 104: 104, 105: 107, 106: 108, 107: 105, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 107, 101, 105, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▍                                                             | 1051/2828 [02:48<08:29,  3.49it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▌                                                             | 1054/2828 [02:49<07:22,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▌                                                             | 1056/2828 [02:49<08:03,  3.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▋                                                             | 1058/2828 [02:50<08:26,  3.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|████████████████████████████████████▊                                                             | 1062/2828 [02:51<06:33,  4.48it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]

 38%|████████████████████████████████████▉                                                             | 1066/2828 [02:51<04:03,  7.23it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]

 38%|█████████████████████████████████████                                                             | 1070/2828 [02:51<02:58,  9.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]

 38%|█████████████████████████████████████▏                                                            | 1072/2828 [02:51<02:51, 10.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 110, 103: 111, 104: 103, 105: 106, 106: 109, 107: 105, 108: 108, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 104, 100, 107, 105, 101, 108, 106, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 110, 103: 111, 104: 103, 105: 106, 106: 109, 107: 105, 108: 108, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 104, 100, 107, 105, 101, 108, 106, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▏                                                            | 1074/2828 [02:52<04:49,  6.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 110, 103: 111, 104: 103, 105: 106, 106: 109, 107: 105, 108: 108, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 104, 100, 107, 105, 101, 108, 106, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 110, 103: 111, 104: 103, 105: 106, 106: 109, 107: 105, 108: 108, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 104, 100, 107, 105, 101, 108, 106, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▎                                                            | 1076/2828 [02:53<06:11,  4.72it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▍                                                            | 1079/2828 [02:53<05:54,  4.94it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 38%|█████████████████████████████████████▌                                                            | 1083/2828 [02:54<04:13,  6.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]

 38%|█████████████████████████████████████▋                                                            | 1087/2828 [02:54<02:58,  9.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 39%|█████████████████████████████████████▊                                                            | 1091/2828 [02:54<02:27, 11.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 39%|█████████████████████████████████████▉                                                            | 1093/2828 [02:55<02:29, 11.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]

 39%|██████████████████████████████████████                                                            | 1097/2828 [02:55<02:06, 13.65it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 109, 104: 112, 105: 113, 106: 105, 107: 107, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 108, 103, 109, 112, 104, 105, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 109, 104: 112, 105: 113, 106: 105, 107: 107, 108: 108, 109: 110, 110: 114, 111: 116, 112: 111, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 108, 103, 109, 112, 104, 105, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▏                                                           | 1101/2828 [02:56<03:41,  7.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▏                                                           | 1103/2828 [02:56<05:24,  5.32it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▎                                                           | 1104/2828 [02:57<07:19,  3.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 39%|██████████████████████████████████████▎                                                           | 1105/2828 [02:57<07:15,  3.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▎                                                           | 1106/2828 [02:58<09:17,  3.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 105, 103: 107, 104: 110, 105: 112, 106: 114, 107: 116, 108: 113, 109: 115, 110: 117, 111: 119, 112: 118, 113: 120, 114: 109, 115: 111, 116: 106, 117: 108, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 101, 102, 116, 103, 117, 114, 104, 115, 105, 108, 106, 109, 107, 110, 112, 111, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 105, 103: 107, 104: 110, 105: 112, 106: 114, 107: 116, 108: 113, 109: 115, 110: 117, 111: 119, 112: 118, 113: 120, 114: 109, 115: 111, 116: 106, 117: 108, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 101, 102, 116, 103, 117, 114, 104, 115, 105, 108, 106, 109, 107, 110, 112, 111, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▍                                                           | 1108/2828 [02:58<09:25,  3.04it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 104, 102, 105, 103, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 104, 102, 105, 103, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▍                                                           | 1109/2828 [02:59<10:57,  2.61it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 39%|██████████████████████████████████████▌                                                           | 1112/2828 [02:59<06:38,  4.31it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▌                                                           | 1114/2828 [03:00<07:44,  3.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▋                                                           | 1116/2828 [03:01<08:13,  3.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|██████████████████████████████████████▋                                                           | 1118/2828 [03:01<06:54,  4.13it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 108, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 106, 104, 105, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 108, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 106, 104, 105, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|██████████████████████████████████████▊                                                           | 1119/2828 [03:01<08:44,  3.26it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|██████████████████████████████████████▊                                                           | 1120/2828 [03:02<10:23,  2.74it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 110, 103: 111, 104: 104, 105: 107, 106: 105, 107: 108, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 110, 103: 111, 104: 104, 105: 107, 106: 105, 107: 108, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|██████████████████████████████████████▊                                                           | 1121/2828 [03:03<11:49,  2.40it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|██████████████████████████████████████▉                                                           | 1124/2828 [03:03<08:10,  3.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████                                                           | 1127/2828 [03:04<05:45,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████                                                           | 1129/2828 [03:04<07:01,  4.03it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████▏                                                          | 1130/2828 [03:05<06:59,  4.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▏                                                          | 1131/2828 [03:05<09:00,  3.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 108, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 106, 104, 105, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 108, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 106, 104, 105, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▎                                                          | 1133/2828 [03:06<09:09,  3.08it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▎                                                          | 1134/2828 [03:06<10:37,  2.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▎                                                          | 1135/2828 [03:07<11:53,  2.37it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████▎                                                          | 1136/2828 [03:07<10:37,  2.66it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████▍                                                          | 1139/2828 [03:08<06:30,  4.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 40%|███████████████████████████████████████▌                                                          | 1141/2828 [03:08<04:56,  5.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 40%|███████████████████████████████████████▋                                                          | 1145/2828 [03:08<03:22,  8.33it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|███████████████████████████████████████▋                                                          | 1147/2828 [03:09<05:13,  5.36it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 41%|███████████████████████████████████████▊                                                          | 1149/2828 [03:09<04:54,  5.70it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 41%|███████████████████████████████████████▉                                                          | 1152/2828 [03:09<03:59,  7.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 41%|███████████████████████████████████████▉                                                          | 1154/2828 [03:10<04:06,  6.79it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▏                                                         | 1158/2828 [03:10<04:22,  6.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 104, 102, 105, 103, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 104, 102, 105, 103, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▎                                                         | 1162/2828 [03:11<04:35,  6.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 41%|████████████████████████████████████████▎                                                         | 1164/2828 [03:12<04:34,  6.06it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▎                                                         | 1165/2828 [03:12<06:34,  4.22it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▍                                                         | 1166/2828 [03:13<08:28,  3.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 41%|████████████████████████████████████████▍                                                         | 1168/2828 [03:13<08:43,  3.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 41%|████████████████████████████████████████▌                                                         | 1170/2828 [03:14<07:16,  3.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▌                                                         | 1171/2828 [03:14<09:09,  3.02it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▌                                                         | 1172/2828 [03:15<10:45,  2.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▋                                                         | 1173/2828 [03:16<12:06,  2.28it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▋                                                         | 1174/2828 [03:16<13:03,  2.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▋                                                         | 1175/2828 [03:17<13:47,  2.00it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▊                                                         | 1176/2828 [03:17<14:20,  1.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▊                                                         | 1177/2828 [03:18<14:43,  1.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▊                                                         | 1179/2828 [03:18<12:02,  2.28it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▉                                                         | 1180/2828 [03:19<12:57,  2.12it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▉                                                         | 1181/2828 [03:20<13:40,  2.01it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 42%|████████████████████████████████████████▉                                                         | 1182/2828 [03:20<11:46,  2.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 110, 104: 114, 105: 115, 106: 102, 107: 105, 108: 108, 109: 106, 110: 109, 111: 112, 112: 116, 113: 118, 114: 117, 115: 119, 116: 113, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 109, 102, 108, 110, 103, 117, 111, 116, 104, 105, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 110, 104: 114, 105: 115, 106: 102, 107: 105, 108: 108, 109: 106, 110: 109, 111: 112, 112: 116, 113: 118, 114: 117, 115: 119, 116: 113, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 109, 102, 108, 110, 103, 117, 111, 116, 104, 105, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|█████████████████████████████████████████                                                         | 1186/2828 [03:21<07:29,  3.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 42%|█████████████████████████████████████████▏                                                        | 1188/2828 [03:21<05:40,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 105, 106: 107, 107: 109, 108: 112, 109: 114, 110: 110, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 101, 100, 105, 102, 106, 103, 107, 110, 104, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|█████████████████████████████████████████▎                                                        | 1191/2828 [03:22<05:28,  4.99it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 42%|█████████████████████████████████████████▎                                                        | 1193/2828 [03:22<04:16,  6.38it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 42%|█████████████████████████████████████████▍                                                        | 1197/2828 [03:22<03:29,  7.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 42%|█████████████████████████████████████████▌                                                        | 1201/2828 [03:22<02:35, 10.45it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|█████████████████████████████████████████▊                                                        | 1205/2828 [03:23<02:14, 12.04it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]

 43%|█████████████████████████████████████████▊                                                        | 1207/2828 [03:23<02:00, 13.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|█████████████████████████████████████████▉                                                        | 1209/2828 [03:23<04:01,  6.72it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 104, 104: 108, 105: 105, 106: 109, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 102, 104, 106, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 104, 104: 108, 105: 105, 106: 109, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 102, 104, 106, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████                                                        | 1213/2828 [03:24<04:14,  6.35it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▏                                                       | 1217/2828 [03:25<05:43,  4.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 118, 111: 115, 112: 117, 113: 105, 114: 107, 115: 102, 116: 104, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 115, 100, 116, 113, 101, 114, 102, 106, 103, 107, 105, 104, 108, 111, 109, 112, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 118, 111: 115, 112: 117, 113: 105, 114: 107, 115: 102, 116: 104, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 115, 100, 116, 113, 101, 114, 102, 106, 103, 107, 105, 104, 108, 111, 109, 112, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▎                                                       | 1221/2828 [03:26<05:01,  5.32it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▍                                                       | 1223/2828 [03:27<06:12,  4.31it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 43%|██████████████████████████████████████████▌                                                       | 1227/2828 [03:27<03:59,  6.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|██████████████████████████████████████████▋                                                       | 1231/2828 [03:28<04:48,  5.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|██████████████████████████████████████████▊                                                       | 1234/2828 [03:29<05:07,  5.18it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 44%|██████████████████████████████████████████▊                                                       | 1237/2828 [03:29<03:29,  7.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 103, 114: 106, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 113, 100, 111, 114, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 103, 114: 106, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 113, 100, 111, 114, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 44%|██████████████████████████████████████████▉                                                       | 1239/2828 [03:30<05:33,  4.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 103, 114: 106, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 113, 100, 111, 114, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 103, 114: 106, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 113, 100, 111, 114, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|██████████████████████████████████████████▉                                                       | 1240/2828 [03:30<07:08,  3.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 44%|███████████████████████████████████████████                                                       | 1242/2828 [03:31<06:12,  4.26it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████                                                       | 1243/2828 [03:31<07:53,  3.35it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████▏                                                      | 1246/2828 [03:32<06:34,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████▎                                                      | 1249/2828 [03:33<05:45,  4.57it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████▍                                                      | 1252/2828 [03:33<05:19,  4.94it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 60, 67: 56, 68: 59, 69: 58}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 68, 66, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 60, 67: 56, 68: 59, 69: 58}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 68, 66, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]

 44%|███████████████████████████████████████████▌                                                      | 1256/2828 [03:34<03:35,  7.29it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 42, 37: 44, 38: 43, 39: 45, 40: 32, 41: 35, 42: 38, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 40, 30, 44, 41, 31, 34, 42, 32, 35, 33, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 42, 37: 44, 38: 43, 39: 45, 40: 32, 41: 35, 42: 38, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 40, 30, 44, 41, 31, 34, 42, 32, 35, 33, 36, 38, 37, 39]
[1, 27, 28]

 45%|███████████████████████████████████████████▋                                                      | 1260/2828 [03:34<02:28, 10.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 45%|███████████████████████████████████████████▊                                                      | 1264/2828 [03:34<02:09, 12.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 113, 103: 111, 104: 105, 105: 110, 106: 114, 107: 116, 108: 115, 109: 117, 110: 102, 111: 106, 112: 107, 113: 112, 114: 103, 115: 108, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 110, 114, 100, 104, 111, 112, 115, 101, 105, 103, 113, 102, 106, 108, 107, 109]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 113, 103: 111, 104: 105, 105: 110, 106: 114, 107: 116, 108: 115, 109: 117, 110: 102, 111: 106, 112: 107, 113: 112, 114: 103, 115: 108, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 110, 114, 100, 104, 111, 112, 115, 101, 105, 103, 113, 102, 106, 108, 107, 109]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|███████████████████████████████████████████▊                                                      | 1266/2828 [03:35<04:05,  6.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████                                                      | 1270/2828 [03:36<04:10,  6.21it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 45%|████████████████████████████████████████████                                                      | 1272/2828 [03:36<03:22,  7.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 45%|████████████████████████████████████████████▎                                                     | 1277/2828 [03:36<02:42,  9.55it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████▎                                                     | 1279/2828 [03:37<04:17,  6.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████▍                                                     | 1283/2828 [03:38<05:31,  4.66it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████▌                                                     | 1285/2828 [03:39<08:06,  3.17it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|████████████████████████████████████████████▋                                                     | 1288/2828 [03:39<05:40,  4.52it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|████████████████████████████████████████████▋                                                     | 1290/2828 [03:40<06:24,  4.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|████████████████████████████████████████████▊                                                     | 1292/2828 [03:41<06:52,  3.73it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|████████████████████████████████████████████▊                                                     | 1293/2828 [03:41<06:43,  3.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|████████████████████████████████████████████▊                                                     | 1294/2828 [03:42<08:26,  3.03it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|████████████████████████████████████████████▉                                                     | 1295/2828 [03:42<09:49,  2.60it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|████████████████████████████████████████████▉                                                     | 1297/2828 [03:43<09:05,  2.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████                                                     | 1300/2828 [03:43<06:52,  3.70it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 46%|█████████████████████████████████████████████                                                     | 1302/2828 [03:44<05:04,  5.01it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▏                                                    | 1304/2828 [03:44<06:01,  4.22it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▏                                                    | 1305/2828 [03:45<07:39,  3.31it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▎                                                    | 1306/2828 [03:45<09:08,  2.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▎                                                    | 1307/2828 [03:46<10:24,  2.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▎                                                    | 1308/2828 [03:46<11:26,  2.21it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 46%|█████████████████████████████████████████████▍                                                    | 1311/2828 [03:47<07:54,  3.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|█████████████████████████████████████████████▌                                                    | 1315/2828 [03:48<04:49,  5.23it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 47%|█████████████████████████████████████████████▋                                                    | 1317/2828 [03:48<03:48,  6.61it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|█████████████████████████████████████████████▋                                                    | 1319/2828 [03:49<05:17,  4.76it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 101, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 101, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|█████████████████████████████████████████████▊                                                    | 1322/2828 [03:49<05:02,  4.97it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 47%|█████████████████████████████████████████████▉                                                    | 1326/2828 [03:50<03:27,  7.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████                                                    | 1330/2828 [03:51<05:10,  4.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 47%|██████████████████████████████████████████████▏                                                   | 1334/2828 [03:51<03:13,  7.71it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 47%|██████████████████████████████████████████████▎                                                   | 1336/2828 [03:51<02:40,  9.29it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|██████████████████████████████████████████████▎                                                   | 1338/2828 [03:51<02:59,  8.28it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|██████████████████████████████████████████████▍                                                   | 1340/2828 [03:52<03:13,  7.69it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 105, 106: 102, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 104, 105, 101, 117, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 105, 106: 102, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 104, 105, 101, 117, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████▌                                                   | 1342/2828 [03:52<04:31,  5.47it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████▌                                                   | 1343/2828 [03:53<06:10,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 48%|██████████████████████████████████████████████▋                                                   | 1347/2828 [03:53<04:07,  5.98it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 48%|██████████████████████████████████████████████▋                                                   | 1349/2828 [03:53<03:16,  7.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|██████████████████████████████████████████████▉                                                   | 1353/2828 [03:54<03:42,  6.62it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|██████████████████████████████████████████████▉                                                   | 1355/2828 [03:55<04:55,  4.99it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|███████████████████████████████████████████████                                                   | 1358/2828 [03:56<04:52,  5.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|███████████████████████████████████████████████▏                                                  | 1360/2828 [03:56<05:45,  4.25it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|███████████████████████████████████████████████▏                                                  | 1361/2828 [03:57<07:19,  3.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 104, 101, 103, 105, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 104, 101, 103, 105, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|███████████████████████████████████████████████▎                                                  | 1365/2828 [03:58<05:29,  4.43it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 48%|███████████████████████████████████████████████▍                                                  | 1369/2828 [03:58<03:34,  6.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]

 49%|███████████████████████████████████████████████▌                                                  | 1373/2828 [03:58<02:27,  9.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]

 49%|███████████████████████████████████████████████▋                                                  | 1377/2828 [03:58<01:59, 12.14it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▊                                                  | 1379/2828 [03:59<03:39,  6.62it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▊                                                  | 1381/2828 [04:00<04:47,  5.04it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 49%|███████████████████████████████████████████████▉                                                  | 1382/2828 [04:00<04:58,  4.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▉                                                  | 1383/2828 [04:00<06:46,  3.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▉                                                  | 1384/2828 [04:01<08:21,  2.88it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▉                                                  | 1385/2828 [04:02<09:41,  2.48it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 102, 113: 104, 114: 107, 115: 111, 116: 112, 117: 108, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 111, 101, 114, 117, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|████████████████████████████████████████████████                                                  | 1388/2828 [04:02<06:54,  3.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 49%|████████████████████████████████████████████████▏                                                 | 1392/2828 [04:03<03:43,  6.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 49%|████████████████████████████████████████████████▍                                                 | 1396/2828 [04:03<02:25,  9.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 49%|████████████████████████████████████████████████▍                                                 | 1398/2828 [04:03<02:46,  8.58it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 111, 107: 115, 108: 116, 109: 114, 110: 110, 111: 106, 112: 109, 113: 113, 114: 112, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 111, 105, 102, 112, 110, 106, 114, 113, 109, 107, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 111, 107: 115, 108: 116, 109: 114, 110: 110, 111: 106, 112: 109, 113: 113, 114: 112, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 111, 105, 102, 112, 110, 106, 114, 113, 109, 107, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 1400/2828 [04:04<04:05,  5.82it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 1401/2828 [04:04<05:46,  4.12it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 1402/2828 [04:05<07:19,  3.25it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 1403/2828 [04:05<08:47,  2.70it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▋                                                 | 1405/2828 [04:06<08:19,  2.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▊                                                 | 1409/2828 [04:07<05:30,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▊                                                 | 1410/2828 [04:07<06:58,  3.39it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▉                                                 | 1411/2828 [04:08<08:22,  2.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 111, 107: 115, 108: 116, 109: 114, 110: 110, 111: 106, 112: 109, 113: 113, 114: 112, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 111, 105, 102, 112, 110, 106, 114, 113, 109, 107, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 111, 107: 115, 108: 116, 109: 114, 110: 110, 111: 106, 112: 109, 113: 113, 114: 112, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 111, 105, 102, 112, 110, 106, 114, 113, 109, 107, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▉                                                 | 1412/2828 [04:08<09:30,  2.48it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 104, 101, 103, 105, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 114, 109: 113, 110: 110, 111: 112, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 104, 101, 103, 105, 106, 110, 107, 111, 109, 108, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████                                                 | 1414/2828 [04:09<08:31,  2.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 50%|█████████████████████████████████████████████████▏                                                | 1420/2828 [04:09<03:55,  5.98it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 50%|█████████████████████████████████████████████████▎                                                | 1424/2828 [04:10<03:08,  7.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 50%|█████████████████████████████████████████████████▍                                                | 1427/2828 [04:10<02:22,  9.85it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▌                                                | 1431/2828 [04:11<03:03,  7.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▋                                                | 1433/2828 [04:11<04:12,  5.52it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▋                                                | 1434/2828 [04:12<05:42,  4.07it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 108, 102: 110, 103: 103, 104: 106, 105: 107, 106: 105, 107: 109, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 103, 100, 106, 104, 105, 101, 107, 102, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 108, 102: 110, 103: 103, 104: 106, 105: 107, 106: 105, 107: 109, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 103, 100, 106, 104, 105, 101, 107, 102, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▊                                                | 1438/2828 [04:13<04:52,  4.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]

 51%|█████████████████████████████████████████████████▉                                                | 1442/2828 [04:13<03:00,  7.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 51%|██████████████████████████████████████████████████                                                | 1446/2828 [04:13<02:14, 10.28it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

 51%|██████████████████████████████████████████████████▏                                               | 1449/2828 [04:13<01:47, 12.79it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 51%|██████████████████████████████████████████████████▎                                               | 1451/2828 [04:14<02:14, 10.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 51%|██████████████████████████████████████████████████▎                                               | 1453/2828 [04:14<02:32,  9.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 52%|██████████████████████████████████████████████████▍                                               | 1457/2828 [04:14<02:21,  9.66it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 52%|██████████████████████████████████████████████████▌                                               | 1459/2828 [04:15<02:39,  8.57it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▋                                               | 1461/2828 [04:15<04:00,  5.68it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▋                                               | 1462/2828 [04:16<05:38,  4.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▋                                               | 1464/2828 [04:17<06:12,  3.67it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▊                                               | 1465/2828 [04:17<07:30,  3.03it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 52%|██████████████████████████████████████████████████▊                                               | 1468/2828 [04:18<04:52,  4.65it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]

 52%|███████████████████████████████████████████████████                                               | 1472/2828 [04:18<03:04,  7.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 52%|███████████████████████████████████████████████████                                               | 1474/2828 [04:18<02:29,  9.04it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▏                                              | 1476/2828 [04:19<03:57,  5.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▎                                              | 1480/2828 [04:19<03:52,  5.79it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 44, 42: 43, 43: 40, 44: 42, 45: 45, 46: 47, 47: 46, 48: 48, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 36, 34, 50, 37, 35, 38, 39, 43, 40, 44, 42, 41, 45, 47, 46, 48, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]

 52%|███████████████████████████████████████████████████▍                                              | 1484/2828 [04:20<02:35,  8.67it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▍                                              | 1486/2828 [04:20<03:59,  5.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▌                                              | 1488/2828 [04:21<05:20,  4.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▋                                              | 1491/2828 [04:22<05:01,  4.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 53%|███████████████████████████████████████████████████▊                                              | 1494/2828 [04:22<03:51,  5.77it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▉                                              | 1497/2828 [04:23<04:52,  4.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]

 53%|███████████████████████████████████████████████████▉                                              | 1499/2828 [04:23<03:42,  5.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 53%|████████████████████████████████████████████████████                                              | 1501/2828 [04:23<03:40,  6.02it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████                                              | 1503/2828 [04:24<05:13,  4.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▏                                             | 1505/2828 [04:25<05:49,  3.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 1508/2828 [04:26<05:04,  4.33it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]

 53%|████████████████████████████████████████████████████▎                                             | 1510/2828 [04:26<03:44,  5.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 1511/2828 [04:26<05:32,  3.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▍                                             | 1512/2828 [04:27<07:06,  3.08it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▍                                             | 1513/2828 [04:27<08:21,  2.62it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▍                                             | 1514/2828 [04:28<09:22,  2.34it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▌                                             | 1515/2828 [04:29<10:14,  2.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▌                                             | 1517/2828 [04:29<09:03,  2.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 54%|████████████████████████████████████████████████████▋                                             | 1519/2828 [04:29<05:33,  3.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 54%|████████████████████████████████████████████████████▋                                             | 1521/2828 [04:30<03:52,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▊                                             | 1523/2828 [04:30<05:31,  3.94it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▉                                             | 1526/2828 [04:31<04:57,  4.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 104, 112: 102, 113: 105, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 111, 113, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 104, 112: 102, 113: 105, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 111, 113, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▉                                             | 1528/2828 [04:32<05:34,  3.89it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 54%|████████████████████████████████████████████████████▉                                             | 1529/2828 [04:32<05:30,  3.93it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 104, 112: 102, 113: 105, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 111, 113, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 104, 112: 102, 113: 105, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 111, 113, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████                                             | 1532/2828 [04:33<04:54,  4.40it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 54%|█████████████████████████████████████████████████████▏                                            | 1536/2828 [04:33<02:53,  7.43it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 54%|█████████████████████████████████████████████████████▎                                            | 1538/2828 [04:33<03:05,  6.95it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 116, 105: 118, 106: 117, 107: 119, 108: 113, 109: 115, 110: 110, 111: 114, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 110, 117, 103, 108, 111, 109, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 116, 105: 118, 106: 117, 107: 119, 108: 113, 109: 115, 110: 110, 111: 114, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 110, 117, 103, 108, 111, 109, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████▎                                            | 1539/2828 [04:34<04:49,  4.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 110, 104: 114, 105: 116, 106: 111, 107: 115, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 109, 114: 103, 115: 105, 116: 108, 117: 112, 118: 113, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 114, 101, 115, 112, 102, 116, 113, 103, 106, 117, 118, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 110, 104: 114, 105: 116, 106: 111, 107: 115, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 109, 114: 103, 115: 105, 116: 108, 117: 112, 118: 113, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 114, 101, 115, 112, 102, 116, 113, 103, 106, 117, 118, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▍                                            | 1542/2828 [04:35<04:35,  4.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 55%|█████████████████████████████████████████████████████▌                                            | 1546/2828 [04:35<02:43,  7.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 55%|█████████████████████████████████████████████████████▋                                            | 1550/2828 [04:35<02:20,  9.09it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 113, 107: 117, 108: 105, 109: 107, 110: 109, 111: 114, 112: 116, 113: 110, 114: 115, 115: 118, 116: 120, 117: 119, 118: 121, 119: 102, 120: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 120, 99, 119, 101, 100, 108, 102, 109, 103, 110, 113, 104, 105, 106, 111, 114, 112, 107, 115, 117, 116, 118]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 113, 107: 117, 108: 105, 109: 107, 110: 109, 111: 114, 112: 116, 113: 110, 114: 115, 115: 118, 116: 120, 117: 119, 118: 121, 119: 102, 120: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 120, 99, 119, 101, 100, 108, 102, 109, 103, 110, 113, 104, 105, 106, 111, 114, 112, 107, 115, 117, 116, 118]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▊                                            | 1552/2828 [04:36<05:24,  3.93it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▊                                            | 1553/2828 [04:37<06:40,  3.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▉                                            | 1555/2828 [04:38<06:54,  3.07it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 59, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 58, 64: 54, 65: 56, 66: 57, 67: 52}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 67, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 59, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 58, 64: 54, 65: 56, 66: 57, 67: 52}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 67, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 55%|█████████████████████████████████████████████████████▉                                            | 1557/2828 [04:38<05:23,  3.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 56, 68: 59, 69: 61}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 66, 68, 56, 69, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 56, 68: 59, 69: 61}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 67, 55, 66, 68, 56, 69, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 1559/2828 [04:39<05:53,  3.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 1560/2828 [04:39<07:13,  2.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▏                                           | 1564/2828 [04:40<05:08,  4.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 55%|██████████████████████████████████████████████████████▎                                           | 1568/2828 [04:40<03:05,  6.80it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 56%|██████████████████████████████████████████████████████▍                                           | 1570/2828 [04:41<04:18,  4.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 56%|██████████████████████████████████████████████████████▌                                           | 1574/2828 [04:42<04:04,  5.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 56%|██████████████████████████████████████████████████████▋                                           | 1578/2828 [04:42<02:40,  7.80it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 56%|██████████████████████████████████████████████████████▊                                           | 1582/2828 [04:42<02:00, 10.36it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]

 56%|██████████████████████████████████████████████████████▉                                           | 1586/2828 [04:42<01:29, 13.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 56%|███████████████████████████████████████████████████████▏                                          | 1591/2828 [04:43<01:34, 13.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 56%|███████████████████████████████████████████████████████▎                                          | 1596/2828 [04:43<01:28, 14.00it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 57%|███████████████████████████████████████████████████████▍                                          | 1598/2828 [04:44<02:17,  8.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 59, 67: 61, 68: 56, 69: 58}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 68, 55, 69, 66, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 59, 67: 61, 68: 56, 69: 58}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 52, 53, 54, 68, 55, 69, 66, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 57%|███████████████████████████████████████████████████████▍                                          | 1600/2828 [04:44<02:08,  9.52it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 57%|███████████████████████████████████████████████████████▌                                          | 1604/2828 [04:45<02:46,  7.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 57%|███████████████████████████████████████████████████████▋                                          | 1608/2828 [04:46<03:32,  5.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 57%|███████████████████████████████████████████████████████▊                                          | 1610/2828 [04:46<02:56,  6.91it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 57%|███████████████████████████████████████████████████████▊                                          | 1612/2828 [04:46<03:59,  5.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 57%|███████████████████████████████████████████████████████▉                                          | 1615/2828 [04:47<03:48,  5.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 57%|████████████████████████████████████████████████████████                                          | 1617/2828 [04:47<03:36,  5.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 57%|████████████████████████████████████████████████████████                                          | 1618/2828 [04:48<05:05,  3.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 57%|████████████████████████████████████████████████████████▏                                         | 1621/2828 [04:48<03:40,  5.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 57%|████████████████████████████████████████████████████████▏                                         | 1622/2828 [04:48<03:56,  5.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 57%|████████████████████████████████████████████████████████▎                                         | 1625/2828 [04:49<03:05,  6.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 58%|████████████████████████████████████████████████████████▍                                         | 1627/2828 [04:49<03:03,  6.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]

 58%|████████████████████████████████████████████████████████▍                                         | 1629/2828 [04:49<02:52,  6.97it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 58%|████████████████████████████████████████████████████████▌                                         | 1632/2828 [04:50<03:26,  5.78it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 58%|████████████████████████████████████████████████████████▌                                         | 1634/2828 [04:50<03:23,  5.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 58%|████████████████████████████████████████████████████████▊                                         | 1638/2828 [04:51<02:34,  7.70it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 58%|████████████████████████████████████████████████████████▊                                         | 1639/2828 [04:51<02:49,  7.03it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 58%|████████████████████████████████████████████████████████▊                                         | 1640/2828 [04:52<04:33,  4.34it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 58%|████████████████████████████████████████████████████████▊                                         | 1641/2828 [04:52<04:37,  4.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 58%|████████████████████████████████████████████████████████▉                                         | 1643/2828 [04:52<03:48,  5.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 58%|█████████████████████████████████████████████████████████                                         | 1646/2828 [04:53<03:59,  4.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]

 58%|█████████████████████████████████████████████████████████▏                                        | 1649/2828 [04:53<02:51,  6.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 58%|█████████████████████████████████████████████████████████▏                                        | 1651/2828 [04:53<02:27,  8.00it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 58%|█████████████████████████████████████████████████████████▎                                        | 1653/2828 [04:53<02:11,  8.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]

 59%|█████████████████████████████████████████████████████████▎                                        | 1655/2828 [04:54<02:42,  7.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]

 59%|█████████████████████████████████████████████████████████▍                                        | 1659/2828 [04:54<02:04,  9.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 3, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 59%|█████████████████████████████████████████████████████████▌                                        | 1661/2828 [04:55<02:44,  7.07it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 59%|█████████████████████████████████████████████████████████▋                                        | 1663/2828 [04:55<03:17,  5.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 59%|█████████████████████████████████████████████████████████▋                                        | 1665/2828 [04:55<03:06,  6.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 59%|█████████████████████████████████████████████████████████▊                                        | 1668/2828 [04:56<03:16,  5.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 59%|█████████████████████████████████████████████████████████▊                                        | 1670/2828 [04:56<03:42,  5.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 13, 8: 9, 9: 10, 10: 14, 11: 15, 12: 17, 13: 19, 14: 16, 15: 18, 16: 20, 17: 22, 18: 21, 19: 23, 20: 7, 21: 11, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 22, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 13, 8: 9, 9: 10, 10: 14, 11: 15, 12: 17, 13: 19, 14: 16, 15: 18, 16: 20, 17: 22, 18: 21, 19: 23, 20: 7, 21: 11, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 22, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 59%|█████████████████████████████████████████████████████████▉                                        | 1672/2828 [04:56<02:52,  6.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 59%|██████████████████████████████████████████████████████████                                        | 1674/2828 [04:57<04:07,  4.67it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 59%|██████████████████████████████████████████████████████████                                        | 1677/2828 [04:58<04:06,  4.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 59%|██████████████████████████████████████████████████████████▏                                       | 1678/2828 [04:58<04:13,  4.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 59%|██████████████████████████████████████████████████████████▏                                       | 1680/2828 [04:58<03:43,  5.14it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 17, 14: 19, 15: 15, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 17, 14: 19, 15: 15, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 59%|██████████████████████████████████████████████████████████▎                                       | 1682/2828 [04:59<03:17,  5.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 58, 56: 60, 57: 63, 58: 56, 59: 59, 60: 61, 61: 64, 62: 66, 63: 62, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 58, 56: 60, 57: 63, 58: 56, 59: 59, 60: 61, 61: 64, 62: 66, 63: 62, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 60%|██████████████████████████████████████████████████████████▍                                       | 1686/2828 [04:59<02:44,  6.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 60%|██████████████████████████████████████████████████████████▍                                       | 1688/2828 [04:59<02:18,  8.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 60%|██████████████████████████████████████████████████████████▋                                       | 1692/2828 [05:00<01:57,  9.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 60%|██████████████████████████████████████████████████████████▋                                       | 1694/2828 [05:00<02:09,  8.73it/s]

{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 60%|██████████████████████████████████████████████████████████▊                                       | 1697/2828 [05:00<02:08,  8.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 35, 36: 34, 37: 37, 38: 39, 39: 36, 40: 38, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 50, 36, 35, 39, 37, 40, 38, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 35, 36: 34, 37: 37, 38: 39, 39: 36, 40: 38, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 50, 36, 35, 39, 37, 40, 38, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 60%|██████████████████████████████████████████████████████████▉                                       | 1699/2828 [05:01<02:24,  7.79it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 60%|███████████████████████████████████████████████████████████                                       | 1703/2828 [05:01<01:55,  9.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 60%|███████████████████████████████████████████████████████████                                       | 1705/2828 [05:01<01:44, 10.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 65, 57: 67, 58: 66, 59: 68, 60: 62, 61: 64, 62: 60, 63: 63, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 62, 55, 60, 63, 61, 56, 58, 57, 59, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 65, 57: 67, 58: 66, 59: 68, 60: 62, 61: 64, 62: 60, 63: 63, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 62, 55, 60, 63, 61, 56, 58, 57, 59, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 72]

 60%|███████████████████████████████████████████████████████████▏                                      | 1709/2828 [05:02<02:00,  9.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 61%|███████████████████████████████████████████████████████████▎                                      | 1713/2828 [05:02<01:49, 10.15it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 61%|███████████████████████████████████████████████████████████▍                                      | 1715/2828 [05:02<01:46, 10.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 22, 18: 21, 19: 20, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 14, 12, 15, 13, 16, 19, 18, 17, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 22, 18: 21, 19: 20, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 14, 12, 15, 13, 16, 19, 18, 17, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 61%|███████████████████████████████████████████████████████████▍                                      | 1717/2828 [05:03<02:03,  9.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 19, 16: 18, 17: 14, 18: 17, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 18, 16, 15, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 19, 16: 18, 17: 14, 18: 17, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 18, 16, 15, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 61%|███████████████████████████████████████████████████████████▌                                      | 1719/2828 [05:03<02:10,  8.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 19, 16: 18, 17: 14, 18: 17, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 18, 16, 15, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 19, 16: 18, 17: 14, 18: 17, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 18, 16, 15, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 61%|███████████████████████████████████████████████████████████▌                                      | 1720/2828 [05:03<02:27,  7.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 61%|███████████████████████████████████████████████████████████▋                                      | 1723/2828 [05:04<02:49,  6.53it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 61%|███████████████████████████████████████████████████████████▊                                      | 1727/2828 [05:04<02:16,  8.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]

 61%|███████████████████████████████████████████████████████████▉                                      | 1731/2828 [05:04<01:40, 10.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 61%|████████████████████████████████████████████████████████████                                      | 1733/2828 [05:05<02:07,  8.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 61%|████████████████████████████████████████████████████████████                                      | 1735/2828 [05:06<04:40,  3.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 10, 6: 6, 7: 9, 8: 11, 9: 12, 10: 14, 11: 18, 12: 20, 13: 19, 14: 21, 15: 15, 16: 17, 17: 13, 18: 16, 19: 5, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 19, 6, 4, 20, 7, 5, 8, 9, 17, 10, 15, 18, 16, 11, 13, 12, 14, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 10, 6: 6, 7: 9, 8: 11, 9: 12, 10: 14, 11: 18, 12: 20, 13: 19, 14: 21, 15: 15, 16: 17, 17: 13, 18: 16, 19: 5, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 19, 6, 4, 20, 7, 5, 8, 9, 17, 10, 15, 18, 16, 11, 13, 12, 14, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 61%|████████████████████████████████████████████████████████████▏                                     | 1738/2828 [05:06<04:18,  4.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 61%|████████████████████████████████████████████████████████████▎                                     | 1739/2828 [05:07<05:30,  3.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 62%|████████████████████████████████████████████████████████████▎                                     | 1740/2828 [05:08<06:34,  2.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 12, 7: 14, 8: 17, 9: 16, 10: 13, 11: 15, 12: 18, 13: 20, 14: 19, 15: 21, 16: 9, 17: 11, 18: 6, 19: 8, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 18, 4, 19, 16, 5, 17, 6, 10, 7, 11, 9, 8, 12, 14, 13, 15, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 12, 7: 14, 8: 17, 9: 16, 10: 13, 11: 15, 12: 18, 13: 20, 14: 19, 15: 21, 16: 9, 17: 11, 18: 6, 19: 8, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 18, 4, 19, 16, 5, 17, 6, 10, 7, 11, 9, 8, 12, 14, 13, 15, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]

 62%|████████████████████████████████████████████████████████████▎                                     | 1742/2828 [05:08<05:01,  3.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 62%|████████████████████████████████████████████████████████████▍                                     | 1743/2828 [05:08<06:09,  2.94it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 58, 56: 60, 57: 59, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 57, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 54, 68, 55, 57, 56, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 58, 56: 60, 57: 59, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 57, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 54, 68, 55, 57, 56, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 62%|████████████████████████████████████████████████████████████▌                                     | 1746/2828 [05:09<03:51,  4.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]

 62%|████████████████████████████████████████████████████████████▋                                     | 1750/2828 [05:09<02:46,  6.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 62%|████████████████████████████████████████████████████████████▋                                     | 1752/2828 [05:09<02:22,  7.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 70, 67: 69, 68: 68, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 68, 67, 66, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 70, 67: 69, 68: 68, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 68, 67, 66, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 62%|████████████████████████████████████████████████████████████▊                                     | 1754/2828 [05:10<02:30,  7.13it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 12, 7: 14, 8: 17, 9: 16, 10: 13, 11: 15, 12: 18, 13: 20, 14: 19, 15: 21, 16: 9, 17: 11, 18: 6, 19: 8, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 18, 4, 19, 16, 5, 17, 6, 10, 7, 11, 9, 8, 12, 14, 13, 15, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 12, 7: 14, 8: 17, 9: 16, 10: 13, 11: 15, 12: 18, 13: 20, 14: 19, 15: 21, 16: 9, 17: 11, 18: 6, 19: 8, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 18, 4, 19, 16, 5, 17, 6, 10, 7, 11, 9, 8, 12, 14, 13, 15, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]

 62%|████████████████████████████████████████████████████████████▊                                     | 1755/2828 [05:10<02:42,  6.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 62%|████████████████████████████████████████████████████████████▉                                     | 1758/2828 [05:11<03:01,  5.89it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 62%|████████████████████████████████████████████████████████████▉                                     | 1760/2828 [05:11<02:19,  7.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 57, 64: 54, 65: 56, 66: 59, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 64, 52, 65, 63, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 58, 54: 60, 55: 62, 56: 64, 57: 61, 58: 63, 59: 65, 60: 67, 61: 66, 62: 68, 63: 57, 64: 54, 65: 56, 66: 59, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 64, 52, 65, 63, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 62%|█████████████████████████████████████████████████████████████                                     | 1762/2828 [05:11<02:31,  7.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 62%|█████████████████████████████████████████████████████████████▏                                    | 1764/2828 [05:12<03:33,  4.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 62%|█████████████████████████████████████████████████████████████▏                                    | 1766/2828 [05:12<03:09,  5.61it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 63%|█████████████████████████████████████████████████████████████▎                                    | 1768/2828 [05:12<02:52,  6.15it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 31, 44: 34, 45: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▍                                    | 1772/2828 [05:13<02:14,  7.82it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▍                                    | 1774/2828 [05:13<02:21,  7.43it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 56, 54: 59, 55: 53, 56: 55, 57: 58, 58: 62, 59: 66, 60: 67, 61: 65, 62: 61, 63: 57, 64: 60, 65: 64, 66: 63, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 56, 54: 59, 55: 53, 56: 55, 57: 58, 58: 62, 59: 66, 60: 67, 61: 65, 62: 61, 63: 57, 64: 60, 65: 64, 66: 63, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▌                                    | 1775/2828 [05:13<02:42,  6.50it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 56, 54: 59, 55: 53, 56: 55, 57: 58, 58: 62, 59: 66, 60: 67, 61: 65, 62: 61, 63: 57, 64: 60, 65: 64, 66: 63, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 56, 54: 59, 55: 53, 56: 55, 57: 58, 58: 62, 59: 66, 60: 67, 61: 65, 62: 61, 63: 57, 64: 60, 65: 64, 66: 63, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▌                                    | 1777/2828 [05:14<02:35,  6.76it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▌                                    | 1778/2828 [05:14<02:54,  6.02it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 23, 19: 24, 20: 25, 21: 20, 22: 22, 23: 7, 24: 11, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 23, 6, 8, 9, 24, 7, 10, 11, 14, 12, 15, 13, 16, 21, 17, 22, 18, 19, 20, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 23, 19: 24, 20: 25, 21: 20, 22: 22, 23: 7, 24: 11, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 23, 6, 8, 9, 24, 7, 10, 11, 14, 12, 15, 13, 16, 21, 17, 22, 18, 19, 20, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 63%|█████████████████████████████████████████████████████████████▋                                    | 1780/2828 [05:14<02:37,  6.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▊                                    | 1783/2828 [05:15<02:52,  6.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 63%|█████████████████████████████████████████████████████████████▊                                    | 1785/2828 [05:15<02:40,  6.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 63%|█████████████████████████████████████████████████████████████▉                                    | 1786/2828 [05:15<02:59,  5.82it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 32, 48: 35, 49: 38}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 63%|█████████████████████████████████████████████████████████████▉                                    | 1789/2828 [05:16<02:54,  5.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 63%|██████████████████████████████████████████████████████████████                                    | 1791/2828 [05:16<02:11,  7.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 63%|██████████████████████████████████████████████████████████████▏                                   | 1794/2828 [05:16<01:56,  8.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 64%|██████████████████████████████████████████████████████████████▏                                   | 1796/2828 [05:16<01:36, 10.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]

 64%|██████████████████████████████████████████████████████████████▍                                   | 1800/2828 [05:17<01:47,  9.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 64%|██████████████████████████████████████████████████████████████▍                                   | 1802/2828 [05:17<01:41, 10.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]

 64%|██████████████████████████████████████████████████████████████▌                                   | 1805/2828 [05:17<01:21, 12.58it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 64%|██████████████████████████████████████████████████████████████▋                                   | 1809/2828 [05:17<01:31, 11.17it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 64%|██████████████████████████████████████████████████████████████▊                                   | 1813/2828 [05:18<01:16, 13.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|██████████████████████████████████████████████████████████████▉                                   | 1817/2828 [05:19<02:54,  5.80it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 64%|███████████████████████████████████████████████████████████████                                   | 1821/2828 [05:19<01:55,  8.74it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████▏                                  | 1823/2828 [05:20<02:53,  5.78it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▎                                  | 1827/2828 [05:20<02:52,  5.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 65%|███████████████████████████████████████████████████████████████▍                                  | 1829/2828 [05:21<02:26,  6.81it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 65%|███████████████████████████████████████████████████████████████▍                                  | 1831/2828 [05:21<02:55,  5.68it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 65%|███████████████████████████████████████████████████████████████▌                                  | 1835/2828 [05:22<02:14,  7.36it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 65%|███████████████████████████████████████████████████████████████▋                                  | 1839/2828 [05:22<01:58,  8.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 65%|███████████████████████████████████████████████████████████████▊                                  | 1841/2828 [05:22<02:10,  7.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 65%|███████████████████████████████████████████████████████████████▊                                  | 1843/2828 [05:23<02:19,  7.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 65%|███████████████████████████████████████████████████████████████▉                                  | 1845/2828 [05:23<02:28,  6.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 65%|███████████████████████████████████████████████████████████████▉                                  | 1846/2828 [05:24<03:42,  4.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 65%|████████████████████████████████████████████████████████████████                                  | 1848/2828 [05:24<03:35,  4.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 65%|████████████████████████████████████████████████████████████████                                  | 1850/2828 [05:24<03:34,  4.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 65%|████████████████████████████████████████████████████████████████▏                                 | 1851/2828 [05:25<03:30,  4.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 65%|████████████████████████████████████████████████████████████████▏                                 | 1852/2828 [05:25<03:36,  4.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 66%|████████████████████████████████████████████████████████████████▏                                 | 1853/2828 [05:25<03:46,  4.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▎                                 | 1855/2828 [05:26<04:25,  3.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 20, 12: 22, 13: 21, 14: 23, 15: 8, 16: 11, 17: 15, 18: 19, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 18, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 20, 12: 22, 13: 21, 14: 23, 15: 8, 16: 11, 17: 15, 18: 19, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 18, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 66%|████████████████████████████████████████████████████████████████▍                                 | 1859/2828 [05:26<02:39,  6.08it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 20, 12: 22, 13: 21, 14: 23, 15: 8, 16: 11, 17: 15, 18: 19, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 18, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 20, 12: 22, 13: 21, 14: 23, 15: 8, 16: 11, 17: 15, 18: 19, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 18, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 66%|████████████████████████████████████████████████████████████████▌                                 | 1862/2828 [05:27<02:11,  7.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 47, 42: 45, 43: 48, 44: 33, 45: 36, 46: 39, 47: 43, 48: 46, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 44, 34, 50, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 48, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 47, 42: 45, 43: 48, 44: 33, 45: 36, 46: 39, 47: 43, 48: 46, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 44, 34, 50, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 48, 41, 43, 29, 30, 31]
[1, 28, 29]

 66%|████████████████████████████████████████████████████████████████▌                                 | 1864/2828 [05:27<01:46,  9.06it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 13, 10: 12, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 10, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 7, 21, 8, 10, 9, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 13, 10: 12, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 10, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 7, 21, 8, 10, 9, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 66%|████████████████████████████████████████████████████████████████▋                                 | 1866/2828 [05:27<02:15,  7.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 13, 10: 12, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 10, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 7, 21, 8, 10, 9, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 13, 10: 12, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 10, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 7, 21, 8, 10, 9, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 66%|████████████████████████████████████████████████████████████████▋                                 | 1867/2828 [05:28<03:34,  4.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]

 66%|████████████████████████████████████████████████████████████████▊                                 | 1869/2828 [05:28<03:17,  4.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]

 66%|████████████████████████████████████████████████████████████████▊                                 | 1871/2828 [05:28<02:52,  5.56it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 66%|████████████████████████████████████████████████████████████████▊                                 | 1872/2828 [05:28<03:05,  5.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]

 66%|█████████████████████████████████████████████████████████████████                                 | 1876/2828 [05:29<02:06,  7.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 66%|█████████████████████████████████████████████████████████████████                                 | 1878/2828 [05:29<01:47,  8.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 22, 20: 21, 21: 20, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 21, 20, 19, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 22, 20: 21, 21: 20, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 21, 20, 19, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 67%|█████████████████████████████████████████████████████████████████▏                                | 1881/2828 [05:30<02:29,  6.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 8, 7: 11, 8: 14, 9: 9, 10: 6, 11: 10, 12: 12, 13: 15, 14: 17, 15: 13, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 10, 5, 6, 9, 11, 7, 12, 15, 8, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 8, 7: 11, 8: 14, 9: 9, 10: 6, 11: 10, 12: 12, 13: 15, 14: 17, 15: 13, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 10, 5, 6, 9, 11, 7, 12, 15, 8, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]

 67%|█████████████████████████████████████████████████████████████████▎                                | 1884/2828 [05:30<02:10,  7.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 12, 7: 13, 8: 14, 9: 7, 10: 8, 11: 9, 12: 10, 13: 15, 14: 16, 15: 18, 16: 21, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 34, 29: 36, 30: 39, 31: 41, 32: 44, 33: 46, 34: 42, 35: 45, 36: 50, 37: 52, 38: 51, 39: 53, 40: 37, 41: 40, 42: 43, 43: 47, 44: 48, 45: 49, 46: 35, 47: 38, 48: 19, 49: 22, 50: 17, 51: 20, 52: 11, 53: 54}
[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 52, 6, 7, 8, 13, 14, 50, 15, 48, 51, 16, 49, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 29, 40, 47, 30, 41, 31, 34, 42, 32, 35, 33, 43, 44, 45, 36, 38, 37, 39, 53]
[1, 2, 6, 7, 8, 9, 10, 11, 54]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]

 67%|█████████████████████████████████████████████████████████████████▎                                | 1886/2828 [05:30<01:43,  9.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 67%|█████████████████████████████████████████████████████████████████▍                                | 1890/2828 [05:30<01:24, 11.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 67%|█████████████████████████████████████████████████████████████████▋                                | 1894/2828 [05:31<01:13, 12.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 67%|█████████████████████████████████████████████████████████████████▋                                | 1896/2828 [05:31<01:37,  9.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 63, 57: 54, 58: 57, 59: 60, 60: 56, 61: 59, 62: 64, 63: 66, 64: 68, 65: 65, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 57, 52, 60, 58, 53, 61, 59, 54, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 67%|█████████████████████████████████████████████████████████████████▊                                | 1898/2828 [05:32<02:21,  6.57it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 67%|█████████████████████████████████████████████████████████████████▉                                | 1901/2828 [05:32<02:10,  7.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]

 67%|█████████████████████████████████████████████████████████████████▉                                | 1903/2828 [05:32<02:08,  7.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 67%|██████████████████████████████████████████████████████████████████                                | 1907/2828 [05:33<01:59,  7.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]

 68%|██████████████████████████████████████████████████████████████████▏                               | 1909/2828 [05:33<01:47,  8.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 68%|██████████████████████████████████████████████████████████████████▎                               | 1913/2828 [05:33<01:32,  9.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 68%|██████████████████████████████████████████████████████████████████▍                               | 1917/2828 [05:34<01:56,  7.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 68%|██████████████████████████████████████████████████████████████████▌                               | 1919/2828 [05:34<02:06,  7.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 68%|██████████████████████████████████████████████████████████████████▌                               | 1922/2828 [05:35<02:02,  7.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 1926/2828 [05:35<02:15,  6.65it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 68%|██████████████████████████████████████████████████████████████████▊                               | 1928/2828 [05:36<01:49,  8.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▉                               | 1930/2828 [05:36<02:45,  5.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▉                               | 1931/2828 [05:37<03:49,  3.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|███████████████████████████████████████████████████████████████████                               | 1934/2828 [05:38<03:28,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]

 68%|███████████████████████████████████████████████████████████████████                               | 1936/2828 [05:38<02:43,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 69%|███████████████████████████████████████████████████████████████████▏                              | 1939/2828 [05:38<02:22,  6.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 54, 57: 57, 58: 60, 59: 56, 60: 59, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 56, 52, 59, 57, 53, 60, 58, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 54, 57: 57, 58: 60, 59: 56, 60: 59, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 56, 52, 59, 57, 53, 60, 58, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 69%|███████████████████████████████████████████████████████████████████▎                              | 1941/2828 [05:38<02:21,  6.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 69%|███████████████████████████████████████████████████████████████████▎                              | 1943/2828 [05:39<02:17,  6.46it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 69%|███████████████████████████████████████████████████████████████████▎                              | 1944/2828 [05:39<02:33,  5.75it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 69%|███████████████████████████████████████████████████████████████████▍                              | 1945/2828 [05:39<02:48,  5.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 69%|███████████████████████████████████████████████████████████████████▍                              | 1947/2828 [05:39<02:32,  5.76it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 69%|███████████████████████████████████████████████████████████████████▌                              | 1949/2828 [05:40<02:50,  5.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 59, 54: 61, 55: 54, 56: 57, 57: 58, 58: 56, 59: 60, 60: 62, 61: 64, 62: 66, 63: 63, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 55, 52, 58, 56, 57, 53, 59, 54, 60, 63, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 59, 54: 61, 55: 54, 56: 57, 57: 58, 58: 56, 59: 60, 60: 62, 61: 64, 62: 66, 63: 63, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 55, 52, 58, 56, 57, 53, 59, 54, 60, 63, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 69%|███████████████████████████████████████████████████████████████████▌                              | 1951/2828 [05:40<02:37,  5.58it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 52, 53: 55, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 68, 61: 70, 62: 69, 63: 71, 64: 57, 65: 59, 66: 62, 67: 66, 68: 67, 69: 54, 70: 56, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 52, 51, 69, 53, 70, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 52, 53: 55, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 68, 61: 70, 62: 69, 63: 71, 64: 57, 65: 59, 66: 62, 67: 66, 68: 67, 69: 54, 70: 56, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 52, 51, 69, 53, 70, 64, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 69%|███████████████████████████████████████████████████████████████████▋                              | 1952/2828 [05:41<02:51,  5.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 60, 56: 56, 57: 57, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 54, 69: 58, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 56, 57, 69, 54, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 60, 56: 56, 57: 57, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 54, 69: 58, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 56, 57, 69, 54, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]

 69%|███████████████████████████████████████████████████████████████████▋                              | 1953/2828 [05:41<03:04,  4.75it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▊                              | 1956/2828 [05:41<02:54,  5.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12, 24: 25, 25: 31, 26: 32, 27: 33, 28: 26, 29: 27, 30: 28, 31: 29, 32: 34, 33: 35, 34: 37, 35: 40, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 55, 49: 58, 50: 60, 51: 63, 52: 65, 53: 61, 54: 64, 55: 69, 56: 71, 57: 70, 58: 72, 59: 56, 60: 59, 61: 62, 62: 66, 63: 67, 64: 68, 65: 54, 66: 57, 67: 38, 68: 41, 69: 36, 70: 39, 71: 30, 72: 73}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19, 24, 28, 29, 30, 31, 71, 25, 26, 27, 32, 33, 69, 34, 67, 70, 35, 68, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 65, 48, 59, 66, 49, 60, 50, 53, 61, 51, 54, 52, 62, 63, 64, 55, 57, 56, 58, 72]
[1, 2, 25, 26, 27, 28, 29, 30, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12, 24: 25, 25: 31, 26: 32, 27: 33, 28: 26, 29: 27, 30: 28, 31: 29, 32: 34, 33: 35, 34: 37, 35: 40, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 55, 49: 58, 50: 60, 51: 63, 52: 65, 53: 61, 54: 64, 55: 69, 56: 71, 57: 70, 58: 72, 59: 56, 60: 59, 61: 62, 62: 66, 63: 67, 64: 68, 65: 54, 66: 57, 67: 38, 68: 41, 69: 36, 70: 39, 71: 30, 72: 73}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19, 24, 28, 29, 30, 31, 71, 25, 26, 27, 32, 33, 69, 34, 67, 70, 35, 68, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 65, 48, 59, 66, 49, 60, 50, 53, 61, 51, 54, 52, 62, 63, 64, 55, 57, 56, 58, 72]
[1, 2, 25, 26, 27, 28, 29, 30, 73]

 69%|███████████████████████████████████████████████████████████████████▊                              | 1957/2828 [05:42<03:00,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69]
[1, 2, 22, 23, 24, 25, 26, 27, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69]
[1, 2, 22, 23, 24, 25, 26, 27, 70]

 69%|███████████████████████████████████████████████████████████████████▊                              | 1958/2828 [05:42<03:04,  4.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 7, 6: 10, 7: 12, 8: 13, 9: 14, 10: 15, 11: 17, 12: 20, 13: 22, 14: 23, 15: 24, 16: 25, 17: 19, 18: 21, 19: 16, 20: 18, 21: 11, 22: 9, 23: 6, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 23, 5, 4, 22, 6, 21, 7, 8, 9, 10, 19, 11, 20, 17, 12, 18, 13, 14, 15, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 7, 6: 10, 7: 12, 8: 13, 9: 14, 10: 15, 11: 17, 12: 20, 13: 22, 14: 23, 15: 24, 16: 25, 17: 19, 18: 21, 19: 16, 20: 18, 21: 11, 22: 9, 23: 6, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 23, 5, 4, 22, 6, 21, 7, 8, 9, 10, 19, 11, 20, 17, 12, 18, 13, 14, 15, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 69%|███████████████████████████████████████████████████████████████████▉                              | 1962/2828 [05:42<02:04,  6.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 70%|████████████████████████████████████████████████████████████████████▏                             | 1966/2828 [05:43<01:26, 10.01it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 1968/2828 [05:44<03:35,  3.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 70%|████████████████████████████████████████████████████████████████████▎                             | 1970/2828 [05:44<03:55,  3.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 70%|████████████████████████████████████████████████████████████████████▍                             | 1974/2828 [05:45<03:15,  4.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 10, 19: 7, 20: 11, 21: 12, 22: 14, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 18, 20, 21, 8, 22, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 10, 19: 7, 20: 11, 21: 12, 22: 14, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 18, 20, 21, 8, 22, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 70%|████████████████████████████████████████████████████████████████████▍                             | 1975/2828 [05:45<03:11,  4.44it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 52, 53: 55, 54: 58, 55: 61, 56: 65, 57: 67, 58: 62, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 57, 65: 60, 66: 54, 67: 56, 68: 59, 69: 63, 70: 64, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 52, 51, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 52, 53: 55, 54: 58, 55: 61, 56: 65, 57: 67, 58: 62, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 57, 65: 60, 66: 54, 67: 56, 68: 59, 69: 63, 70: 64, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 52, 51, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 70%|████████████████████████████████████████████████████████████████████▌                             | 1978/2828 [05:46<02:22,  5.96it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 70%|████████████████████████████████████████████████████████████████████▌                             | 1980/2828 [05:46<01:59,  7.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▊                             | 1984/2828 [05:47<02:12,  6.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 70%|████████████████████████████████████████████████████████████████████▉                             | 1988/2828 [05:47<01:35,  8.81it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 54, 57: 57, 58: 60, 59: 56, 60: 59, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 56, 52, 59, 57, 53, 60, 58, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 58, 54: 61, 55: 62, 56: 54, 57: 57, 58: 60, 59: 56, 60: 59, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 56, 52, 59, 57, 53, 60, 58, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 70%|█████████████████████████████████████████████████████████████████████                             | 1992/2828 [05:48<02:14,  6.21it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 71%|█████████████████████████████████████████████████████████████████████▏                            | 1996/2828 [05:48<01:37,  8.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▏                            | 1998/2828 [05:49<02:39,  5.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 71%|█████████████████████████████████████████████████████████████████████▎                            | 2000/2828 [05:49<02:05,  6.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 71%|█████████████████████████████████████████████████████████████████████▍                            | 2002/2828 [05:50<02:20,  5.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]

 71%|█████████████████████████████████████████████████████████████████████▌                            | 2007/2828 [05:50<01:33,  8.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 71%|█████████████████████████████████████████████████████████████████████▌                            | 2009/2828 [05:50<01:27,  9.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 71%|█████████████████████████████████████████████████████████████████████▊                            | 2013/2828 [05:51<01:19, 10.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10, 52: 53}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38, 52]
[1, 2, 5, 6, 7, 8, 9, 10, 53]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 71%|█████████████████████████████████████████████████████████████████████▊                            | 2015/2828 [05:51<02:13,  6.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 71%|█████████████████████████████████████████████████████████████████████▉                            | 2018/2828 [05:52<02:30,  5.40it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 71%|██████████████████████████████████████████████████████████████████████                            | 2020/2828 [05:52<02:04,  6.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 71%|██████████████████████████████████████████████████████████████████████                            | 2022/2828 [05:53<02:44,  4.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 72%|██████████████████████████████████████████████████████████████████████▏                           | 2024/2828 [05:53<03:15,  4.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 72%|██████████████████████████████████████████████████████████████████████▏                           | 2026/2828 [05:54<03:35,  3.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 72%|██████████████████████████████████████████████████████████████████████▎                           | 2028/2828 [05:55<03:49,  3.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 72%|██████████████████████████████████████████████████████████████████████▎                           | 2030/2828 [05:55<03:15,  4.08it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 72%|██████████████████████████████████████████████████████████████████████▍                           | 2031/2828 [05:55<03:10,  4.18it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 72%|██████████████████████████████████████████████████████████████████████▍                           | 2032/2828 [05:55<03:06,  4.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 72%|██████████████████████████████████████████████████████████████████████▌                           | 2036/2828 [05:56<02:02,  6.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 72%|██████████████████████████████████████████████████████████████████████▌                           | 2038/2828 [05:56<01:59,  6.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]

 72%|██████████████████████████████████████████████████████████████████████▋                           | 2040/2828 [05:56<01:39,  7.91it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 53, 55: 56, 56: 58, 57: 61, 58: 63, 59: 60, 60: 57, 61: 59, 62: 62, 63: 64, 64: 66, 65: 67, 66: 65, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 54, 52, 53, 55, 60, 56, 61, 59, 57, 62, 58, 63, 66, 64, 65, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 53, 55: 56, 56: 58, 57: 61, 58: 63, 59: 60, 60: 57, 61: 59, 62: 62, 63: 64, 64: 66, 65: 67, 66: 65, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 54, 52, 53, 55, 60, 56, 61, 59, 57, 62, 58, 63, 66, 64, 65, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 72%|██████████████████████████████████████████████████████████████████████▊                           | 2043/2828 [05:57<01:37,  8.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 16, 8: 18, 9: 13, 10: 17, 11: 22, 12: 24, 13: 23, 14: 25, 15: 8, 16: 11, 17: 15, 18: 21, 19: 7, 20: 10, 21: 14, 22: 19, 23: 20, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 19, 15, 5, 20, 16, 6, 9, 21, 17, 7, 10, 8, 22, 23, 18, 11, 13, 12, 14, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 72%|██████████████████████████████████████████████████████████████████████▊                           | 2045/2828 [05:57<01:39,  7.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 22, 16: 23, 17: 24, 18: 19, 19: 21, 20: 9, 21: 12, 22: 7, 23: 10, 24: 25, 25: 26, 26: 27, 27: 31, 28: 32, 29: 33, 30: 28, 31: 29, 32: 34, 33: 35, 34: 37, 35: 40, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 55, 49: 58, 50: 60, 51: 63, 52: 65, 53: 61, 54: 64, 55: 69, 56: 71, 57: 70, 58: 72, 59: 56, 60: 59, 61: 62, 62: 66, 63: 67, 64: 68, 65: 54, 66: 57, 67: 38, 68: 41, 69: 36, 70: 39, 71: 30, 72: 73, 73: 79, 74: 80, 75: 81, 76: 74, 77: 75, 78: 76, 79: 77, 80: 82, 81: 83, 82: 85, 83: 88, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 100, 95: 101, 96: 103, 97: 106, 98: 108, 99: 111, 100: 113, 101: 109, 102: 112, 103: 117, 104: 119, 105: 118, 106: 120, 107: 104, 108: 107, 109: 110, 110: 114, 111: 115, 112: 116, 113: 102, 114: 105, 115: 86, 116: 89, 117: 84, 118: 87, 119: 78, 120: 121}
[0, 1, 2, 3, 4, 5, 22, 6, 20, 23, 7, 21, 8, 11, 9, 12, 10, 13, 18, 14, 19, 15, 16, 17, 24, 25, 26, 30, 31, 71, 27, 28, 29, 32, 33, 69, 34, 67, 70, 35, 68, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 65, 48, 59, 66, 49, 60, 50, 53, 61, 51, 54, 52, 62, 63, 64, 55, 57, 56, 58, 72, 76, 77, 78, 79, 119, 73, 74, 75, 80, 81, 117, 82, 115, 118, 83, 116, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 113, 96, 107, 114, 97, 108, 98, 101, 109, 99, 102, 100, 110, 111, 112, 103, 105, 104, 106, 120]
[1, 25, 26, 27, 28, 29, 30, 73, 74, 75, 76, 77, 78, 121]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 22, 16: 23, 17: 24, 18: 19, 19: 21, 20: 9, 21: 12, 22: 7, 23: 10, 24: 25, 25: 26, 26: 27, 27: 31, 28: 32, 29: 33, 30: 28, 31: 29, 32: 34, 33: 35, 34: 37, 35: 40, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 55, 49: 58, 50: 60, 51: 63, 52: 65, 53: 61, 54: 64, 55: 69, 56: 71, 57: 70, 58: 72, 59: 56, 60: 59, 61: 62, 62: 66, 63: 67, 64: 68, 65: 54, 66: 57, 67: 38, 68: 41, 69: 36, 70: 39, 71: 30, 72: 73, 73: 79, 74: 80, 75: 81, 76: 74, 77: 75, 78: 76, 79: 77, 80: 82, 81: 83, 82: 85, 83: 88, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 100, 95: 101, 96: 103, 97: 106, 98: 108, 99: 111, 100: 113, 101: 109, 102: 112, 103: 117, 104: 119, 105: 118, 106: 120, 107: 104, 108: 107, 109: 110, 110: 114, 111: 115, 112: 116, 113: 102, 114: 105, 115: 86, 116: 89, 117: 84, 118: 87, 119: 78, 120: 121}
[0, 1, 2, 3, 4, 5, 22, 6, 20, 23, 7, 21, 8, 11, 9, 12, 10, 13, 18, 14, 19, 15, 16, 17, 24, 25, 26, 30, 31, 71, 27, 28, 29, 32, 33, 69, 34, 67, 70, 35, 68, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 65, 48, 59, 66, 49, 60, 50, 53, 61, 51, 54, 52, 62, 63, 64, 55, 57, 56, 58, 72, 76, 77, 78, 79, 119, 73, 74, 75, 80, 81, 117, 82, 115, 118, 83, 116, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 113, 96, 107, 114, 97, 108, 98, 101, 109, 99, 102, 100, 110, 111, 112, 103, 105, 104, 106, 120]
[1, 25, 26, 27, 28, 29, 30, 73, 74, 75, 76, 77, 78, 121]

 72%|██████████████████████████████████████████████████████████████████████▉                           | 2046/2828 [05:58<02:49,  4.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 72%|██████████████████████████████████████████████████████████████████████▉                           | 2048/2828 [05:58<02:29,  5.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 72%|███████████████████████████████████████████████████████████████████████                           | 2050/2828 [05:58<02:17,  5.64it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▏                          | 2053/2828 [05:59<02:18,  5.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 73%|███████████████████████████████████████████████████████████████████████▏                          | 2055/2828 [05:59<01:53,  6.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 73%|███████████████████████████████████████████████████████████████████████▎                          | 2059/2828 [05:59<01:15, 10.17it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]

 73%|███████████████████████████████████████████████████████████████████████▍                          | 2061/2828 [06:00<02:11,  5.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 34, 32: 35, 33: 37, 34: 40, 35: 42, 36: 38, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 36, 43: 39, 44: 31, 45: 33}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 45, 31, 32, 42, 33, 36, 43, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 73%|███████████████████████████████████████████████████████████████████████▍                          | 2063/2828 [06:00<01:47,  7.10it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 10, 19: 7, 20: 11, 21: 13, 22: 14, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 18, 20, 8, 21, 22, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 10, 19: 7, 20: 11, 21: 13, 22: 14, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 18, 20, 8, 21, 22, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 73%|███████████████████████████████████████████████████████████████████████▌                          | 2066/2828 [06:00<01:53,  6.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 73%|███████████████████████████████████████████████████████████████████████▋                          | 2068/2828 [06:00<01:37,  7.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▋                          | 2070/2828 [06:01<01:47,  7.07it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 2071/2828 [06:01<02:02,  6.18it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 2072/2828 [06:01<02:16,  5.53it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 2073/2828 [06:02<02:28,  5.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 2074/2828 [06:02<02:38,  4.76it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▉                          | 2075/2828 [06:02<02:46,  4.53it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 73%|███████████████████████████████████████████████████████████████████████▉                          | 2076/2828 [06:02<02:52,  4.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]

 74%|████████████████████████████████████████████████████████████████████████                          | 2079/2828 [06:03<02:06,  5.91it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]

 74%|████████████████████████████████████████████████████████████████████████                          | 2081/2828 [06:03<01:38,  7.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 74%|████████████████████████████████████████████████████████████████████████▏                         | 2083/2828 [06:03<01:48,  6.88it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 55, 56: 58, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 56, 58, 54, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 74%|████████████████████████████████████████████████████████████████████████▏                         | 2084/2828 [06:03<02:04,  5.99it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 74%|████████████████████████████████████████████████████████████████████████▎                         | 2086/2828 [06:04<02:00,  6.14it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 52, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 52, 71]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 2089/2828 [06:04<01:48,  6.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 2091/2828 [06:05<02:34,  4.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 74%|████████████████████████████████████████████████████████████████████████▌                         | 2095/2828 [06:05<01:52,  6.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 74%|████████████████████████████████████████████████████████████████████████▋                         | 2098/2828 [06:06<01:41,  7.22it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 68, 59: 70, 60: 64, 61: 66, 62: 61, 63: 65, 64: 56, 65: 59, 66: 53, 67: 55, 68: 58, 69: 62, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 62, 69, 55, 60, 63, 61, 56, 58, 57, 59, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 63, 56: 67, 57: 69, 58: 68, 59: 70, 60: 64, 61: 66, 62: 61, 63: 65, 64: 56, 65: 59, 66: 53, 67: 55, 68: 58, 69: 62, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 62, 69, 55, 60, 63, 61, 56, 58, 57, 59, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 74%|████████████████████████████████████████████████████████████████████████▋                         | 2099/2828 [06:06<01:58,  6.17it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 8, 6: 4, 7: 6, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 6, 3, 7, 4, 5, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 8, 6: 4, 7: 6, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 6, 3, 7, 4, 5, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 74%|████████████████████████████████████████████████████████████████████████▊                         | 2102/2828 [06:06<01:41,  7.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▉                         | 2105/2828 [06:07<01:37,  7.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 75%|█████████████████████████████████████████████████████████████████████████                         | 2107/2828 [06:07<01:25,  8.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 75%|█████████████████████████████████████████████████████████████████████████                         | 2109/2828 [06:07<01:38,  7.29it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████                         | 2110/2828 [06:08<01:53,  6.33it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 75%|█████████████████████████████████████████████████████████████████████████▏                        | 2111/2828 [06:08<02:08,  5.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 75%|█████████████████████████████████████████████████████████████████████████▏                        | 2112/2828 [06:08<02:12,  5.39it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 62, 67: 66, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 54, 65, 55, 58, 66, 56, 59, 57, 67, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 62, 67: 66, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 54, 65, 55, 58, 66, 56, 59, 57, 67, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 75%|█████████████████████████████████████████████████████████████████████████▏                        | 2113/2828 [06:08<02:25,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 75%|█████████████████████████████████████████████████████████████████████████▎                        | 2115/2828 [06:09<02:08,  5.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 75%|█████████████████████████████████████████████████████████████████████████▍                        | 2119/2828 [06:09<01:32,  7.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 44, 44: 43, 45: 39, 46: 42, 47: 45, 48: 47, 49: 46, 50: 48}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 45, 37, 42, 46, 44, 43, 47, 49, 48, 50, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]

 75%|█████████████████████████████████████████████████████████████████████████▌                        | 2123/2828 [06:09<01:05, 10.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 47, 36: 42, 37: 45, 38: 40, 39: 43, 40: 46, 41: 48, 42: 49, 43: 50, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 38, 33, 36, 39, 34, 37, 40, 35, 41, 42, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 75%|█████████████████████████████████████████████████████████████████████████▋                        | 2125/2828 [06:09<01:03, 10.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 75%|█████████████████████████████████████████████████████████████████████████▋                        | 2127/2828 [06:10<00:59, 11.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▊                        | 2129/2828 [06:10<01:50,  6.30it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▊                        | 2130/2828 [06:11<02:43,  4.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 75%|█████████████████████████████████████████████████████████████████████████▉                        | 2134/2828 [06:11<01:55,  6.00it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 20, 14: 22, 15: 21, 16: 23, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 13, 15, 14, 16, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 20, 14: 22, 15: 21, 16: 23, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 13, 15, 14, 16, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 76%|██████████████████████████████████████████████████████████████████████████                        | 2136/2828 [06:12<02:05,  5.51it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 20, 14: 22, 15: 21, 16: 23, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 13, 15, 14, 16, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 20, 14: 22, 15: 21, 16: 23, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 13, 15, 14, 16, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 76%|██████████████████████████████████████████████████████████████████████████                        | 2138/2828 [06:12<01:36,  7.13it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 63, 56: 64, 57: 65, 58: 56, 59: 60, 60: 66, 61: 57, 62: 54, 63: 58, 64: 61, 65: 67, 66: 69, 67: 62, 68: 68, 69: 70, 70: 72, 71: 71, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 58, 61, 63, 54, 59, 64, 67, 55, 56, 57, 60, 65, 68, 66, 69, 71, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 63, 56: 64, 57: 65, 58: 56, 59: 60, 60: 66, 61: 57, 62: 54, 63: 58, 64: 61, 65: 67, 66: 69, 67: 62, 68: 68, 69: 70, 70: 72, 71: 71, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 58, 61, 63, 54, 59, 64, 67, 55, 56, 57, 60, 65, 68, 66, 69, 71, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 76%|██████████████████████████████████████████████████████████████████████████                        | 2139/2828 [06:12<01:54,  6.01it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 63, 56: 64, 57: 65, 58: 56, 59: 60, 60: 66, 61: 57, 62: 54, 63: 58, 64: 61, 65: 67, 66: 69, 67: 62, 68: 68, 69: 70, 70: 72, 71: 71, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 58, 61, 63, 54, 59, 64, 67, 55, 56, 57, 60, 65, 68, 66, 69, 71, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 63, 56: 64, 57: 65, 58: 56, 59: 60, 60: 66, 61: 57, 62: 54, 63: 58, 64: 61, 65: 67, 66: 69, 67: 62, 68: 68, 69: 70, 70: 72, 71: 71, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 58, 61, 63, 54, 59, 64, 67, 55, 56, 57, 60, 65, 68, 66, 69, 71, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 2141/2828 [06:12<01:52,  6.11it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 2142/2828 [06:13<02:04,  5.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 53, 65: 56, 66: 58, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 63, 65, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 53, 65: 56, 66: 58, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 63, 65, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▎                       | 2145/2828 [06:13<01:43,  6.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 2147/2828 [06:13<01:28,  7.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 2149/2828 [06:13<01:18,  8.68it/s]

{0: 1, 1: 2, 2: 4, 3: 3, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 3, 2, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]
{0: 1, 1: 2, 2: 4, 3: 3, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 27, 24: 28, 25: 29, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26, 68: 69, 69: 75, 70: 76, 71: 77, 72: 70, 73: 71, 74: 72, 75: 73, 76: 78, 77: 79, 78: 81, 79: 84, 80: 86, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 99, 93: 102, 94: 104, 95: 107, 96: 109, 97: 105, 98: 108, 99: 113, 100: 115, 101: 114, 102: 116, 103: 100, 104: 103, 105: 106, 106: 110, 107: 111, 108: 112, 109: 98, 110: 101, 111: 82, 112: 85, 113: 80, 114: 83, 115: 74, 116: 117}
[0, 1, 3, 2, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 26, 27, 67, 23, 24, 25, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54, 68, 72, 73, 74, 75, 115, 69, 70, 71, 76, 77, 113, 78, 111, 114, 79, 112, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 109, 92, 103, 110, 93, 104, 94, 97, 105, 95, 98, 96, 106, 107, 108, 99, 101, 100, 102, 116]
[1, 21, 22, 23, 24, 25, 26, 69, 70, 71, 72, 73, 74, 117]

 76%|██████████████████████████████████████████████████████████████████████████▌                       | 2150/2828 [06:14<02:18,  4.88it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▌                       | 2152/2828 [06:15<02:44,  4.11it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▋                       | 2154/2828 [06:15<02:59,  3.75it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▋                       | 2156/2828 [06:16<03:11,  3.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 53, 65: 56, 66: 58, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 63, 65, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 53, 65: 56, 66: 58, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 63, 65, 53, 66, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 2158/2828 [06:16<02:55,  3.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 2159/2828 [06:17<02:46,  4.02it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 2160/2828 [06:17<02:45,  4.03it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 54, 55: 56, 56: 59, 57: 60, 58: 58, 59: 61, 60: 63, 61: 65, 62: 67, 63: 66, 64: 68, 65: 64, 66: 62, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 54, 52, 55, 53, 58, 56, 57, 59, 66, 60, 65, 61, 63, 62, 64, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 54, 55: 56, 56: 59, 57: 60, 58: 58, 59: 61, 60: 63, 61: 65, 62: 67, 63: 66, 64: 68, 65: 64, 66: 62, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 54, 52, 55, 53, 58, 56, 57, 59, 66, 60, 65, 61, 63, 62, 64, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 76%|██████████████████████████████████████████████████████████████████████████▉                       | 2162/2828 [06:17<02:19,  4.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▉                       | 2163/2828 [06:18<03:13,  3.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 77%|██████████████████████████████████████████████████████████████████████████▉                       | 2164/2828 [06:18<03:00,  3.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 77%|███████████████████████████████████████████████████████████████████████████                       | 2167/2828 [06:18<01:57,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]

 77%|███████████████████████████████████████████████████████████████████████████▏                      | 2169/2828 [06:18<01:31,  7.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 77%|███████████████████████████████████████████████████████████████████████████▎                      | 2172/2828 [06:19<01:41,  6.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 17, 8: 19, 9: 13, 10: 18, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 5, 18: 8, 19: 11, 20: 14, 21: 15, 22: 16, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 19, 6, 9, 20, 21, 22, 7, 10, 8, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▎                      | 2173/2828 [06:19<01:54,  5.74it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 2177/2828 [06:20<01:22,  7.84it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 2178/2828 [06:20<01:39,  6.56it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▌                      | 2182/2828 [06:21<01:48,  5.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 8, 6: 7, 7: 10, 8: 11, 9: 9, 10: 12, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 6, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 20, 6, 5, 9, 7, 8, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 8, 6: 7, 7: 10, 8: 11, 9: 9, 10: 12, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 6, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 20, 6, 5, 9, 7, 8, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 77%|███████████████████████████████████████████████████████████████████████████▋                      | 2183/2828 [06:21<02:40,  4.02it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 57, 57: 54, 58: 58, 59: 60, 60: 62, 61: 64, 62: 61, 63: 63, 64: 65, 65: 67, 66: 66, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 57, 53, 54, 56, 58, 55, 59, 62, 60, 63, 61, 64, 66, 65, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 57, 57: 54, 58: 58, 59: 60, 60: 62, 61: 64, 62: 61, 63: 63, 64: 65, 65: 67, 66: 66, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 57, 53, 54, 56, 58, 55, 59, 62, 60, 63, 61, 64, 66, 65, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 69]

 77%|███████████████████████████████████████████████████████████████████████████▋                      | 2184/2828 [06:21<02:39,  4.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 77%|███████████████████████████████████████████████████████████████████████████▊                      | 2188/2828 [06:22<01:40,  6.39it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 56, 58: 59, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 54, 57, 53, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 77%|███████████████████████████████████████████████████████████████████████████▉                      | 2190/2828 [06:22<01:56,  5.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 7, 10: 11, 11: 13, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 9, 6, 7, 8, 10, 12, 11, 13, 16, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 7, 10: 11, 11: 13, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 9, 6, 7, 8, 10, 12, 11, 13, 16, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 77%|███████████████████████████████████████████████████████████████████████████▉                      | 2191/2828 [06:23<01:59,  5.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 7, 10: 11, 11: 13, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 9, 6, 7, 8, 10, 12, 11, 13, 16, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 7, 10: 11, 11: 13, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 9, 6, 7, 8, 10, 12, 11, 13, 16, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 78%|███████████████████████████████████████████████████████████████████████████▉                      | 2193/2828 [06:23<01:28,  7.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 57, 56: 59, 57: 60, 58: 62, 59: 64, 60: 61, 61: 63, 62: 65, 63: 67, 64: 66, 65: 68, 66: 54, 67: 58, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 54, 55, 67, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 57, 56: 59, 57: 60, 58: 62, 59: 64, 60: 61, 61: 63, 62: 65, 63: 67, 64: 66, 65: 68, 66: 54, 67: 58, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 54, 55, 67, 56, 57, 60, 58, 61, 59, 62, 64, 63, 65, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 69]

 78%|████████████████████████████████████████████████████████████████████████████                      | 2196/2828 [06:23<01:17,  8.15it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 35, 38: 38, 39: 36, 40: 39, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 50, 35, 37, 39, 36, 38, 40, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 35, 38: 38, 39: 36, 40: 39, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 50, 35, 37, 39, 36, 38, 40, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 78%|████████████████████████████████████████████████████████████████████████████▏                     | 2198/2828 [06:23<01:25,  7.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 78%|████████████████████████████████████████████████████████████████████████████▏                     | 2200/2828 [06:24<01:32,  6.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 60, 57: 56, 58: 58, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 60, 57: 56, 58: 58, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 78%|████████████████████████████████████████████████████████████████████████████▎                     | 2202/2828 [06:24<01:36,  6.49it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 62, 67: 66, 68: 54, 69: 57, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 64, 69, 54, 65, 55, 58, 66, 56, 59, 57, 67, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 63, 57: 65, 58: 61, 59: 64, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 62, 67: 66, 68: 54, 69: 57, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 64, 69, 54, 65, 55, 58, 66, 56, 59, 57, 67, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 2205/2828 [06:24<01:29,  6.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 2207/2828 [06:25<01:35,  6.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 59, 57: 58, 58: 62, 59: 65, 60: 61, 61: 57, 62: 60, 63: 63, 64: 66, 65: 68, 66: 64, 67: 67, 68: 69, 69: 71, 70: 70, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 61, 57, 56, 62, 60, 58, 63, 66, 59, 64, 67, 65, 68, 70, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 54, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 59, 57: 58, 58: 62, 59: 65, 60: 61, 61: 57, 62: 60, 63: 63, 64: 66, 65: 68, 66: 64, 67: 67, 68: 69, 69: 71, 70: 70, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 61, 57, 56, 62, 60, 58, 63, 66, 59, 64, 67, 65, 68, 70, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 54, 73]

 78%|████████████████████████████████████████████████████████████████████████████▌                     | 2208/2828 [06:25<01:47,  5.78it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 78%|████████████████████████████████████████████████████████████████████████████▌                     | 2211/2828 [06:25<01:25,  7.18it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 78%|████████████████████████████████████████████████████████████████████████████▋                     | 2213/2828 [06:26<01:11,  8.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 15, 12: 19, 13: 21, 14: 16, 15: 20, 16: 22, 17: 24, 18: 23, 19: 25, 20: 7, 21: 11, 22: 14, 23: 17, 24: 18, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 22, 11, 14, 23, 24, 12, 15, 13, 16, 18, 17, 19, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 2215/2828 [06:26<01:30,  6.74it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 62, 56: 67, 57: 69, 58: 68, 59: 70, 60: 63, 61: 65, 62: 60, 63: 64, 64: 56, 65: 58, 66: 61, 67: 66, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 65, 54, 62, 66, 55, 60, 63, 61, 67, 56, 58, 57, 59, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 62, 56: 67, 57: 69, 58: 68, 59: 70, 60: 63, 61: 65, 62: 60, 63: 64, 64: 56, 65: 58, 66: 61, 67: 66, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 65, 54, 62, 66, 55, 60, 63, 61, 67, 56, 58, 57, 59, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 2216/2828 [06:26<01:43,  5.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 2218/2828 [06:27<02:17,  4.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|████████████████████████████████████████████████████████████████████████████▉                     | 2221/2828 [06:28<02:13,  4.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 79%|█████████████████████████████████████████████████████████████████████████████                     | 2225/2828 [06:28<01:18,  7.64it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 37, 32: 41, 33: 42, 34: 43, 35: 32, 36: 36, 37: 40, 38: 35, 39: 31, 40: 34, 41: 38, 42: 44, 43: 46, 44: 39, 45: 45, 46: 47, 47: 49, 48: 48, 49: 50}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 39, 35, 30, 40, 38, 36, 31, 41, 44, 37, 32, 33, 34, 42, 45, 43, 46, 48, 47, 49]
[1, 27, 28]

 79%|█████████████████████████████████████████████████████████████████████████████▏                    | 2227/2828 [06:28<01:05,  9.16it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▏                    | 2229/2828 [06:29<01:56,  5.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 2233/2828 [06:29<01:32,  6.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 2235/2828 [06:29<01:20,  7.40it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]

 79%|█████████████████████████████████████████████████████████████████████████████▌                    | 2237/2828 [06:30<01:08,  8.57it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 63, 58: 57, 59: 54, 60: 58, 61: 60, 62: 64, 63: 66, 64: 61, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 59, 53, 54, 58, 60, 55, 61, 64, 56, 57, 62, 65, 63, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 63, 58: 57, 59: 54, 60: 58, 61: 60, 62: 64, 63: 66, 64: 61, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 59, 53, 54, 58, 60, 55, 61, 64, 56, 57, 62, 65, 63, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]

 79%|█████████████████████████████████████████████████████████████████████████████▌                    | 2239/2828 [06:30<01:31,  6.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▋                    | 2242/2828 [06:31<01:40,  5.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▊                    | 2246/2828 [06:32<01:39,  5.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 79%|█████████████████████████████████████████████████████████████████████████████▉                    | 2248/2828 [06:32<01:24,  6.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 2252/2828 [06:32<01:04,  8.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 2254/2828 [06:32<00:54, 10.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 55, 56: 59, 57: 56, 58: 60, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 55, 56: 59, 57: 56, 58: 60, 59: 61, 60: 63, 61: 65, 62: 62, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 55, 57, 53, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 80%|██████████████████████████████████████████████████████████████████████████████▏                   | 2256/2828 [06:32<01:05,  8.79it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 58, 55: 61, 56: 56, 57: 59, 58: 57, 59: 60, 60: 62, 61: 64, 62: 66, 63: 63, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 52, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 58, 55: 61, 56: 56, 57: 59, 58: 57, 59: 60, 60: 62, 61: 64, 62: 66, 63: 63, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 52, 53, 56, 58, 54, 57, 59, 55, 60, 63, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 57, 56: 54, 57: 58, 58: 60, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 56, 53, 54, 55, 57, 59, 58, 60, 63, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 57, 56: 54, 57: 58, 58: 60, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 56, 53, 54, 55, 57, 59, 58, 60, 63, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 80%|██████████████████████████████████████████████████████████████████████████████▎                   | 2260/2828 [06:33<01:14,  7.65it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]

 80%|██████████████████████████████████████████████████████████████████████████████▍                   | 2262/2828 [06:33<01:06,  8.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 80%|██████████████████████████████████████████████████████████████████████████████▍                   | 2264/2828 [06:33<01:01,  9.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 11, 7: 8, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70}
[0, 1, 2, 3, 4, 19, 5, 7, 8, 20, 6, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69]
[1, 2, 22, 23, 24, 25, 26, 27, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 11, 7: 8, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70}
[0, 1, 2, 3, 4, 19, 5, 7, 8, 20, 6, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69]
[1, 2, 22, 23, 24, 25, 26, 27, 70]

 80%|██████████████████████████████████████████████████████████████████████████████▌                   | 2266/2828 [06:34<01:06,  8.42it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 80%|██████████████████████████████████████████████████████████████████████████████▋                   | 2270/2828 [06:34<00:54, 10.20it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 80%|██████████████████████████████████████████████████████████████████████████████▋                   | 2272/2828 [06:34<01:06,  8.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████▊                   | 2275/2828 [06:35<01:23,  6.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 60, 66: 53, 67: 55, 68: 59, 69: 63, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 54, 68, 65, 55, 58, 69, 56, 59, 57, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 58, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 60, 66: 53, 67: 55, 68: 59, 69: 63, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 54, 68, 65, 55, 58, 69, 56, 59, 57, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 81%|██████████████████████████████████████████████████████████████████████████████▉                   | 2277/2828 [06:36<02:09,  4.24it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 81%|███████████████████████████████████████████████████████████████████████████████                   | 2281/2828 [06:36<01:34,  5.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 8, 7: 9, 8: 11, 9: 10, 10: 12, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 6, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 20, 5, 6, 7, 9, 8, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 8, 7: 9, 8: 11, 9: 10, 10: 12, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 6, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 20, 5, 6, 7, 9, 8, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 81%|███████████████████████████████████████████████████████████████████████████████▏                  | 2284/2828 [06:37<01:44,  5.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 81%|███████████████████████████████████████████████████████████████████████████████▏                  | 2286/2828 [06:38<01:50,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 11, 7: 8, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 19, 5, 7, 8, 20, 6, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 11, 7: 8, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 19, 5, 7, 8, 20, 6, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 56, 55: 58, 56: 60, 57: 63, 58: 57, 59: 59, 60: 61, 61: 64, 62: 66, 63: 62, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 52, 53, 54, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 55, 54: 56, 55: 58, 56: 60, 57: 63, 58: 57, 59: 59, 60: 61, 61: 64, 62: 66, 63: 62, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 52, 53, 54, 58, 55, 59, 56, 60, 63, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 81%|███████████████████████████████████████████████████████████████████████████████▎                  | 2289/2828 [06:38<01:28,  6.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 81%|███████████████████████████████████████████████████████████████████████████████▍                  | 2291/2828 [06:38<01:12,  7.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 81%|███████████████████████████████████████████████████████████████████████████████▍                  | 2292/2828 [06:38<01:21,  6.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 81%|███████████████████████████████████████████████████████████████████████████████▌                  | 2296/2828 [06:39<01:11,  7.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 81%|███████████████████████████████████████████████████████████████████████████████▋                  | 2298/2828 [06:39<01:00,  8.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 81%|███████████████████████████████████████████████████████████████████████████████▋                  | 2300/2828 [06:39<00:55,  9.48it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 81%|███████████████████████████████████████████████████████████████████████████████▊                  | 2302/2828 [06:40<01:32,  5.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 81%|███████████████████████████████████████████████████████████████████████████████▊                  | 2303/2828 [06:40<01:40,  5.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 82%|███████████████████████████████████████████████████████████████████████████████▉                  | 2307/2828 [06:41<01:16,  6.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████                  | 2309/2828 [06:41<01:06,  7.77it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▏                 | 2313/2828 [06:41<00:52,  9.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 82%|████████████████████████████████████████████████████████████████████████████████▎                 | 2317/2828 [06:41<00:43, 11.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▎                 | 2319/2828 [06:42<00:43, 11.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▍                 | 2321/2828 [06:42<00:43, 11.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 17, 14: 19, 15: 15, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29, 71: 72}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57, 71]
[1, 2, 24, 25, 26, 27, 28, 29, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 17, 14: 19, 15: 15, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29, 71: 72}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57, 71]
[1, 2, 24, 25, 26, 27, 28, 29, 72]

 82%|████████████████████████████████████████████████████████████████████████████████▌                 | 2323/2828 [06:42<00:54,  9.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 8, 7: 11, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 8, 7: 11, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 105, 105: 108, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 100, 102, 104, 101, 103, 105, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 82%|████████████████████████████████████████████████████████████████████████████████▋                 | 2327/2828 [06:43<01:20,  6.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 82%|████████████████████████████████████████████████████████████████████████████████▋                 | 2328/2828 [06:43<01:28,  5.64it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 82%|████████████████████████████████████████████████████████████████████████████████▊                 | 2331/2828 [06:44<01:36,  5.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▊                 | 2333/2828 [06:44<01:17,  6.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 83%|████████████████████████████████████████████████████████████████████████████████▉                 | 2337/2828 [06:45<00:52,  9.32it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 83%|█████████████████████████████████████████████████████████████████████████████████                 | 2339/2828 [06:45<00:49,  9.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 16, 11: 18, 12: 14, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 9, 19: 12, 20: 7, 21: 10, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 2, 3, 4, 5, 20, 6, 18, 21, 7, 19, 8, 12, 9, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 16, 11: 18, 12: 14, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 9, 19: 12, 20: 7, 21: 10, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 2, 3, 4, 5, 20, 6, 18, 21, 7, 19, 8, 12, 9, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]

 83%|█████████████████████████████████████████████████████████████████████████████████                 | 2341/2828 [06:46<01:36,  5.06it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 83%|█████████████████████████████████████████████████████████████████████████████████▏                | 2342/2828 [06:46<01:37,  4.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 83%|█████████████████████████████████████████████████████████████████████████████████▏                | 2344/2828 [06:46<01:28,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 83%|█████████████████████████████████████████████████████████████████████████████████▎                | 2348/2828 [06:46<01:07,  7.07it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 83%|█████████████████████████████████████████████████████████████████████████████████▍                | 2350/2828 [06:47<00:59,  7.98it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 83%|█████████████████████████████████████████████████████████████████████████████████▍                | 2351/2828 [06:47<01:38,  4.84it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 83%|█████████████████████████████████████████████████████████████████████████████████▌                | 2354/2828 [06:48<01:35,  4.98it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 83%|█████████████████████████████████████████████████████████████████████████████████▋                | 2356/2828 [06:48<01:16,  6.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 60, 55: 63, 56: 65, 57: 61, 58: 64, 59: 68, 60: 70, 61: 69, 62: 71, 63: 57, 64: 59, 65: 62, 66: 66, 67: 67, 68: 53, 69: 55, 70: 56, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 70, 63, 53, 64, 54, 57, 65, 55, 58, 56, 66, 67, 59, 61, 60, 62, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 60, 55: 63, 56: 65, 57: 61, 58: 64, 59: 68, 60: 70, 61: 69, 62: 71, 63: 57, 64: 59, 65: 62, 66: 66, 67: 67, 68: 53, 69: 55, 70: 56, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 70, 63, 53, 64, 54, 57, 65, 55, 58, 56, 66, 67, 59, 61, 60, 62, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 83%|█████████████████████████████████████████████████████████████████████████████████▋                | 2357/2828 [06:48<01:24,  5.55it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 60, 56: 63, 57: 64, 58: 56, 59: 58, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 60, 55, 61, 64, 56, 57, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 60, 56: 63, 57: 64, 58: 56, 59: 58, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 60, 55, 61, 64, 56, 57, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 83%|█████████████████████████████████████████████████████████████████████████████████▋                | 2358/2828 [06:49<01:32,  5.07it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 83%|█████████████████████████████████████████████████████████████████████████████████▋                | 2359/2828 [06:49<02:13,  3.51it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 83%|█████████████████████████████████████████████████████████████████████████████████▊                | 2360/2828 [06:49<02:08,  3.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 83%|█████████████████████████████████████████████████████████████████████████████████▊                | 2361/2828 [06:50<02:05,  3.72it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 84%|█████████████████████████████████████████████████████████████████████████████████▊                | 2362/2828 [06:50<02:01,  3.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 84%|█████████████████████████████████████████████████████████████████████████████████▉                | 2364/2828 [06:50<01:42,  4.55it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|█████████████████████████████████████████████████████████████████████████████████▉                | 2366/2828 [06:51<01:57,  3.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|██████████████████████████████████████████████████████████████████████████████████                | 2369/2828 [06:52<01:44,  4.40it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|██████████████████████████████████████████████████████████████████████████████████▏               | 2372/2828 [06:52<01:40,  4.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 84%|██████████████████████████████████████████████████████████████████████████████████▎               | 2374/2828 [06:52<01:16,  5.96it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 8, 7: 11, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 8, 7: 11, 8: 9, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 6, 20: 4, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 20, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]

 84%|██████████████████████████████████████████████████████████████████████████████████▎               | 2375/2828 [06:53<01:18,  5.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 41, 35: 43, 36: 40, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 46, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|██████████████████████████████████████████████████████████████████████████████████▎               | 2377/2828 [06:53<01:40,  4.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|██████████████████████████████████████████████████████████████████████████████████▍               | 2379/2828 [06:54<01:56,  3.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 84%|██████████████████████████████████████████████████████████████████████████████████▍               | 2380/2828 [06:55<02:23,  3.13it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 7, 20: 11, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 8, 20, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 7, 20: 11, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 8, 20, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]

 84%|██████████████████████████████████████████████████████████████████████████████████▌               | 2382/2828 [06:55<01:51,  3.98it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 59, 57: 62, 58: 58, 59: 61, 60: 63, 61: 64, 62: 66, 63: 68, 64: 65, 65: 67, 66: 69, 67: 71, 68: 70, 69: 72, 70: 57, 71: 60, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 70, 58, 56, 71, 59, 57, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 54, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 59, 57: 62, 58: 58, 59: 61, 60: 63, 61: 64, 62: 66, 63: 68, 64: 65, 65: 67, 66: 69, 67: 71, 68: 70, 69: 72, 70: 57, 71: 60, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 70, 58, 56, 71, 59, 57, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 54, 73]

 84%|██████████████████████████████████████████████████████████████████████████████████▋               | 2385/2828 [06:55<01:22,  5.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 60, 55: 54, 56: 56, 57: 59, 58: 58, 59: 61, 60: 63, 61: 65, 62: 67, 63: 66, 64: 68, 65: 64, 66: 62, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 55, 52, 56, 53, 58, 57, 54, 59, 66, 60, 65, 61, 63, 62, 64, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 60, 55: 54, 56: 56, 57: 59, 58: 58, 59: 61, 60: 63, 61: 65, 62: 67, 63: 66, 64: 68, 65: 64, 66: 62, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 55, 52, 56, 53, 58, 57, 54, 59, 66, 60, 65, 61, 63, 62, 64, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▋               | 2387/2828 [06:56<01:16,  5.73it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 85%|██████████████████████████████████████████████████████████████████████████████████▊               | 2390/2828 [06:56<01:21,  5.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 85%|██████████████████████████████████████████████████████████████████████████████████▉               | 2394/2828 [06:56<00:51,  8.49it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 38, 35: 42, 36: 44, 37: 46, 38: 43, 39: 45, 40: 47, 41: 49, 42: 48, 43: 50, 44: 31, 45: 34, 46: 37, 47: 39, 48: 40, 49: 41}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 46, 34, 47, 48, 49, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 41, 37: 43, 38: 38, 39: 42, 40: 45, 41: 47, 42: 46, 43: 48, 44: 33, 45: 36, 46: 40, 47: 44, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 50, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 85%|███████████████████████████████████████████████████████████████████████████████████               | 2396/2828 [06:57<00:52,  8.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 7, 20: 11, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 8, 20, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 10, 9: 12, 10: 13, 11: 15, 12: 17, 13: 14, 14: 16, 15: 18, 16: 20, 17: 19, 18: 21, 19: 7, 20: 11, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 7, 8, 20, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 85%|███████████████████████████████████████████████████████████████████████████████████               | 2398/2828 [06:57<00:45,  9.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 85%|███████████████████████████████████████████████████████████████████████████████████▏              | 2402/2828 [06:57<00:44,  9.49it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 85%|███████████████████████████████████████████████████████████████████████████████████▎              | 2404/2828 [06:57<00:42, 10.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 19, 14: 18, 15: 15, 16: 17, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 19, 14: 18, 15: 15, 16: 17, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 85%|███████████████████████████████████████████████████████████████████████████████████▍              | 2406/2828 [06:58<00:48,  8.77it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 19, 14: 18, 15: 15, 16: 17, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 19, 14: 18, 15: 15, 16: 17, 17: 20, 18: 22, 19: 21, 20: 23, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 8, 9, 22, 7, 10, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 85%|███████████████████████████████████████████████████████████████████████████████████▍              | 2408/2828 [06:58<00:50,  8.32it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 85%|███████████████████████████████████████████████████████████████████████████████████▌              | 2410/2828 [06:58<00:54,  7.65it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 85%|███████████████████████████████████████████████████████████████████████████████████▌              | 2413/2828 [06:59<00:50,  8.23it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 47, 42: 45, 43: 48, 44: 33, 45: 36, 46: 39, 47: 43, 48: 46, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 44, 34, 50, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 48, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 47, 42: 45, 43: 48, 44: 33, 45: 36, 46: 39, 47: 43, 48: 46, 49: 32, 50: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 49, 44, 34, 50, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 48, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]

 85%|███████████████████████████████████████████████████████████████████████████████████▋              | 2414/2828 [06:59<00:59,  6.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]

 85%|███████████████████████████████████████████████████████████████████████████████████▋              | 2416/2828 [06:59<01:01,  6.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]

 86%|███████████████████████████████████████████████████████████████████████████████████▊              | 2419/2828 [07:00<01:07,  6.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 86%|███████████████████████████████████████████████████████████████████████████████████▊              | 2420/2828 [07:00<01:10,  5.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 86%|███████████████████████████████████████████████████████████████████████████████████▉              | 2421/2828 [07:00<01:17,  5.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 86%|███████████████████████████████████████████████████████████████████████████████████▉              | 2423/2828 [07:01<01:39,  4.09it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 86%|████████████████████████████████████████████████████████████████████████████████████              | 2424/2828 [07:02<02:08,  3.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 54, 55: 56, 56: 59, 57: 62, 58: 64, 59: 61, 60: 58, 61: 60, 62: 63, 63: 65, 64: 67, 65: 68, 66: 66, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 54, 52, 55, 53, 60, 56, 61, 59, 57, 62, 58, 63, 66, 64, 65, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 54, 55: 56, 56: 59, 57: 62, 58: 64, 59: 61, 60: 58, 61: 60, 62: 63, 63: 65, 64: 67, 65: 68, 66: 66, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 54, 52, 55, 53, 60, 56, 61, 59, 57, 62, 58, 63, 66, 64, 65, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████              | 2426/2828 [07:02<01:44,  3.84it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 86%|████████████████████████████████████████████████████████████████████████████████████              | 2427/2828 [07:02<02:10,  3.07it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 24, 21: 25, 22: 7, 23: 10, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31, 73: 74}
[0, 1, 2, 24, 3, 4, 22, 15, 5, 23, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 20, 21, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59, 73]
[1, 2, 26, 27, 28, 29, 30, 31, 74]

 86%|████████████████████████████████████████████████████████████████████████████████████▏             | 2430/2828 [07:03<01:26,  4.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 86%|████████████████████████████████████████████████████████████████████████████████████▏             | 2431/2828 [07:03<01:57,  3.36it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 86%|████████████████████████████████████████████████████████████████████████████████████▎             | 2434/2828 [07:04<01:36,  4.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 86%|████████████████████████████████████████████████████████████████████████████████████▍             | 2438/2828 [07:04<00:52,  7.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 86%|████████████████████████████████████████████████████████████████████████████████████▌             | 2440/2828 [07:05<00:46,  8.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 86%|████████████████████████████████████████████████████████████████████████████████████▋             | 2443/2828 [07:05<01:05,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 86%|████████████████████████████████████████████████████████████████████████████████████▋             | 2445/2828 [07:05<00:53,  7.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]

 86%|████████████████████████████████████████████████████████████████████████████████████▊             | 2446/2828 [07:06<01:03,  6.04it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]

 87%|████████████████████████████████████████████████████████████████████████████████████▊             | 2449/2828 [07:06<00:54,  6.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 87%|█████████████████████████████████████████████████████████████████████████████████████             | 2453/2828 [07:06<00:38,  9.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 87%|█████████████████████████████████████████████████████████████████████████████████████             | 2455/2828 [07:06<00:32, 11.41it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 87%|█████████████████████████████████████████████████████████████████████████████████████▏            | 2457/2828 [07:07<00:31, 11.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 87%|█████████████████████████████████████████████████████████████████████████████████████▏            | 2459/2828 [07:07<00:40,  9.15it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 61, 56: 55, 57: 58, 58: 62, 59: 65, 60: 66, 61: 56, 62: 59, 63: 63, 64: 67, 65: 69, 66: 64, 67: 68, 68: 70, 69: 72, 70: 71, 71: 73, 72: 53, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 72, 52, 56, 61, 53, 57, 62, 54, 55, 58, 63, 66, 59, 60, 64, 67, 65, 68, 70, 69, 71, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 74, 75]

 87%|█████████████████████████████████████████████████████████████████████████████████████▎            | 2463/2828 [07:08<00:47,  7.64it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 87%|█████████████████████████████████████████████████████████████████████████████████████▍            | 2465/2828 [07:08<00:51,  6.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 87%|█████████████████████████████████████████████████████████████████████████████████████▌            | 2468/2828 [07:08<00:47,  7.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 87%|█████████████████████████████████████████████████████████████████████████████████████▌            | 2470/2828 [07:09<00:48,  7.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 20, 12: 22, 13: 21, 14: 23, 15: 7, 16: 10, 17: 13, 18: 17, 19: 18, 20: 19, 21: 5, 22: 8, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 21, 4, 15, 22, 5, 16, 6, 9, 17, 7, 10, 8, 18, 19, 20, 11, 13, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 87%|█████████████████████████████████████████████████████████████████████████████████████▋            | 2472/2828 [07:09<00:48,  7.40it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|█████████████████████████████████████████████████████████████████████████████████████▊            | 2475/2828 [07:09<00:43,  8.15it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 44, 41: 46, 42: 45, 43: 47, 44: 33, 45: 36, 46: 39, 47: 43, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 44, 34, 49, 45, 35, 38, 46, 36, 39, 37, 47, 40, 42, 41, 43, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 35, 36: 34, 37: 37, 38: 39, 39: 36, 40: 38, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 50, 36, 35, 39, 37, 40, 38, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 35, 36: 34, 37: 37, 38: 39, 39: 36, 40: 38, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 50, 36, 35, 39, 37, 40, 38, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 66, 58: 69, 59: 70, 60: 71, 61: 57, 62: 54, 63: 58, 64: 60, 65: 63, 66: 65, 67: 61, 68: 64, 69: 67, 70: 72, 71: 68, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 62, 53, 54, 61, 63, 55, 64, 67, 56, 65, 68, 66, 57, 69, 71, 58, 59, 60, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 88%|█████████████████████████████████████████████████████████████████████████████████████▊            | 2476/2828 [07:10<00:52,  6.68it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 88%|█████████████████████████████████████████████████████████████████████████████████████▊            | 2478/2828 [07:10<01:12,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 88%|█████████████████████████████████████████████████████████████████████████████████████▉            | 2479/2828 [07:11<01:37,  3.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 88%|█████████████████████████████████████████████████████████████████████████████████████▉            | 2481/2828 [07:11<01:20,  4.32it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 88%|██████████████████████████████████████████████████████████████████████████████████████            | 2482/2828 [07:11<01:18,  4.40it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 88%|██████████████████████████████████████████████████████████████████████████████████████            | 2485/2828 [07:12<00:58,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 88%|██████████████████████████████████████████████████████████████████████████████████████▏           | 2487/2828 [07:12<00:47,  7.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 62, 56: 64, 57: 60, 58: 63, 59: 66, 60: 68, 61: 69, 62: 67, 63: 70, 64: 56, 65: 58, 66: 61, 67: 65, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 65, 54, 57, 66, 55, 58, 56, 67, 59, 62, 60, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 62, 56: 64, 57: 60, 58: 63, 59: 66, 60: 68, 61: 69, 62: 67, 63: 70, 64: 56, 65: 58, 66: 61, 67: 65, 68: 53, 69: 55, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 69, 64, 53, 65, 54, 57, 66, 55, 58, 56, 67, 59, 62, 60, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 88%|██████████████████████████████████████████████████████████████████████████████████████▎           | 2491/2828 [07:12<00:42,  7.98it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|██████████████████████████████████████████████████████████████████████████████████████▎           | 2492/2828 [07:13<00:49,  6.79it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 61, 55: 62, 56: 55, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 56, 59, 53, 57, 58, 60, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 61, 55: 62, 56: 55, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 56, 59, 53, 57, 58, 60, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 88%|██████████████████████████████████████████████████████████████████████████████████████▍           | 2493/2828 [07:13<00:57,  5.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|██████████████████████████████████████████████████████████████████████████████████████▍           | 2496/2828 [07:13<00:58,  5.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 88%|██████████████████████████████████████████████████████████████████████████████████████▌           | 2498/2828 [07:13<00:46,  7.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 88%|██████████████████████████████████████████████████████████████████████████████████████▋           | 2500/2828 [07:14<00:40,  8.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]

 89%|██████████████████████████████████████████████████████████████████████████████████████▊           | 2504/2828 [07:14<00:28, 11.38it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 34, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 38, 45: 33, 46: 36}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 45, 32, 43, 46, 33, 44, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 89%|██████████████████████████████████████████████████████████████████████████████████████▊           | 2506/2828 [07:15<00:52,  6.16it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 89%|██████████████████████████████████████████████████████████████████████████████████████▉           | 2507/2828 [07:15<00:54,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 89%|██████████████████████████████████████████████████████████████████████████████████████▉           | 2509/2828 [07:15<00:51,  6.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 89%|███████████████████████████████████████████████████████████████████████████████████████           | 2513/2828 [07:16<00:42,  7.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 89%|███████████████████████████████████████████████████████████████████████████████████████▏          | 2515/2828 [07:16<00:35,  8.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 20, 15: 18, 16: 21, 17: 9, 18: 11, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 18, 7, 10, 8, 11, 9, 12, 15, 13, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 20, 15: 18, 16: 21, 17: 9, 18: 11, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 18, 7, 10, 8, 11, 9, 12, 15, 13, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 89%|███████████████████████████████████████████████████████████████████████████████████████▎          | 2519/2828 [07:16<00:44,  6.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 89%|███████████████████████████████████████████████████████████████████████████████████████▎          | 2521/2828 [07:17<00:38,  7.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 89%|███████████████████████████████████████████████████████████████████████████████████████▌          | 2525/2828 [07:17<00:33,  8.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 89%|███████████████████████████████████████████████████████████████████████████████████████▋          | 2529/2828 [07:17<00:26, 11.45it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 90%|███████████████████████████████████████████████████████████████████████████████████████▊          | 2533/2828 [07:18<00:23, 12.49it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 8, 7: 12, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 22, 14: 24, 15: 23, 16: 25, 17: 11, 18: 7, 19: 10, 20: 13, 21: 16, 22: 20, 23: 21, 24: 4, 25: 26, 26: 32, 27: 33, 28: 34, 29: 27, 30: 28, 31: 29, 32: 30, 33: 35, 34: 36, 35: 38, 36: 41, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 56, 50: 59, 51: 61, 52: 64, 53: 66, 54: 62, 55: 65, 56: 70, 57: 72, 58: 71, 59: 73, 60: 57, 61: 60, 62: 63, 63: 67, 64: 68, 65: 69, 66: 55, 67: 58, 68: 39, 69: 42, 70: 37, 71: 40, 72: 31}
[0, 1, 2, 24, 3, 4, 18, 6, 5, 19, 17, 7, 20, 8, 11, 21, 9, 12, 10, 22, 23, 13, 15, 14, 16, 25, 29, 30, 31, 32, 72, 26, 27, 28, 33, 34, 70, 35, 68, 71, 36, 69, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 66, 49, 60, 67, 50, 61, 51, 54, 62, 52, 55, 53, 63, 64, 65, 56, 58, 57, 59]
[1, 2, 26, 27, 28, 29, 30, 31]

 90%|███████████████████████████████████████████████████████████████████████████████████████▊          | 2535/2828 [07:18<00:29,  9.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 90%|███████████████████████████████████████████████████████████████████████████████████████▉          | 2537/2828 [07:19<00:48,  5.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 67, 62: 65, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 57, 55, 58, 56, 59, 62, 60, 61, 63, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 67, 62: 65, 63: 68, 64: 56, 65: 58, 66: 53, 67: 55, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 65, 54, 57, 55, 58, 56, 59, 62, 60, 61, 63, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 72]

 90%|███████████████████████████████████████████████████████████████████████████████████████▉          | 2538/2828 [07:19<00:52,  5.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 16, 11: 10, 12: 7, 13: 11, 14: 13, 15: 17, 16: 19, 17: 14, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 12, 6, 7, 11, 13, 8, 14, 17, 9, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 16, 11: 10, 12: 7, 13: 11, 14: 13, 15: 17, 16: 19, 17: 14, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 12, 6, 7, 11, 13, 8, 14, 17, 9, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 90%|████████████████████████████████████████████████████████████████████████████████████████          | 2540/2828 [07:19<00:48,  5.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 90%|████████████████████████████████████████████████████████████████████████████████████████          | 2542/2828 [07:19<00:48,  5.87it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 61, 56: 64, 57: 65, 58: 66, 59: 56, 60: 57, 61: 60, 62: 62, 63: 67, 64: 69, 65: 63, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 54, 72: 58, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 71, 53, 59, 60, 72, 54, 61, 55, 62, 65, 56, 57, 58, 63, 66, 64, 67, 69, 68, 70, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 90%|████████████████████████████████████████████████████████████████████████████████████████▎         | 2547/2828 [07:20<00:34,  8.15it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]

 90%|████████████████████████████████████████████████████████████████████████████████████████▍         | 2551/2828 [07:20<00:31,  8.70it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 48, 46: 49, 47: 31, 48: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 47, 40, 30, 48, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39, 45, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 90%|████████████████████████████████████████████████████████████████████████████████████████▍         | 2553/2828 [07:20<00:28,  9.76it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 16, 9: 18, 10: 13, 11: 17, 12: 20, 13: 22, 14: 21, 15: 23, 16: 9, 17: 10, 18: 14, 19: 15, 20: 19, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 16, 17, 22, 7, 10, 18, 19, 8, 11, 9, 20, 12, 14, 13, 15, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 16, 9: 18, 10: 13, 11: 17, 12: 20, 13: 22, 14: 21, 15: 23, 16: 9, 17: 10, 18: 14, 19: 15, 20: 19, 21: 7, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 21, 6, 16, 17, 22, 7, 10, 18, 19, 8, 11, 9, 20, 12, 14, 13, 15, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 90%|████████████████████████████████████████████████████████████████████████████████████████▌         | 2557/2828 [07:21<00:32,  8.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 35, 38: 38, 39: 36, 40: 39, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 50, 35, 37, 39, 36, 38, 40, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 35, 38: 38, 39: 36, 40: 39, 41: 40, 42: 42, 43: 44, 44: 41, 45: 43, 46: 45, 47: 47, 48: 46, 49: 48, 50: 33}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 50, 35, 37, 39, 36, 38, 40, 41, 44, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 91%|████████████████████████████████████████████████████████████████████████████████████████▋         | 2561/2828 [07:21<00:25, 10.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 91%|████████████████████████████████████████████████████████████████████████████████████████▊         | 2563/2828 [07:22<00:23, 11.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 91%|████████████████████████████████████████████████████████████████████████████████████████▉         | 2565/2828 [07:22<00:20, 12.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 91%|████████████████████████████████████████████████████████████████████████████████████████▉         | 2567/2828 [07:22<00:27,  9.48it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████         | 2569/2828 [07:22<00:38,  6.71it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 64, 56: 66, 57: 61, 58: 65, 59: 67, 60: 69, 61: 68, 62: 70, 63: 56, 64: 53, 65: 55, 66: 58, 67: 62, 68: 63, 69: 59, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 63, 53, 66, 69, 54, 57, 67, 68, 55, 58, 56, 59, 61, 60, 62, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▏        | 2572/2828 [07:23<00:33,  7.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▎        | 2576/2828 [07:23<00:23, 10.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 42, 39: 44, 40: 40, 41: 43, 42: 45, 43: 47, 44: 46, 45: 48, 46: 36, 47: 32, 48: 35, 49: 38, 50: 41}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 50, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 42, 39: 44, 40: 40, 41: 43, 42: 45, 43: 47, 44: 46, 45: 48, 46: 36, 47: 32, 48: 35, 49: 38, 50: 41}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 50, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▍        | 2580/2828 [07:23<00:19, 12.96it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▍        | 2582/2828 [07:23<00:18, 13.11it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 9, 6: 4, 7: 6, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 7, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 6, 3, 7, 21, 4, 5, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 9, 6: 4, 7: 6, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 7, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 6, 3, 7, 21, 4, 5, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▌        | 2584/2828 [07:24<00:41,  5.92it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 9, 6: 4, 7: 6, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 7, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 6, 3, 7, 21, 4, 5, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 8, 5: 9, 6: 4, 7: 6, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 7, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 6, 3, 7, 21, 4, 5, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▌        | 2586/2828 [07:25<00:39,  6.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 13, 9: 16, 10: 10, 11: 7, 12: 11, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 13, 8, 14, 17, 9, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 13, 9: 16, 10: 10, 11: 7, 12: 11, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 13, 8, 14, 17, 9, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▊        | 2590/2828 [07:25<00:31,  7.61it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 33, 35: 35, 36: 36, 37: 38, 38: 41, 39: 43, 40: 39, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 37, 47: 40, 48: 32, 49: 34}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 49, 35, 36, 46, 37, 40, 47, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 18, 10: 20, 11: 19, 12: 21, 13: 15, 14: 17, 15: 13, 16: 16, 17: 9, 18: 11, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 18, 7, 15, 8, 13, 16, 14, 9, 11, 10, 12, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 18, 10: 20, 11: 19, 12: 21, 13: 15, 14: 17, 15: 13, 16: 16, 17: 9, 18: 11, 19: 6, 20: 8, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 19, 5, 20, 17, 6, 18, 7, 15, 8, 13, 16, 14, 9, 11, 10, 12, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▊        | 2592/2828 [07:26<00:44,  5.25it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▉        | 2595/2828 [07:26<00:37,  6.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▉        | 2597/2828 [07:26<00:29,  7.71it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 33, 35: 37, 36: 34, 37: 38, 38: 40, 39: 42, 40: 44, 41: 41, 42: 43, 43: 45, 44: 47, 45: 46, 46: 48, 47: 36, 48: 32, 49: 35, 50: 39}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 34, 36, 49, 47, 35, 37, 50, 38, 41, 39, 42, 40, 43, 45, 44, 46, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|██████████████████████████████████████████████████████████████████████████████████████████        | 2599/2828 [07:26<00:31,  7.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 13, 8: 16, 9: 18, 10: 14, 11: 17, 12: 20, 13: 22, 14: 21, 15: 23, 16: 9, 17: 10, 18: 15, 19: 19, 20: 7, 21: 11, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 20, 6, 16, 17, 21, 22, 7, 10, 18, 8, 11, 9, 19, 12, 14, 13, 15, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 13, 8: 16, 9: 18, 10: 14, 11: 17, 12: 20, 13: 22, 14: 21, 15: 23, 16: 9, 17: 10, 18: 15, 19: 19, 20: 7, 21: 11, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 20, 6, 16, 17, 21, 22, 7, 10, 18, 8, 11, 9, 19, 12, 14, 13, 15, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▏       | 2601/2828 [07:27<00:31,  7.15it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 63, 56: 65, 57: 61, 58: 64, 59: 66, 60: 68, 61: 69, 62: 67, 63: 70, 64: 56, 65: 59, 66: 53, 67: 55, 68: 58, 69: 62, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 57, 69, 55, 58, 56, 59, 62, 60, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 60, 55: 63, 56: 65, 57: 61, 58: 64, 59: 66, 60: 68, 61: 69, 62: 67, 63: 70, 64: 56, 65: 59, 66: 53, 67: 55, 68: 58, 69: 62, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 67, 64, 53, 68, 65, 54, 57, 69, 55, 58, 56, 59, 62, 60, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▏       | 2602/2828 [07:27<00:36,  6.24it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 64, 56, 61, 65, 63, 62, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 64, 56, 61, 65, 63, 62, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▎       | 2605/2828 [07:27<00:29,  7.49it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 37, 45, 32, 38, 35, 33, 39, 36, 34]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▎       | 2607/2828 [07:28<00:24,  8.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 23, 23: 24, 24: 28, 25: 29, 26: 30, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27, 69: 70, 70: 76, 71: 77, 72: 78, 73: 71, 74: 72, 75: 73, 76: 74, 77: 79, 78: 80, 79: 82, 80: 85, 81: 87, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 100, 94: 103, 95: 105, 96: 108, 97: 110, 98: 106, 99: 109, 100: 114, 101: 116, 102: 115, 103: 117, 104: 101, 105: 104, 106: 107, 107: 111, 108: 112, 109: 113, 110: 99, 111: 102, 112: 83, 113: 86, 114: 81, 115: 84, 116: 75, 117: 118}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 22, 23, 27, 28, 68, 24, 25, 26, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55, 69, 73, 74, 75, 76, 116, 70, 71, 72, 77, 78, 114, 79, 112, 115, 80, 113, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 110, 93, 104, 111, 94, 105, 95, 98, 106, 96, 99, 97, 107, 108, 109, 100, 102, 101, 103, 117]
[1, 22, 23, 24, 25, 26, 27, 70, 71, 72, 73, 74, 75, 118]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▍       | 2609/2828 [07:28<00:40,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 10, 10: 7, 11: 11, 12: 13, 13: 15, 14: 17, 15: 14, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 10, 6, 7, 9, 11, 8, 12, 15, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 10, 10: 7, 11: 11, 12: 13, 13: 15, 14: 17, 15: 14, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 10, 6, 7, 9, 11, 8, 12, 15, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▍       | 2611/2828 [07:29<00:41,  5.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 10, 10: 7, 11: 11, 12: 13, 13: 15, 14: 17, 15: 14, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 10, 6, 7, 9, 11, 8, 12, 15, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 10, 10: 7, 11: 11, 12: 13, 13: 15, 14: 17, 15: 14, 16: 16, 17: 18, 18: 20, 19: 19, 20: 21, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 10, 6, 7, 9, 11, 8, 12, 15, 13, 16, 14, 17, 19, 18, 20, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▌       | 2613/2828 [07:29<00:29,  7.19it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▌       | 2614/2828 [07:29<00:34,  6.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 57, 64: 53, 65: 55, 66: 56, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 57, 64: 53, 65: 55, 66: 56, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▋       | 2617/2828 [07:29<00:27,  7.68it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 43, 37: 45, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 36, 33, 37, 34, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▊       | 2619/2828 [07:30<00:40,  5.13it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▊       | 2621/2828 [07:30<00:36,  5.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▉       | 2623/2828 [07:30<00:32,  6.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 17, 12: 19, 13: 15, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 10, 20: 13, 21: 8, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 19, 22, 8, 20, 9, 13, 10, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 17, 12: 19, 13: 15, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 10, 20: 13, 21: 8, 22: 11, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 19, 22, 8, 20, 9, 13, 10, 11, 14, 12, 15, 17, 16, 18, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▉       | 2625/2828 [07:31<00:29,  6.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 93%|███████████████████████████████████████████████████████████████████████████████████████████       | 2627/2828 [07:31<00:40,  5.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 57, 64: 53, 65: 55, 66: 56, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 58, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 57, 64: 53, 65: 55, 66: 56, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 64, 52, 65, 66, 63, 53, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▏      | 2631/2828 [07:32<00:31,  6.31it/s]

{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▏      | 2633/2828 [07:32<00:26,  7.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▎      | 2635/2828 [07:32<00:21,  8.85it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 11, 6: 12, 7: 13, 8: 6, 9: 7, 10: 8, 11: 9, 12: 14, 13: 15, 14: 17, 15: 20, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 33, 28: 35, 29: 38, 30: 40, 31: 43, 32: 45, 33: 41, 34: 44, 35: 49, 36: 51, 37: 50, 38: 52, 39: 36, 40: 39, 41: 42, 42: 46, 43: 47, 44: 48, 45: 34, 46: 37, 47: 18, 48: 21, 49: 16, 50: 19, 51: 10}
[0, 1, 2, 3, 4, 8, 9, 10, 11, 51, 5, 6, 7, 12, 13, 49, 14, 47, 50, 15, 48, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 45, 28, 39, 46, 29, 40, 30, 33, 41, 31, 34, 32, 42, 43, 44, 35, 37, 36, 38]
[1, 2, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▍      | 2637/2828 [07:32<00:26,  7.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▍      | 2638/2828 [07:33<00:30,  6.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▍      | 2640/2828 [07:33<00:37,  4.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▌      | 2642/2828 [07:34<00:33,  5.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▌      | 2643/2828 [07:34<00:36,  5.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▋      | 2646/2828 [07:34<00:27,  6.58it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▋      | 2647/2828 [07:34<00:31,  5.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▊      | 2648/2828 [07:35<00:44,  4.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▉      | 2652/2828 [07:36<00:31,  5.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 10, 7: 11, 8: 12, 9: 7, 10: 8, 11: 13, 12: 14, 13: 16, 14: 19, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 30, 25: 31, 26: 32, 27: 34, 28: 37, 29: 39, 30: 42, 31: 44, 32: 40, 33: 43, 34: 48, 35: 50, 36: 49, 37: 51, 38: 35, 39: 38, 40: 41, 41: 45, 42: 46, 43: 47, 44: 33, 45: 36, 46: 17, 47: 20, 48: 15, 49: 18, 50: 9, 51: 52, 52: 58, 53: 59, 54: 60, 55: 53, 56: 54, 57: 55, 58: 56, 59: 61, 60: 62, 61: 64, 62: 67, 63: 69, 64: 70, 65: 71, 66: 72, 67: 73, 68: 74, 69: 75, 70: 76, 71: 77, 72: 78, 73: 79, 74: 80, 75: 82, 76: 85, 77: 87, 78: 90, 79: 92, 80: 88, 81: 91, 82: 96, 83: 98, 84: 97, 85: 99, 86: 83, 87: 86, 88: 89, 89: 93, 90: 94, 91: 95, 92: 81, 93: 84, 94: 65, 95: 68, 96: 63, 97: 66, 98: 57, 99: 100}
[0, 1, 2, 3, 4, 5, 9, 10, 50, 6, 7, 8, 11, 12, 48, 13, 46, 49, 14, 47, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 44, 27, 38, 45, 28, 39, 29, 32, 40, 30, 33, 31, 41, 42, 43, 34, 36, 35, 37, 51, 55, 56, 57, 58, 98, 52, 53, 54, 59, 60, 96, 61, 94, 97, 62, 95, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 92, 75, 86, 93, 76, 87, 77, 80, 88, 78, 81, 79, 89, 90, 91, 82, 84, 83, 85, 99]
[1, 4, 5, 6, 7, 8, 9, 52, 53, 54, 55, 56, 57, 100]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▉      | 2653/2828 [07:36<00:42,  4.16it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 60, 55: 54, 56: 56, 57: 59, 58: 63, 59: 67, 60: 68, 61: 66, 62: 62, 63: 58, 64: 61, 65: 65, 66: 64, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 53, 52: 55, 53: 57, 54: 60, 55: 54, 56: 56, 57: 59, 58: 63, 59: 67, 60: 68, 61: 66, 62: 62, 63: 58, 64: 61, 65: 65, 66: 64, 67: 52, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 67, 51, 55, 52, 56, 53, 63, 57, 54, 64, 62, 58, 66, 65, 61, 59, 60, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 94%|████████████████████████████████████████████████████████████████████████████████████████████      | 2655/2828 [07:36<00:35,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 94%|████████████████████████████████████████████████████████████████████████████████████████████      | 2658/2828 [07:37<00:34,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 7, 21: 10, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 20, 15, 5, 21, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 7, 21: 10, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 20, 15, 5, 21, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▏     | 2660/2828 [07:37<00:34,  4.91it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 7, 21: 10, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 20, 15, 5, 21, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 15, 8: 17, 9: 13, 10: 16, 11: 19, 12: 22, 13: 20, 14: 23, 15: 8, 16: 11, 17: 14, 18: 18, 19: 21, 20: 7, 21: 10, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 20, 15, 5, 21, 16, 6, 9, 17, 7, 10, 8, 18, 11, 13, 19, 12, 14, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▎     | 2664/2828 [07:38<00:19,  8.35it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▍     | 2666/2828 [07:38<00:21,  7.54it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 67, 60: 69, 61: 63, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 66, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 72, 59, 62, 60, 63, 65, 64, 66, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 74]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▌     | 2670/2828 [07:38<00:17,  8.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 66, 61: 65, 62: 62, 63: 64, 64: 67, 65: 69, 66: 68, 67: 70, 68: 54, 69: 58, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 55, 56, 69, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 66, 61: 65, 62: 62, 63: 64, 64: 67, 65: 69, 66: 68, 67: 70, 68: 54, 69: 58, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 68, 53, 55, 56, 69, 54, 57, 58, 62, 59, 63, 61, 60, 64, 66, 65, 67, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 71]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▋     | 2674/2828 [07:39<00:16,  9.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▋     | 2676/2828 [07:39<00:17,  8.64it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 36, 35: 39, 36: 42, 37: 37, 38: 34, 39: 38, 40: 40, 41: 43, 42: 45, 43: 41, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 38, 33, 34, 37, 39, 35, 40, 43, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▊     | 2680/2828 [07:40<00:19,  7.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████     | 2684/2828 [07:40<00:14, 10.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 35, 34: 39, 35: 36, 36: 37, 37: 40, 38: 41, 39: 43, 40: 45, 41: 42, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 47, 33, 35, 36, 48, 34, 37, 38, 41, 39, 42, 40, 43, 45, 44, 46]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████     | 2686/2828 [07:40<00:16,  8.62it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▏    | 2688/2828 [07:41<00:22,  6.36it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▏    | 2689/2828 [07:41<00:24,  5.72it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▏    | 2690/2828 [07:41<00:26,  5.28it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 2691/2828 [07:42<00:27,  4.94it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 2692/2828 [07:42<00:29,  4.68it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 56, 58: 58, 59: 60, 60: 63, 61: 65, 62: 61, 63: 64, 64: 66, 65: 68, 66: 67, 67: 69, 68: 53, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 53, 52, 57, 54, 58, 55, 59, 62, 56, 60, 63, 61, 64, 66, 65, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 70, 71]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 2693/2828 [07:42<00:30,  4.48it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 65, 60: 56, 61: 59, 62: 61, 63: 66, 64: 68, 65: 62, 66: 67, 67: 69, 68: 71, 69: 70, 70: 72, 71: 53, 72: 73, 73: 74}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 71, 52, 54, 60, 53, 55, 61, 56, 62, 65, 57, 58, 59, 63, 66, 64, 67, 69, 68, 70, 72, 73]
[1, 2, 3, 4, 5, 6, 49, 50, 73, 74]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▍    | 2696/2828 [07:43<00:21,  6.13it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▍    | 2698/2828 [07:43<00:21,  6.06it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▌    | 2701/2828 [07:43<00:17,  7.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 8, 9: 10, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 5, 4, 8, 6, 9, 7, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 8, 9: 10, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 5, 4, 8, 6, 9, 7, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▋    | 2702/2828 [07:44<00:19,  6.54it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▊    | 2706/2828 [07:44<00:15,  8.06it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▊    | 2708/2828 [07:44<00:13,  8.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▉    | 2711/2828 [07:45<00:18,  6.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████    | 2713/2828 [07:45<00:15,  7.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████    | 2714/2828 [07:46<00:24,  4.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████    | 2716/2828 [07:46<00:30,  3.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 8, 9: 10, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 5, 4, 8, 6, 9, 7, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 8, 9: 10, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 27, 22: 28, 23: 29, 24: 22, 25: 23, 26: 24, 27: 25, 28: 30, 29: 31, 30: 33, 31: 36, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 51, 45: 54, 46: 56, 47: 59, 48: 61, 49: 57, 50: 60, 51: 65, 52: 67, 53: 66, 54: 68, 55: 52, 56: 55, 57: 58, 58: 62, 59: 63, 60: 64, 61: 50, 62: 53, 63: 34, 64: 37, 65: 32, 66: 35, 67: 26}
[0, 1, 2, 3, 19, 5, 4, 8, 6, 9, 7, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 24, 25, 26, 27, 67, 21, 22, 23, 28, 29, 65, 30, 63, 66, 31, 64, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 61, 44, 55, 62, 45, 56, 46, 49, 57, 47, 50, 48, 58, 59, 60, 51, 53, 52, 54]
[1, 2, 21, 22, 23, 24, 25, 26]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▎   | 2720/2828 [07:47<00:15,  7.04it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 39, 34: 44, 35: 46, 36: 40, 37: 45, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 38, 44: 32, 45: 34, 46: 37, 47: 41, 48: 42, 49: 43}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 46, 43, 33, 36, 47, 48, 49, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▎   | 2722/2828 [07:47<00:12,  8.75it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 42, 39: 44, 40: 40, 41: 43, 42: 45, 43: 47, 44: 46, 45: 48, 46: 36, 47: 32, 48: 35, 49: 38, 50: 41}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 50, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 49, 30: 50, 31: 51, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 39, 38: 42, 39: 44, 40: 40, 41: 43, 42: 45, 43: 47, 44: 46, 45: 48, 46: 36, 47: 32, 48: 35, 49: 38, 50: 41}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 47, 35, 34, 48, 46, 36, 49, 37, 40, 50, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▍   | 2724/2828 [07:47<00:10,  9.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 52, 71]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70, 70: 71}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69, 70]
[1, 2, 3, 4, 5, 6, 49, 50, 52, 71]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▍   | 2726/2828 [07:47<00:12,  8.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 54, 67: 57, 68: 60, 69: 63, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 68, 55, 58, 69, 56, 59, 57, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 61, 56: 64, 57: 66, 58: 62, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 56, 65: 59, 66: 54, 67: 57, 68: 60, 69: 63, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 68, 55, 58, 69, 56, 59, 57, 60, 62, 61, 63, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▌   | 2730/2828 [07:48<00:10,  9.11it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 47, 39: 49, 40: 48, 41: 50, 42: 35, 43: 37, 44: 40, 45: 44, 46: 45, 47: 46, 48: 32, 49: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 31, 49, 42, 32, 43, 33, 36, 44, 34, 37, 35, 45, 46, 47, 38, 40, 39, 41]
[1, 27, 28]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▋   | 2732/2828 [07:48<00:09, 10.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▋   | 2734/2828 [07:48<00:12,  7.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▊   | 2735/2828 [07:49<00:14,  6.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▉   | 2738/2828 [07:49<00:14,  6.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▉   | 2740/2828 [07:50<00:20,  4.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████   | 2743/2828 [07:50<00:17,  4.75it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 46, 39: 48, 40: 47, 41: 49, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40, 47: 44, 48: 45}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 47, 48, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████   | 2745/2828 [07:51<00:13,  6.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 26, 21: 27, 22: 28, 23: 21, 24: 22, 25: 23, 26: 24, 27: 29, 28: 30, 29: 32, 30: 35, 31: 37, 32: 38, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 50, 44: 53, 45: 55, 46: 58, 47: 60, 48: 56, 49: 59, 50: 64, 51: 66, 52: 65, 53: 67, 54: 51, 55: 54, 56: 57, 57: 61, 58: 62, 59: 63, 60: 49, 61: 52, 62: 33, 63: 36, 64: 31, 65: 34, 66: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 23, 24, 25, 26, 66, 20, 21, 22, 27, 28, 64, 29, 62, 65, 30, 63, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 60, 43, 54, 61, 44, 55, 45, 48, 56, 46, 49, 47, 57, 58, 59, 50, 52, 51, 53]
[1, 2, 20, 21, 22, 23, 24, 25]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▏  | 2747/2828 [07:51<00:12,  6.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▎  | 2750/2828 [07:52<00:13,  5.91it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 41, 36: 42, 37: 35, 38: 37, 39: 39, 40: 43, 41: 45, 42: 40, 43: 44, 44: 46, 45: 48, 46: 47, 47: 49, 48: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 48, 32, 31, 37, 33, 38, 34, 39, 42, 35, 36, 40, 43, 41, 44, 46, 45, 47]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▎  | 2752/2828 [07:52<00:10,  7.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 11, 8: 13, 9: 15, 10: 17, 11: 14, 12: 16, 13: 18, 14: 20, 15: 19, 16: 21, 17: 9, 18: 12, 19: 7, 20: 10, 21: 22, 22: 28, 23: 29, 24: 30, 25: 23, 26: 24, 27: 25, 28: 26, 29: 31, 30: 32, 31: 34, 32: 37, 33: 39, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 52, 46: 55, 47: 57, 48: 60, 49: 62, 50: 58, 51: 61, 52: 66, 53: 68, 54: 67, 55: 69, 56: 53, 57: 56, 58: 59, 59: 63, 60: 64, 61: 65, 62: 51, 63: 54, 64: 35, 65: 38, 66: 33, 67: 36, 68: 27}
[0, 1, 2, 3, 4, 5, 19, 6, 17, 20, 7, 18, 8, 11, 9, 12, 10, 13, 15, 14, 16, 21, 25, 26, 27, 28, 68, 22, 23, 24, 29, 30, 66, 31, 64, 67, 32, 65, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 62, 45, 56, 63, 46, 57, 47, 50, 58, 48, 51, 49, 59, 60, 61, 52, 54, 53, 55]
[1, 2, 22, 23, 24, 25, 26, 27]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▌  | 2756/2828 [07:52<00:08,  8.90it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▌  | 2758/2828 [07:53<00:12,  5.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 2760/2828 [07:53<00:14,  4.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 2761/2828 [07:54<00:19,  3.52it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 61, 55: 62, 56: 55, 57: 58, 58: 56, 59: 59, 60: 60, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 56, 58, 53, 57, 59, 60, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 61, 55: 62, 56: 55, 57: 58, 58: 56, 59: 59, 60: 60, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 56, 58, 53, 57, 59, 60, 54, 55, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 2763/2828 [07:54<00:15,  4.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▉  | 2767/2828 [07:55<00:10,  5.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▉  | 2769/2828 [07:55<00:08,  7.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2774/2828 [07:55<00:05,  9.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 17, 16: 19, 17: 14, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 17, 16: 19, 17: 14, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 17, 9, 14, 15, 18, 16, 19, 21, 20, 22, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2776/2828 [07:56<00:06,  8.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 56, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 54, 59, 53, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 56, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 54, 59, 53, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▎ | 2780/2828 [07:56<00:05,  9.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 39, 33: 40, 34: 33, 35: 37, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 35, 46: 31, 47: 34, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 46, 30, 34, 47, 45, 31, 35, 48, 32, 33, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 56, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 54, 59, 53, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 60, 57: 63, 58: 64, 59: 56, 60: 59, 61: 61, 62: 65, 63: 67, 64: 62, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 70, 52, 54, 59, 53, 55, 60, 56, 61, 64, 57, 58, 62, 65, 63, 66, 68, 67, 69, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 72, 73]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▍ | 2782/2828 [07:56<00:05,  8.03it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▌ | 2786/2828 [07:57<00:06,  6.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▌ | 2788/2828 [07:57<00:05,  6.92it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▋ | 2789/2828 [07:58<00:06,  6.44it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▊ | 2793/2828 [07:58<00:04,  7.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▉ | 2797/2828 [07:58<00:02, 10.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████ | 2801/2828 [07:59<00:02, 10.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 35, 42: 38, 43: 42, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▏| 2803/2828 [07:59<00:02, 11.00it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 68, 57: 70, 58: 65, 59: 69, 60: 71, 61: 73, 62: 72, 63: 74, 64: 60, 65: 63, 66: 57, 67: 59, 68: 62, 69: 66, 70: 67, 71: 55, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 71, 52, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 68, 57: 70, 58: 65, 59: 69, 60: 71, 61: 73, 62: 72, 63: 74, 64: 60, 65: 63, 66: 57, 67: 59, 68: 62, 69: 66, 70: 67, 71: 55, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 71, 52, 66, 53, 67, 64, 54, 68, 65, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 70, 66: 72, 67: 71, 68: 73, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 62, 60, 63, 61, 64, 69, 70, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 61, 58: 59, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 70, 66: 72, 67: 71, 68: 73, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 62, 60, 63, 61, 64, 69, 70, 65, 67, 66, 68]
[1, 49, 50]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▏| 2805/2828 [07:59<00:02, 11.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▎| 2809/2828 [08:00<00:01,  9.97it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 70, 58: 72, 59: 71, 60: 73, 61: 66, 62: 68, 63: 63, 64: 67, 65: 59, 66: 61, 67: 64, 68: 69, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 63, 67, 56, 61, 64, 62, 68, 57, 59, 58, 60]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 70, 58: 72, 59: 71, 60: 73, 61: 66, 62: 68, 63: 63, 64: 67, 65: 59, 66: 61, 67: 64, 68: 69, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 63, 67, 56, 61, 64, 62, 68, 57, 59, 58, 60]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▍| 2813/2828 [08:00<00:01,  9.52it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 57, 55: 61, 56: 63, 57: 65, 58: 67, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 55, 67: 58, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 66, 52, 54, 67, 65, 53, 55, 68, 56, 59, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▌| 2817/2828 [08:00<00:00, 11.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▋| 2819/2828 [08:00<00:00, 11.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▊| 2821/2828 [08:01<00:01,  6.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 2825/2828 [08:02<00:00,  7.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2828/2828 [08:02<00:00,  5.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

,dirName,jobName,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath,sourcePathwaysTxtPath,routeId,routeNumberInFile,...,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt,hasRuleLookup,queryReaction,queryMappedReaction,rcmfpMappingStatus,queryRCMFP,rcmfpStatus
0,high_pPotency_molecule_pathway19_wGen3,high_pPotency_molecule_pathway19_wGen3,19,high_pPotency_molecule_pathway19_wGen3,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_network...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway19_wGen3_route_0...,4,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
1,high_pPotency_molecule_pathway2_wGen1,high_pPotency_molecule_pathway2_wGen1,2,high_pPotency_molecule_pathway2_wGen1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen1_route_00...,2,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,4,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
3,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,5,...,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,[S+:1]([CH2:2][CH2:4][CH:6]([NH2:9])[C:10](=[O...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
4,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,6,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,16,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!R...,G1EFQ3;O94197;Q5Y9C6;Q94FT4,4,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2824,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,18,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2825,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,18,...,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,[S+:1]([CH2:2][CH2:4][CH:6]([NH2:9])[C:10](=[O...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2826,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,20,...,CoA;Any,[#6:1]-[#16:2].[#8;$([#8&!R]-[#6&!R]);!$([#8&!...,G1EFQ3;Q00857,2,True,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,[S:1]([CH2:2][CH2:3][NH:4][C:5](=[O:6])[CH2:7]...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2827,high_pPotency_molecule_pathway2_wGen2,high_pPotency_molecule_pathway2_wGen2,2,high_pPotency_molecule_pathway2_wGen2,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_network_...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway2_wGen2_route_00...,20,...,METHYL_ACCEPTOR_CoF;Any,[#6:1]-[#16+:2].[#8;$([#8&!R]-[#6&R]);!$([#8&!...,G0FUS0,1,True,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,[S+:1]([CH2:2][CH2:4][CH:6]([NH2:9])[C:10](=[O...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success

In [23]:
print("RCMFP status counts:")
print(sucessAtomMapDF["rcmfpStatus"].value_counts(dropna=False))
print("Valid RCMFP reactions:", len(sucessAtomMapDF))
print("Failed RCMFP reactions:", len(queryRcmfpFailureDF))

RCMFP status counts:
rcmfpStatus
rcmfp_success    2828
Name: count, dtype: int64
Valid RCMFP reactions: 2828
Failed RCMFP reactions: 0

### Load and align known enzyme reference metadata and RCMFP cache

- loaded from: https://github.com/JBEI/TridentSynthWeb/tree/b17e61040b182ce68b2931f8dbbaf65f370f8c03/data/processed

In [ ]:
naturalEnzymeFilePath = os.path.join(dataDir + "/DORAnet/known_enzyme_reactions_union.parquet")
naturalEnzyme_FP_FilePath = os.path.join(dataDir + "/DORAnet/known_rxn_rcmfp_cache.npz")

naturalEnzymeDF = pd.read_parquet(naturalEnzymeFilePath)
naturalEnzymeDF_wFingerprints = np.load(naturalEnzyme_FP_FilePath, allow_pickle=True)
naturalEnzyme_fingerprint_matrix = naturalEnzymeDF_wFingerprints["fingerprints"].astype(bool)
naturalEnzyme_RC_PatternLHS, naturalEnzyme_RC_PatternRHS, knownValidIndices = naturalEnzymeDF_wFingerprints["rc_patterns_lhs"], naturalEnzymeDF_wFingerprints["rc_patterns_rhs"], naturalEnzymeDF_wFingerprints["valid_indices"]
naturalEnzymeReferenceDF = naturalEnzymeDF.iloc[knownValidIndices].reset_index(drop=True).copy()
naturalEnzymeReferenceDF["naturalEnzyme_RC_PatternLHS"], naturalEnzymeReferenceDF["naturalEnzyme_RC_PatternRHS"], naturalEnzymeReferenceDF["knownOriginalIndex"] = naturalEnzyme_RC_PatternLHS, naturalEnzyme_RC_PatternRHS, knownValidIndices
assert len(naturalEnzymeReferenceDF) == naturalEnzyme_fingerprint_matrix.shape[0]
print("Known enzyme reference shape:", naturalEnzymeReferenceDF.shape); print("Known enzyme molecular fingerprint matrix shape:", naturalEnzyme_fingerprint_matrix.shape)

### Compute RCMFP fingerprint matrices for `DORAnet` reactions

In [ ]:
def make_reverse_fingerprint_matrix(fpMatrix, sideLength=FP_SIDE_LENGTH): return np.hstack([fpMatrix[:, sideLength:], fpMatrix[:, :sideLength]]).astype(bool)
def make_fingerprint_matrix_from_column(df, fpCol):
    validMask = df[fpCol].notna(); metaDF = df.loc[validMask].drop(columns=[fpCol], errors="ignore").reset_index(drop=True)
    fpMatrix = np.vstack(df.loc[validMask, fpCol].to_numpy()).astype(bool); fpReverseMatrix = make_reverse_fingerprint_matrix(fpMatrix)
    return metaDF, fpMatrix, fpReverseMatrix, fpMatrix.sum(axis=1), fpReverseMatrix.sum(axis=1)

queryMetaDF, query_FP_Matrix, query_FP_MatrixReverse, queryPopcounts, queryReversePopcounts = make_fingerprint_matrix_from_column(sucessAtomMapDF, "queryRCMFP")
naturalEnzyme_fingerprint_matrixReverse = make_reverse_fingerprint_matrix(naturalEnzyme_fingerprint_matrix)
knownPopcounts, knownReversePopcounts = naturalEnzyme_fingerprint_matrix.sum(axis=1), naturalEnzyme_fingerprint_matrixReverse.sum(axis=1)

queryKeepCols = ["reactants", "products", "reactionString", "ruleName", "reactionType", "rxn_str", "ruleSMARTS", "candidateUniProtRaw", "numCandidateUniProt", "hasRuleLookup", "queryReaction", "queryMappedReaction", "rcmfpMappingStatus", "rcmfpStatus", "feasibilityScore_rule1", "feasibilityLabel_rule1", "feasibilityScore_rule2", "feasibilityLabel_rule2", "feasibilityScore_rule3", "feasibilityLabel_rule3", "feasibilityScore_rule4", "feasibilityLabel_rule4"]
queryMetaDF = queryMetaDF[[c for c in queryKeepCols if c in queryMetaDF.columns]].copy()
print("Query metadata shape:", queryMetaDF.shape); print("Query molecular fingerprint matrix shape:", query_FP_Matrix.shape); print("Known enzyme molecular fingerprint matrix shape:", naturalEnzyme_fingerprint_matrix.shape)
queryMetaDF

### Add `ruleBase` column to known enzyme reference and query metadata from DORAnet reactions

This avoids forcing known reference rules into expanded DORAnet rule names. It uses coarse operator family IDs such as `rule0003` and then lets RCMFP decide the closest natural reaction within that family.

In [ ]:
def get_rule_base(x): return None if pd.isna(x) else str(x).strip().split("_")[0]
def parse_operator_list(x):
    if isinstance(x, np.ndarray): return [str(v).strip() for v in x.tolist() if v is not None and str(v).strip()]
    if isinstance(x, (list, tuple, set)): return [str(v).strip() for v in list(x) if v is not None and str(v).strip()]
    if x is None or pd.isna(x): return []
    s = str(x).strip()
    if s in ["", "nan", "None", "[]"]: return []
    try:
        parsed = ast.literal_eval(s)
        return [str(v).strip() for v in list(parsed)] if isinstance(parsed, (list, tuple, set, np.ndarray)) else [str(parsed).strip()]
    except Exception:
        for sep in ["|", ";", ","]:
            if sep in s: return [v.strip().strip("'\"") for v in s.split(sep) if v.strip()]
        return [s]

def choose_known_rule_base(row):
    top = row.get("top_mapped_operator")
    if top is not None and not pd.isna(top) and str(top).strip().startswith("rule"): return str(top).strip(), "top_mapped_operator"
    for op in parse_operator_list(row.get("all_mapped_operators")):
        if str(op).startswith("rule"): return str(op), "all_mapped_operators"
    return None, "no_ruleBase"



# Build ruleBase in naturalEnzymeReferenceDF
naturalEnzymeReferenceDF = naturalEnzymeReferenceDF.copy()

naturalEnzymeReferenceDF[["ruleBase", "ruleBaseSource"]] = naturalEnzymeReferenceDF.apply(
    lambda row: pd.Series(choose_known_rule_base(row)),
    axis=1
)

# If you want only base (e.g., rule0001 from rule0001_22), normalize:
naturalEnzymeReferenceDF["ruleBase"] = naturalEnzymeReferenceDF["ruleBase"].apply(get_rule_base)

# Rebuild metadata
queryMetaDF = queryMetaDF.reset_index(drop=True).copy()
knownMetaDF = naturalEnzymeReferenceDF.reset_index(drop=True).copy()

queryMetaDF["queryRowId"] = np.arange(len(queryMetaDF))
knownMetaDF["knownRowId"] = np.arange(len(knownMetaDF))

queryMetaDF["ruleBase"] = queryMetaDF["ruleName"].apply(get_rule_base)

queryMetaDF["_ruleKey"] = queryMetaDF["ruleBase"].astype("object")
knownMetaDF["_ruleKey"] = knownMetaDF["ruleBase"].astype("object")

# Create ruleBase first, then use it
queryMetaDF["ruleBase"] = queryMetaDF["ruleName"].apply(get_rule_base)

if "ruleBase" not in knownMetaDF.columns:
    raise KeyError("knownMetaDF does not contain ruleBase after merge. Check knownOriginalIndex alignment.")

queryMetaDF["_ruleKey"] = queryMetaDF["ruleBase"].astype("object")
knownMetaDF["_ruleKey"] = knownMetaDF["ruleBase"].astype("object")

knownIndicesByRuleBase = {
    ruleBase: idx.to_numpy()
    for ruleBase, idx in knownMetaDF.dropna(subset=["_ruleKey"]).groupby("_ruleKey").groups.items()
}

queryRuleBases = set(queryMetaDF["ruleBase"].dropna().astype(str))
knownRuleBases = set(knownMetaDF["ruleBase"].dropna().astype(str))

print("Source of known enzymetic data base:")
print(knownMetaDF["ruleBaseSource"].value_counts(dropna=False))
print("Reaction rules present in DORAnet reaction mechanism:", len(queryRuleBases))
print("Reaction rules present in known enzymetic data base:", len(knownRuleBases))
print("Overlapping base reaction rules:", len(queryRuleBases.intersection(knownRuleBases)))
print("Example overlaps:", sorted(queryRuleBases.intersection(knownRuleBases))[:20])

### Run `ruleBase` constrained RCMFP enzyme retrieval

For each query reaction (present in DORAnet reaction network) it searches the known natural enzyme reaction database, computes RCMFP Tanimoto similarity, keeps the best matches and stores the results in `matchedRCMFP_DF`. Final returned matches are ranked from highest to lowest RCMFP similarity.

In [ ]:
# this function calculates Tanimoto similarity between one query fingerprint and many known enzyme reference fingerprints
def compute_tanimoto_similarity(queryPackedRow, queryPop, refPackedMatrix, refPopcounts, popcount8):
    inter = popcount8[np.bitwise_and(refPackedMatrix, queryPackedRow)].sum(axis=1).astype(np.float32); union = refPopcounts + queryPop - inter
    scores = np.zeros(len(refPopcounts), dtype=np.float32); valid = union > 0; scores[valid] = inter[valid] / union[valid]
    return scores

# this function retrieves the top enzyme reference matches for one query reaction
def retrieve_similar_reactions(queryIdx, topK=TOP_K, minSimilarity=MIN_SIMILARITY):
    queryRuleBase = queryMetaDF.loc[queryIdx, "_ruleKey"]
    candidateIdx, searchMode = (knownIndicesByRuleBase[queryRuleBase], "same_ruleBase") if pd.notna(queryRuleBase) and queryRuleBase in knownIndicesByRuleBase else (np.arange(len(knownMetaDF)), "full_database_fallback")
    qPacked, qPop = queryPacked[queryIdx], queryPopcounts[queryIdx]
    scores = np.maximum(compute_tanimoto_similarity(qPacked, qPop, knownPacked[candidateIdx], knownPopcounts[candidateIdx], popcount8), compute_tanimoto_similarity(qPacked, qPop, knownPackedReverse[candidateIdx], knownReversePopcounts[candidateIdx], popcount8))
    validLocal = np.where(scores > minSimilarity)[0]
    if len(validLocal) == 0: return []
    topLocal = validLocal[np.argpartition(-scores[validLocal], topK - 1)[:topK]] if len(validLocal) > topK else validLocal
    topLocal = topLocal[np.argsort(-scores[topLocal])]
    return [{"queryRowId": int(queryIdx), "rank": rank, "knownRowId": int(candidateIdx[localIdx]), "rcmfpSimilarity": float(scores[localIdx]), "searchMode": searchMode, "numCandidatesSearched": int(len(candidateIdx))} for rank, localIdx in enumerate(topLocal, start=1)]

query_FP_Matrix, naturalEnzyme_fingerprint_matrix, naturalEnzyme_fingerprint_matrixReverse = query_FP_Matrix.astype(bool), naturalEnzyme_fingerprint_matrix.astype(bool), naturalEnzyme_fingerprint_matrixReverse.astype(bool)
queryPacked, knownPacked, knownPackedReverse = np.packbits(query_FP_Matrix.astype(np.uint8), axis=1), np.packbits(naturalEnzyme_fingerprint_matrix.astype(np.uint8), axis=1), np.packbits(naturalEnzyme_fingerprint_matrixReverse.astype(np.uint8), axis=1)
queryPopcounts, knownPopcounts, knownReversePopcounts = query_FP_Matrix.sum(axis=1).astype(np.int32), naturalEnzyme_fingerprint_matrix.sum(axis=1).astype(np.int32), naturalEnzyme_fingerprint_matrixReverse.sum(axis=1).astype(np.int32)
popcount8 = np.array([bin(i).count("1") for i in range(256)], dtype=np.uint8)

allHitRecords = []
for queryIdx in tqdm(range(len(queryMetaDF)), desc="RCMFP enzyme retrieval"): allHitRecords.extend(retrieve_similar_reactions(queryIdx))
matchedRCMFP_DF = pd.DataFrame(allHitRecords)
print("Total hits:", len(matchedRCMFP_DF)); print(matchedRCMFP_DF["searchMode"].value_counts(dropna=False))
matchedRCMFP_DF.head()

### Build full summary, filter Moderate/Strong, deduplicate and save outputs

In [ ]:
def print_section(title):
    print("\n" + "-" * 80)
    print(title)
    print("-" * 80)

def print_saved_file(label, path):
    print(f"{label}: {path}")

def classify_precedent(sim):
    if pd.isna(sim): return "No natural precedent retrieved"
    if sim >= 0.60: return "Strong natural enzyme precedent"
    if sim >= 0.35: return "Moderate natural enzyme precedent"
    if sim > 0: return "Weak precedent; likely enzyme-engineering risk"
    return "No useful RCMFP precedent"

queryDisplayCols = [c for c in ["queryRowId", "reactionString", "ruleName", "ruleBase", "reactionType", "queryReaction", "queryMappedReaction", "candidateUniProtRaw", "numCandidateUniProt", "rcmfpMappingStatus", "rcmfpStatus", "feasibilityScore_rule1", "feasibilityLabel_rule1", "feasibilityScore_rule2", "feasibilityLabel_rule2", "feasibilityScore_rule3", "feasibilityLabel_rule3", "feasibilityScore_rule4", "feasibilityLabel_rule4"] if c in queryMetaDF.columns]
knownDisplayCols = [c for c in ["knownRowId", "knownOriginalIndex", "ruleBase", "ruleBaseSource", "rxn_idx", "mapped", "unmapped", "orig_rxn_text", "rule", "source", "quality", "natural", "organism", "protein_refs", "protein_db", "ec_num", "top_mapped_operator", "all_mapped_operators"] if c in knownMetaDF.columns]

matchedRCMFP_DF = matchedRCMFP_DF.merge(queryMetaDF[queryDisplayCols], on="queryRowId", how="left", suffixes=("", "_query")).merge(knownMetaDF[knownDisplayCols], on="knownRowId", how="left", suffixes=("", "_known")).sort_values(["queryRowId", "rank"]).reset_index(drop=True)
matchedRCMFP_DF.head()

### Marge information of natural enzyme reference to `reactionDF_wUniprotID`

In [ ]:
# User options
keyCol = "reactionString"
scoreCol = "rcmfpSimilarity"
keepMode = "best"   # "best" or "all"
bestAscending = False  # False => highest score is best, True => lowest is best

sourceDF = matchedRCMFP_DF.copy()

if keepMode == "best":
    sourceToMerge = (
        sourceDF
        .sort_values(scoreCol, ascending=bestAscending, na_position="last")
        .drop_duplicates(subset=[keyCol], keep="first")
    )
elif keepMode == "all":
    sourceToMerge = sourceDF
else:
    raise ValueError("keepMode must be 'best' or 'all'")

# only add columns that don't already exist in target
newCols = [c for c in sourceToMerge.columns if c not in reactionDF_wUniprotID.columns and c != keyCol]

reactionDF_wUniprotID = reactionDF_wUniprotID.merge(
    sourceToMerge[[keyCol] + newCols],
    on=keyCol,
    how="inner"   # keep only rows present in source
)

print(f"Mode: {keepMode}")
print(f"Rows after merge: {len(reactionDF_wUniprotID):,}")
print(f"Added columns: {len(newCols)}")
reactionDF_wUniprotID

### Find best `UniProt ID` per DORANet reaction rule

In [ ]:
uniprotPattern = re.compile(
    r"([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9](?:[A-Z0-9]{3}[0-9]){1,2})"
)

def extractUniProtID(x):
    if pd.isna(x):
        return []
    ids = uniprotPattern.findall(str(x))
    seen, out = set(), []
    for uid in ids:
        if uid not in seen:
            out.append(uid)
            seen.add(uid)
    return out


tmp = matchedRCMFP_DF.copy()

tmp["knownProteinRefList"] = tmp["protein_refs"].apply(extractUniProtID)

tmp = tmp[
    tmp["knownProteinRefList"].apply(len) > 0
].copy()

tmp = tmp.explode("knownProteinRefList").rename(
    columns={"knownProteinRefList": "rcmfpSupportedUniProt"}
)

tmp["rcmfpSimilarity"] = pd.to_numeric(
    tmp["rcmfpSimilarity"],
    errors="coerce"
)

tmp["rank"] = pd.to_numeric(
    tmp["rank"],
    errors="coerce"
)

ruleRcmfpUniProtScoreDF = (
    tmp
    .groupby(["ruleName", "ruleBase", "rcmfpSupportedUniProt"])
    .agg(
        numSupportingHits=("knownRowId", "nunique"),
        bestRCMFPSimilarity=("rcmfpSimilarity", "max"),
        meanRCMFPSimilarity=("rcmfpSimilarity", "mean"),
        bestRank=("rank", "min"),
        exampleKnownRowId=("knownRowId", "first"),
        exampleKnownReaction=("orig_rxn_text", "first"),
        exampleKnownOrganism=("organism", "first"),
        exampleKnownEcNumber=("ec_num", "first"),
        exampleProteinRefs=("protein_refs", "first"),
    )
    .reset_index()
)

ruleRcmfpUniProtScoreDF["rcmfpProteinRefScore"] = (
    ruleRcmfpUniProtScoreDF["bestRCMFPSimilarity"] * 100
    + np.log1p(ruleRcmfpUniProtScoreDF["numSupportingHits"]) * 10
    - ruleRcmfpUniProtScoreDF["bestRank"] * 0.1
)

ruleRcmfpUniProtScoreDF = ruleRcmfpUniProtScoreDF.sort_values(
    [
        "ruleName",
        "rcmfpProteinRefScore",
        "bestRCMFPSimilarity",
        "numSupportingHits",
        "bestRank",
    ],
    ascending=[True, False, False, False, True]
)

bestRCMFPUniProtByRuleDF = (
    ruleRcmfpUniProtScoreDF
    .groupby("ruleName")
    .head(1)
    .reset_index(drop=True)
)

bestRCMFPUniProtByRuleDF[
    [
        "ruleName",
        "rcmfpSupportedUniProt",
        "rcmfpProteinRefScore",
        "bestRCMFPSimilarity",
        "meanRCMFPSimilarity",
        "numSupportingHits",
        "bestRank",
        "exampleKnownOrganism",
        "exampleKnownEcNumber",
        "exampleKnownReaction",
    ]
].head()

### Merge back `RCMFP-supported UniProt ID` with `reactionDF_wUniprotID`

In [ ]:
# Columns to keep + rename map
rename_map = {
    "rcmfpSupportedUniProt": "bestRCMFP_UniProtID",
    "rcmfpProteinRefScore": "bestRCMFP_UniProtScore",
    "bestRCMFPSimilarity": "bestRCMFP_SimilarityScore",
    "meanRCMFPSimilarity": "meanRCMFP_Similarity_byRule",
    "numSupportingHits": "numRCMFP_SupportingHits_byRule",
    "bestRank": "bestRCMFPRank_byRule",
    "exampleKnownRowId": "bestRCMFP_RowId",
    "exampleKnownReaction": "bestRCMFP_Reaction",
    "exampleKnownOrganism": "bestRCMFP_Organism",
    "exampleKnownEcNumber": "bestRCMFP_ECnumber",
    "exampleProteinRefs": "bestRCMFP_ProteinRefs",
}

bestRCMFPForMergeDF = (
    bestRCMFPUniProtByRuleDF[["ruleName", *rename_map]]
    .rename(columns=rename_map)
)

reactionDF_wBestRCMFP_Similarity = (
    reactionDF_wUniprotID
    .merge(bestRCMFPForMergeDF, on="ruleName", how="left")
    .assign(
        hasbestRCMFP_UniProtID=lambda df: (
            df["bestRCMFP_UniProtID"].fillna("").astype(str).str.len().gt(0)
        )
    )
)

print("reactionDF_wBestRCMFP_Similarity created")
print(f"Rows in reactionDF_wUniprotID              : {len(reactionDF_wUniprotID):,}")
print(f"Rows in reactionDF_wBestRCMFP_Similarity   : {len(reactionDF_wBestRCMFP_Similarity):,}")
print(f"Rows with best RCMFP UniProt               : {reactionDF_wBestRCMFP_Similarity['hasbestRCMFP_UniProtID'].sum():,}")
print(f"Unique best RCMFP UniProt IDs              : {reactionDF_wBestRCMFP_Similarity['bestRCMFP_UniProtID'].nunique():,}")

reactionDF_wBestRCMFP_Similarity.head()

In [ ]:
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.drop(
    columns=[
        'reactantSetCanonical', 'productSetCanonical',
        'rxn_str', 'feasibilityScore_rule1', 'feasibilityLabel_rule1',
        'feasibilityLabel_rule2', 'feasibilityScore_rule3', 'feasibilityLabel_rule3',
        'feasibilityScore_rule4', 'feasibilityLabel_rule4', 'ruleReactants',
        'ruleProducts', 'ruleSMARTS', 'hasRuleLookup', 'queryRowId', 'rank',
        'knownRowId', 'rcmfpSimilarity', 'searchMode', 'numCandidatesSearched',
        'ruleBase', 'queryReaction', 'queryMappedReaction','rcmfpMappingStatus', 'rcmfpStatus', 'knownOriginalIndex',
        'ruleBase_known', 'ruleBaseSource', 'rxn_idx', 'mapped', 'unmapped','orig_rxn_text', 'rule', 'source', 'quality', 'natural', 
        'organism','protein_refs', 'protein_db', 'ec_num', 'top_mapped_operator',
        'all_mapped_operators','bestRCMFP_UniProtScore', 'meanRCMFP_Similarity_byRule','numRCMFP_SupportingHits_byRule',      
        'bestRCMFPRank_byRule','bestRCMFP_RowId', 'bestRCMFP_Reaction', 'bestRCMFP_ProteinRefs', 'hasbestRCMFP_UniProtID'               
    ],
    errors='ignore'  
)

reactionDF_wBestRCMFP_Similarity

reactionDF_wUniprotID_display = reactionDF_wUniprotID[
    ["reactants", "products", "ruleName", "candidateUniProtRaw", "feasibilityScore_rule1", "rcmfpBestSimilarity"]].copy()
reactionDF_wUniprotID_display = reactionDF_wUniprotID_display.drop_duplicates(
    subset=["ruleName"], keep="first"
).copy()
reactionDF_wUniprotID_display

## 5. Query UniProt for EC numbers, protein names, organisms and sequences

```text
DORAnet rule ID → UniProt accession → EC number/protein sequence
```

### Summarize unique DORAnet reaction rules with `UniProt ID`

In [ ]:
tmp = reactionDF_wBestRCMFP_Similarity.copy()

tmp["prioritizedUniProt"] = (
    tmp["bestRCMFP_UniProtID"].fillna("").astype(str).str.strip()
)
fallback_mask = tmp["prioritizedUniProt"].eq("")
tmp.loc[fallback_mask, "prioritizedUniProt"] = (
    tmp.loc[fallback_mask, "candidateUniProtRaw"].fillna("").astype(str).str.strip()
)

usedRuleSummaryDF = (
    tmp
    .groupby(["ruleName", "reactionType", "prioritizedUniProt"], dropna=False)
    .agg(
        numReactions=("reactionString", "count"),
        exampleReaction=("reactionString", "first"),
    )
    .reset_index()
    .sort_values("numReactions", ascending=False)
)

usedRuleSummaryDF

### Fetch `UniProt` metadata

In [ ]:
def chunkList(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]


def cleanUniProtAccession(x):
    if pd.isna(x):
        return None

    x = str(x).strip()
    x = x.replace("UniProtKB:", "").replace("UniProt:", "").replace("uniprot:", "")
    x = x.replace("sp|", "").replace("tr|", "")

    # Handles strings like sp|P77791|NAME
    if "|" in x:
        parts = [p.strip() for p in x.split("|") if p.strip()]
        for p in parts:
            if isValidUniProtAccession(p):
                return p

    x = x.split()[0].split("-")[0].strip()
    return x if x else None


uniprotAccessionPattern = re.compile(
    r"^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z0-9]{3}[0-9]){1,2})$"
)


def isValidUniProtAccession(x):
    return False if pd.isna(x) else bool(
        uniprotAccessionPattern.match(str(x).strip())
    )


def fetchUniProtMetadata(accessionList, chunkSize=20, sleepSeconds=0.5):
    fields = [
        "accession",
        "reviewed",
        "id",
        "protein_name",
        "gene_names",
        "organism_name",
        "organism_id",
        "ec",
        "length",
        "sequence",
    ]

    allDf = []
    errors = 0

    for chunk in tqdm(list(chunkList(accessionList, chunkSize)), desc="Querying UniProt"):
        q = " OR ".join([f"(accession_id:{a})" for a in chunk])

        try:
            r = requests.get(
                "https://rest.uniprot.org/uniprotkb/search",
                params={
                    "query": q,
                    "format": "tsv",
                    "fields": ",".join(fields),
                    "size": chunkSize,
                },
                timeout=120,
            )

            if r.status_code != 200:
                errors += 1
            else:
                df = pd.read_csv(StringIO(r.text), sep="\t")

                if len(df) == 0:
                    errors += 1
                else:
                    allDf.append(df)

        except Exception:
            errors += 1

        time.sleep(sleepSeconds)

    out = (
        pd.concat(allDf, ignore_index=True).drop_duplicates()
        if allDf
        else pd.DataFrame()
    )

    return out, errors


# -----------------------------------------------
# Filter best RCMFP UniProt IDs
# -----------------------------------------------
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.copy()

reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID_clean"] = (
    reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID"]
    .apply(cleanUniProtAccession)
)

reactionDF_wBestRCMFP_Similarity["isValidBestRCMFP_UniProtID"] = (
    reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID_clean"]
    .apply(isValidUniProtAccession)
)

uniqueAccessionList = sorted(
    reactionDF_wBestRCMFP_Similarity.loc[
        reactionDF_wBestRCMFP_Similarity["isValidBestRCMFP_UniProtID"],
        "bestRCMFP_UniProtID_clean",
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

print(f"Unique valid best RCMFP UniProt IDs: {len(uniqueAccessionList):,}")

if not uniqueAccessionList:
    raise RuntimeError("No valid best RCMFP UniProt IDs found.")


# -----------------------------------------------
# Query UniProt
# -----------------------------------------------
uniprotMetadataRawDF, failedChunks = fetchUniProtMetadata(
    uniqueAccessionList,
    chunkSize=20,
    sleepSeconds=0.5,
)

totalChunks = int(np.ceil(len(uniqueAccessionList) / 20))
successChunks = totalChunks - failedChunks

print(f"Successful query chunks: {successChunks}")
print(f"Failed query chunks    : {failedChunks}")


# -----------------------------------------------
# Standardize UniProt columns
# -----------------------------------------------
renameMap = {
    "Entry": "uniprotAccession",
    "Reviewed": "uniprotReviewed",
    "Entry Name": "entryName",
    "Protein names": "proteinName",
    "Gene Names": "geneNames",
    "Organism": "organism",
    "Organism (ID)": "organismTaxId",
    "EC number": "ecNumber",
    "Length": "proteinLengthAa",
    "Sequence": "proteinSequence",
}

uniprotMetadataDF = uniprotMetadataRawDF.rename(columns=renameMap)

requiredCols = [
    "uniprotAccession",
    "uniprotReviewed",
    "entryName",
    "proteinName",
    "geneNames",
    "organism",
    "organismTaxId",
    "ecNumber",
    "proteinLengthAa",
    "proteinSequence",
]

for c in requiredCols:
    if c not in uniprotMetadataDF.columns:
        uniprotMetadataDF[c] = np.nan

uniprotMetadataDF = uniprotMetadataDF[requiredCols].copy()


# -----------------------------------------------
# Merge UniProt metadata back to reactionDF_wBestRCMFP_Similarity
# -----------------------------------------------
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.rename(
    columns={"bestRCMFP_UniProtID_clean": "uniprotAccession"}
)

reactionDF_wBestRCMFP_wUniProtMetadata = reactionDF_wBestRCMFP_Similarity.merge(
    uniprotMetadataDF,
    on="uniprotAccession",
    how="left",
    suffixes=("", "_uniprot"),
)

reactionDF_wBestRCMFP_wUniProtMetadata["hasUniProtMetadata"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["proteinName"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

reactionDF_wBestRCMFP_wUniProtMetadata["hasProteinSequence"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["proteinSequence"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("reactionDF_wBestRCMFP_wUniProtMetadata created")
print(f"Rows total             : {len(reactionDF_wBestRCMFP_wUniProtMetadata):,}")
print(f"Rows with metadata     : {reactionDF_wBestRCMFP_wUniProtMetadata['hasUniProtMetadata'].sum():,}")
print(f"Rows with protein seq  : {reactionDF_wBestRCMFP_wUniProtMetadata['hasProteinSequence'].sum():,}")

reactionDF_wBestRCMFP_wUniProtMetadata.head()

## 6. Fetch `DNA sequences` from `GenBank`

In [ ]:
# -----------------------------------------------
# settings
# -----------------------------------------------

NCBI_EMAIL = "sghosh6@lbl.gov"
NCBI_API_KEY = None
NCBI_TOOL = "DORAnet_GenBank_CDS_Fetch"

ncbiSleepSeconds = 0.40 if NCBI_API_KEY is None else 0.12
uniprotSleepSeconds = 0.15

# For testing, set 20 or 50. For full run, keep None.
maxUniProtToFetch = None


# -----------------------------------------------
# UniProt column setup
# -----------------------------------------------
if "reactionDF_wBestRCMFP_wUniProtMetadata" not in globals():
    raise RuntimeError("reactionDF_wBestRCMFP_wUniProtMetadata is not defined.")

reactionDF_wBestRCMFP_wUniProtMetadata = reactionDF_wBestRCMFP_wUniProtMetadata.copy()

# Prefer existing uniprotAccession column.
# Otherwise use bestRCMFP_UniProtID.
if "uniprotAccession" not in reactionDF_wBestRCMFP_wUniProtMetadata.columns:
    if "bestRCMFP_UniProtID" in reactionDF_wBestRCMFP_wUniProtMetadata.columns:
        reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"] = (
            reactionDF_wBestRCMFP_wUniProtMetadata["bestRCMFP_UniProtID"]
        )
    else:
        raise ValueError("Need either 'uniprotAccession' or 'bestRCMFP_UniProtID' column.")


# -----------------------------------------------
# Helper functions
# -----------------------------------------------
def dedupeKeepOrder(valueList):
    seen = set()
    out = []

    for value in valueList:
        if value is None:
            continue

        value = str(value).strip()

        if value and value not in seen:
            out.append(value)
            seen.add(value)

    return out


def cleanUniProtAccession(x):
    if pd.isna(x):
        return None

    x = str(x).strip()
    x = (
        x.replace("UniProtKB:", "")
        .replace("UniProt:", "")
        .replace("uniprot:", "")
        .replace("sp|", "")
        .replace("tr|", "")
    )

    if "|" in x:
        parts = [p.strip() for p in x.split("|") if p.strip()]
        for p in parts:
            if isValidUniProtAccession(p):
                return p

    x = x.split()[0].split("-")[0].strip()

    return x if x else None


uniprotAccessionPattern = re.compile(
    r"^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z0-9]{3}[0-9]){1,2})$"
)


def isValidUniProtAccession(x):
    return False if pd.isna(x) else bool(
        uniprotAccessionPattern.match(str(x).strip())
    )


def parseFastaRecords(fastaText):
    records = []
    header = None
    seqLines = []

    for line in str(fastaText).splitlines():
        line = line.strip()

        if not line:
            continue

        if line.startswith(">"):
            if header is not None:
                records.append({
                    "header": header,
                    "sequence": "".join(seqLines),
                })

            header = line[1:]
            seqLines = []

        else:
            seqLines.append(line)

    if header is not None:
        records.append({
            "header": header,
            "sequence": "".join(seqLines),
        })

    return records


def cleanDnaSequence(seq):
    seq = str(seq).upper()
    seq = re.sub(r"[^ACGTN]", "", seq)
    return seq


def fetchUniProtCrossRefs(uniprotAccession, sleepSeconds=0.15):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprotAccession}.json"

    result = {
        "uniprotAccession": uniprotAccession,
        "refseqProteinIds": [],
        "emblProteinIds": [],
        "nucleotideIds": [],
        "rawCrossRefSummary": "",
        "uniprotCrossRefStatus": "not_queried",
        "uniprotCrossRefError": "",
    }

    try:
        response = requests.get(url, timeout=60)

        if response.status_code != 200:
            result["uniprotCrossRefStatus"] = "failed"
            result["uniprotCrossRefError"] = f"{response.status_code}: {response.text[:300]}"
            time.sleep(sleepSeconds)
            return result

        entryJson = response.json()
        crossRefs = entryJson.get("uniProtKBCrossReferences", [])

        refseqProteinIds = []
        emblProteinIds = []
        nucleotideIds = []
        rawSummaryParts = []

        for xref in crossRefs:
            databaseName = str(xref.get("database", "")).strip()
            xrefId = str(xref.get("id", "")).strip()
            properties = xref.get("properties", [])

            propertyDict = {}

            for prop in properties:
                key = str(prop.get("key", "")).strip()
                value = str(prop.get("value", "")).strip()

                if key and value:
                    propertyDict.setdefault(key, []).append(value)

            if databaseName in ["RefSeq", "EMBL", "GenBank", "DDBJ"]:
                rawSummaryParts.append(f"{databaseName}:{xrefId}")

            if databaseName == "RefSeq" and xrefId:
                refseqProteinIds.append(xrefId)

            if databaseName in ["EMBL", "GenBank", "DDBJ"]:
                if xrefId:
                    nucleotideIds.append(xrefId)

                for key, values in propertyDict.items():
                    normalizedKey = (
                        key.lower()
                        .replace(" ", "")
                        .replace("_", "")
                        .replace("-", "")
                    )

                    if "proteinid" in normalizedKey or normalizedKey == "protein":
                        emblProteinIds.extend(values)

                    if "nucleotidesequenceid" in normalizedKey or "nucleotide" in normalizedKey:
                        nucleotideIds.extend(values)

        result["refseqProteinIds"] = dedupeKeepOrder(refseqProteinIds)
        result["emblProteinIds"] = dedupeKeepOrder(emblProteinIds)
        result["nucleotideIds"] = dedupeKeepOrder(nucleotideIds)
        result["rawCrossRefSummary"] = ";".join(rawSummaryParts)
        result["uniprotCrossRefStatus"] = "success"

    except Exception as exc:
        result["uniprotCrossRefStatus"] = "failed"
        result["uniprotCrossRefError"] = str(exc)

    time.sleep(sleepSeconds)

    return result


def fetchNcbiCdsFromProteinAccession(proteinAccession, sleepSeconds=0.40):
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

    params = {
        "db": "protein",
        "id": proteinAccession,
        "rettype": "fasta_cds_na",
        "retmode": "text",
        "tool": NCBI_TOOL,
        "email": NCBI_EMAIL,
    }

    if NCBI_API_KEY is not None:
        params["api_key"] = NCBI_API_KEY

    result = {
        "proteinAccessionQueried": proteinAccession,
        "ncbiFetchStatus": "not_queried",
        "ncbiFetchError": "",
        "genbankCdsFastaHeader": "",
        "genbankCdsSequence": "",
        "genbankCdsLengthBp": np.nan,
        "numFastaRecordsReturned": 0,
    }

    try:
        response = requests.get(url, params=params, timeout=120)

        if response.status_code != 200:
            result["ncbiFetchStatus"] = "failed"
            result["ncbiFetchError"] = f"{response.status_code}: {response.text[:300]}"
            time.sleep(sleepSeconds)
            return result

        fastaRecords = parseFastaRecords(response.text.strip())

        if len(fastaRecords) == 0:
            result["ncbiFetchStatus"] = "no_cds_returned"
            result["ncbiFetchError"] = response.text[:300]
            time.sleep(sleepSeconds)
            return result

        firstRecord = fastaRecords[0]
        cleanSeq = cleanDnaSequence(firstRecord["sequence"])

        if len(cleanSeq) == 0:
            result["ncbiFetchStatus"] = "empty_cds_sequence"
            result["ncbiFetchError"] = "No valid DNA sequence parsed."
            time.sleep(sleepSeconds)
            return result

        result["ncbiFetchStatus"] = "success"
        result["genbankCdsFastaHeader"] = firstRecord["header"]
        result["genbankCdsSequence"] = cleanSeq
        result["genbankCdsLengthBp"] = len(cleanSeq)
        result["numFastaRecordsReturned"] = len(fastaRecords)

    except Exception as exc:
        result["ncbiFetchStatus"] = "failed"
        result["ncbiFetchError"] = str(exc)

    time.sleep(sleepSeconds)

    return result


def fetchBestGenBankCdsForUniProt(uniprotAccession):
    crossRefResult = fetchUniProtCrossRefs(
        uniprotAccession,
        sleepSeconds=uniprotSleepSeconds,
    )

    candidateProteinIds = dedupeKeepOrder(
        crossRefResult["refseqProteinIds"] + crossRefResult["emblProteinIds"]
    )

    output = {
        "uniprotAccession": uniprotAccession,
        "genbankProteinIdsFromUniProt": ";".join(candidateProteinIds),
        "genbankNucleotideIdsFromUniProt": ";".join(crossRefResult["nucleotideIds"]),
        "rawCrossRefSummary": crossRefResult["rawCrossRefSummary"],
        "uniprotCrossRefStatus": crossRefResult["uniprotCrossRefStatus"],
        "uniprotCrossRefError": crossRefResult["uniprotCrossRefError"],
        "genbankProteinAccessionUsed": "",
        "genbankCdsFastaHeader": "",
        "genbankCdsSequence": "",
        "genbankCdsLengthBp": np.nan,
        "numFastaRecordsReturned": 0,
        "genbankCdsFetchStatus": "not_attempted",
        "genbankCdsFetchError": "",
    }

    if len(candidateProteinIds) == 0:
        output["genbankCdsFetchStatus"] = "no_protein_crossref"
        output["genbankCdsFetchError"] = (
            "No RefSeq/EMBL/GenBank protein cross-reference found in UniProt JSON."
        )
        return output

    fetchErrors = []

    for proteinAccession in candidateProteinIds:
        cdsResult = fetchNcbiCdsFromProteinAccession(
            proteinAccession,
            sleepSeconds=ncbiSleepSeconds,
        )

        if cdsResult["ncbiFetchStatus"] == "success":
            output["genbankProteinAccessionUsed"] = proteinAccession
            output["genbankCdsFastaHeader"] = cdsResult["genbankCdsFastaHeader"]
            output["genbankCdsSequence"] = cdsResult["genbankCdsSequence"]
            output["genbankCdsLengthBp"] = cdsResult["genbankCdsLengthBp"]
            output["numFastaRecordsReturned"] = cdsResult["numFastaRecordsReturned"]
            output["genbankCdsFetchStatus"] = "success"
            output["genbankCdsFetchError"] = ""
            return output

        fetchErrors.append(
            f"{proteinAccession}: {cdsResult['ncbiFetchStatus']} | {cdsResult['ncbiFetchError']}"
        )

    output["genbankCdsFetchStatus"] = "failed_all_protein_crossrefs"
    output["genbankCdsFetchError"] = " || ".join(fetchErrors[:5])

    return output


# -----------------------------------------------
# Choose UniProt IDs from reactionDF_wBestRCMFP_wUniProtMetadata
# -----------------------------------------------
reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"]
    .apply(cleanUniProtAccession)
)

reactionDF_wBestRCMFP_wUniProtMetadata["isValidUniProtAccession"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"]
    .apply(isValidUniProtAccession)
)

uniqueUniProtForGenBankList = sorted(
    reactionDF_wBestRCMFP_wUniProtMetadata.loc[
        reactionDF_wBestRCMFP_wUniProtMetadata["isValidUniProtAccession"],
        "uniprotAccession",
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

if maxUniProtToFetch is not None:
    uniqueUniProtForGenBankList = uniqueUniProtForGenBankList[:maxUniProtToFetch]

print(f"Unique UniProt accessions selected for GenBank CDS fetch: {len(uniqueUniProtForGenBankList):,}")

if len(uniqueUniProtForGenBankList) == 0:
    raise RuntimeError("No valid UniProt accessions found for GenBank CDS fetch.")


# -----------------------------------------------
# Fetch GenBank CDS sequences
# -----------------------------------------------
genbankLookupRecords = []

for uniprotAccession in tqdm(
    uniqueUniProtForGenBankList,
    desc="Fetching GenBank CDS via UniProt crossrefs",
):
    record = fetchBestGenBankCdsForUniProt(uniprotAccession)
    genbankLookupRecords.append(record)

genbankLookupDF = pd.DataFrame(genbankLookupRecords)

print("\nGenBank CDS fetch status:")
print(genbankLookupDF["genbankCdsFetchStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Merge GenBank CDS back to reaction dataframe
# -----------------------------------------------
reactionDF_wBestRCMFP_wDNAseq = reactionDF_wBestRCMFP_wUniProtMetadata.merge(
    genbankLookupDF,
    on="uniprotAccession",
    how="left",
)

reactionDF_wBestRCMFP_wDNAseq["hasGenBankCdsSequence"] = (
    reactionDF_wBestRCMFP_wDNAseq["genbankCdsSequence"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("\nreactionDF_wBestRCMFP_wDNAseq created")
print(f"Rows total              : {len(reactionDF_wBestRCMFP_wDNAseq):,}")
print(f"Rows with GenBank CDS   : {reactionDF_wBestRCMFP_wDNAseq['hasGenBankCdsSequence'].sum():,}")

reactionDF_wBestRCMFP_wDNAseq.head()

### Remove those coumns if no DNA sequence found from `GenBank`

In [ ]:
before_rows = len(reactionDF_wBestRCMFP_wDNAseq)

reactionDF_wBestRCMFP_wDNAseq = reactionDF_wBestRCMFP_wDNAseq[reactionDF_wBestRCMFP_wDNAseq["hasGenBankCdsSequence"] != False].copy()
after_rows = len(reactionDF_wBestRCMFP_wDNAseq)
dropped_rows = before_rows - after_rows

print(f"Total reaction : {before_rows:,}")
print(f"Reaction with GenBank CDS  : {after_rows:,}")
print(f"Reaction dropped : {dropped_rows:,}")

## 7. Codon-optimize selected enzymes for `target_species` using `DNA Chisel`

### Print Organisms details: `E.coli/Pseudomonas putida` etc

In [ ]:
organismCountsDF = (
    reactionDF_wBestRCMFP_wDNAseq["organism"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
    .value_counts(dropna=False)
    .rename_axis("organism")
    .reset_index(name="count")
)

totalRows = len(reactionDF_wBestRCMFP_wDNAseq)
organismCountsDF["percentage"] = (organismCountsDF["count"] / totalRows * 100).round(2)

print(f"Unique organisms: {organismCountsDF['organism'].nunique()}\n")
organismCountsDF

### Codon optimization settings

In [ ]:
targetSpecies = "e_coli"
minGc = 0.30
maxGc = 0.70
gcWindow = 50
stopCodon = "TAA"

forbiddenPatternList = [
    "BsaI_site",
    "BsmBI_site",
    "EcoRI_site",
    "XbaI_site",
    "SpeI_site",
    "PstI_site",
    "NotI_site",
]

stopCodons = {"TAA", "TAG", "TGA"}

In [ ]:
# -----------------------------------------------
# Helper functions
# -----------------------------------------------
def cleanDna(seq):
    if pd.isna(seq):
        return ""
    return re.sub(r"[^ACGTN]", "", str(seq).upper())


def removeTerminalStop(cds):
    cds = cleanDna(cds)
    if len(cds) >= 3 and len(cds) % 3 == 0 and cds[-3:] in stopCodons:
        return cds[:-3]
    return cds


def hasInternalStop(cds):
    cds = cleanDna(cds)
    if len(cds) % 3 != 0:
        return True
    codons = [cds[i:i+3] for i in range(0, len(cds), 3)]
    return any(codon in stopCodons for codon in codons)


def classifyCdsForOptimization(cds):
    cds = cleanDna(cds)
    cdsNoStop = removeTerminalStop(cds)

    if len(cds) == 0:
        return "no_cds"
    if len(cdsNoStop) == 0:
        return "empty_after_stop_removal"
    if len(cdsNoStop) % 3 != 0:
        return "length_not_multiple_of_3"
    if "N" in cdsNoStop:
        return "contains_N"
    if hasInternalStop(cdsNoStop):
        return "contains_internal_stop"

    return "ready_for_optimization"


def safeText(x):
    if pd.isna(x):
        return ""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))[:80]


def wrapFasta(seq, width=80):
    seq = str(seq)
    return "\n".join(seq[i:i+width] for i in range(0, len(seq), width))


def optimizeCdsForEcoli(initialCds):
    sequenceLength = len(initialCds)
    geneLocation = (0, sequenceLength)

    constraints = [
        EnforceTranslation(location=geneLocation),
        EnforceGCContent(mini=minGc, maxi=maxGc, window=gcWindow),
    ]

    for patternName in forbiddenPatternList:
        constraints.append(AvoidPattern(patternName))

    objectives = [
        MaximizeCAI(species=targetSpecies, location=geneLocation)
    ]

    optimizationProblem = DnaOptimizationProblem(
        sequence=initialCds,
        constraints=constraints,
        objectives=objectives,
    )

    optimizationProblem.resolve_constraints()
    optimizationProblem.optimize()

    return optimizationProblem.sequence, optimizationProblem


# -----------------------------------------------
# Prepare input from reactionDF_wBestRCMFP_wDNAseq
# -----------------------------------------------
reactionDF_wBestRCMFP_wDNAseq_forOpt = reactionDF_wBestRCMFP_wDNAseq.copy()

reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(cleanDna)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequenceForOptimization"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(removeTerminalStop)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(classifyCdsForOptimization)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["isReadyForCodonOptimization"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"]
    == "ready_for_optimization"
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["optimizationInputKey"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["uniprotAccession"].fillna("").astype(str)
    + "|"
    + reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankProteinAccessionUsed"].fillna("").astype(str)
    + "|"
    + reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequenceForOptimization"].fillna("").astype(str)
).apply(lambda x: hashlib.sha1(x.encode("utf-8")).hexdigest())

print("Input status:")
print(reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Optimize unique GenBank CDS records only
# -----------------------------------------------
geneInputDF = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt[
        reactionDF_wBestRCMFP_wDNAseq_forOpt["isReadyForCodonOptimization"]
    ]
    .drop_duplicates("optimizationInputKey")
    .reset_index(drop=True)
)

optimizedGeneRecords = []

for idx, row in tqdm(
    geneInputDF.iterrows(),
    total=len(geneInputDF),
    desc="Optimizing RCMFP-supported GenBank CDS for E. coli"
):
    optimizationInputKey = row["optimizationInputKey"]
    initialCds = row["genbankCdsSequenceForOptimization"]

    try:
        optimizedCdsNoStop, optimizationProblem = optimizeCdsForEcoli(initialCds)
        optimizedCds = optimizedCdsNoStop + stopCodon

        optimizationStatus = "success"
        optimizationError = ""
        constraintsSummary = optimizationProblem.constraints_text_summary()
        objectivesSummary = optimizationProblem.objectives_text_summary()

    except Exception as exc:
        optimizedCds = ""
        optimizationStatus = "failed"
        optimizationError = str(exc)
        constraintsSummary = ""
        objectivesSummary = ""

    optimizedGeneRecords.append({
        "optimizationInputKey": optimizationInputKey,
        "optimizedGeneId": f"ecoli_rcmfp_opt_gene_{idx:06d}",
        "optimizedCds": optimizedCds,
        "optimizedCdsLengthBp": len(optimizedCds),
        "expressionHost": "Escherichia coli",
        "targetSpecies": targetSpecies,
        "minGc": minGc,
        "maxGc": maxGc,
        "gcWindow": gcWindow,
        "stopCodonUsed": stopCodon,
        "codonOptimizationStatus": optimizationStatus,
        "codonOptimizationError": optimizationError,
        "constraintsSummary": constraintsSummary,
        "objectivesSummary": objectivesSummary,
    })

optimizedGeneDF = pd.DataFrame(optimizedGeneRecords)

print("\nOptimization status:")
print(optimizedGeneDF["codonOptimizationStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Merge optimized CDS back to reaction dataframe
# -----------------------------------------------
reactionDF_wOptimizedDNAseq = reactionDF_wBestRCMFP_wDNAseq_forOpt.merge(
    optimizedGeneDF,
    on="optimizationInputKey",
    how="left"
)

reactionDF_wOptimizedDNAseq["hasOptimizedCds"] = (
    reactionDF_wOptimizedDNAseq["optimizedCds"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("\nFinal reactionDF_wOptimizedDNAseq:")
print(f"Rows total           : {len(reactionDF_wOptimizedDNAseq):,}")
print(f"Rows optimized       : {reactionDF_wOptimizedDNAseq['hasOptimizedCds'].sum():,}")
print(f"Unique optimized CDS : {reactionDF_wOptimizedDNAseq.loc[reactionDF_wOptimizedDNAseq['hasOptimizedCds'], 'optimizationInputKey'].nunique():,}")
reactionDF_wOptimizedDNAseq.head()

## 8. Export `DNA design` files for `Teselagen`

In [ ]:
optimizedDNAFilePath = os.path.join(DNADesignResultsDir,"reactionDF_wBestRCMFP_optimized_Ecoli.fasta")

fastaDF = (reactionDF_wOptimizedDNAseq[reactionDF_wOptimizedDNAseq["hasOptimizedCds"]].drop_duplicates("optimizationInputKey").copy())

with open(optimizedDNAFilePath, "w", encoding="utf-8") as f:
    for _, row in fastaDF.iterrows():
        fastaHeader = (
            f">{row['optimizedGeneId']}|"
            f"rule={safeText(row.get('ruleName', ''))}|"
            f"UniProt={safeText(row.get('uniprotAccession', ''))}|"
            f"GenBankProtein={safeText(row.get('genbankProteinAccessionUsed', ''))}|"
            f"EC={safeText(row.get('ecNumber', ''))}|"
            f"host=Escherichia_coli"
        )

        f.write(fastaHeader + "\n")
        f.write(wrapFasta(row["optimizedCds"]) + "\n\n")

print(f"\nSaved FASTA at: {optimizedDNAFilePath}")

### Find unique `starter --> target` from codon optmized pathways

In [ ]:
reactionDF_wOptimizedDNAseq

In [ ]:
# -------------------------------------------------------------------
# Count complete starter --> target pathways per directory
# for reactionDF_wOptimizedDNAseq
# -------------------------------------------------------------------

df = reactionDF_wOptimizedDNAseq.copy()

# Make sure routeId is string
df["routeId"] = df["routeId"].astype(str)

# If generationRun is missing, infer it from searchDepthUsed
if "generationRun" not in df.columns and "searchDepthUsed" in df.columns:
    df["generationRun"] = df["searchDepthUsed"]

# If reconstructedPathwayString is missing but old column exists
if "reconstructedPathwayString" not in df.columns and "multiStepReactionSMILES" in df.columns:
    df = df.rename(columns={"multiStepReactionSMILES": "reconstructedPathwayString"})

# -------------------------------------------------------------------
# One row per unique reconstructed pathway route
# -------------------------------------------------------------------

aggDict = {
    "dirName": ("dirName", "first"),
    "jobName": ("jobName", "first"),
    "numSteps": ("numSteps", "first"),
    "searchDepthUsed": ("searchDepthUsed", "first"),
    "starterSMILES": ("starterSMILES", "first"),
    "targetSMILES": ("targetSMILES", "first"),
    "reconstructedPathwayString": ("reconstructedPathwayString", "first"),
}

if "sourceFolderNum" in df.columns:
    aggDict["sourceFolderNum"] = ("sourceFolderNum", "first")

if "generationRun" in df.columns:
    aggDict["generationRun"] = ("generationRun", "first")

completeRouteLevelDF = (
    df
    .sort_values(["dirName", "routeId", "step"])
    .groupby("routeId", as_index=False)
    .agg(**aggDict)
)

# -------------------------------------------------------------------
# Count 1-step, 2-step, and 3-step pathways per directory
# -------------------------------------------------------------------

indexCols = ["dirName", "jobName", "starterSMILES", "targetSMILES"]

if "generationRun" in completeRouteLevelDF.columns:
    indexCols.insert(2, "generationRun")

starterTargetPathwayCountsDF_wOptimizedDNAseq = (
    completeRouteLevelDF
    .pivot_table(
        index=indexCols,
        columns="numSteps",
        values="routeId",
        aggfunc="nunique",
        fill_value=0,
    )
    .rename(columns={
        1: "numOneStepPathways",
        2: "numTwoStepPathways",
        3: "numThreeStepPathways",
    })
    .reset_index()
)

for c in ["numOneStepPathways", "numTwoStepPathways", "numThreeStepPathways"]:
    if c not in starterTargetPathwayCountsDF_wOptimizedDNAseq.columns:
        starterTargetPathwayCountsDF_wOptimizedDNAseq[c] = 0

starterTargetPathwayCountsDF_wOptimizedDNAseq["totalStarterToTargetPathways"] = (
    starterTargetPathwayCountsDF_wOptimizedDNAseq["numOneStepPathways"]
    + starterTargetPathwayCountsDF_wOptimizedDNAseq["numTwoStepPathways"]
    + starterTargetPathwayCountsDF_wOptimizedDNAseq["numThreeStepPathways"]
)

starterTargetPathwayCountsDF_wOptimizedDNAseq = (
    starterTargetPathwayCountsDF_wOptimizedDNAseq
    .sort_values("totalStarterToTargetPathways", ascending=False)
    .reset_index(drop=True)
)

# -------------------------------------------------------------------
# Print summary
# -------------------------------------------------------------------

print(f"Total reaction-step rows              : {len(df):,}")
print(f"Unique starter --> target pathways   : {completeRouteLevelDF['routeId'].nunique():,}")
print(f"Directories with pathways            : {starterTargetPathwayCountsDF_wOptimizedDNAseq['dirName'].nunique():,}")

print("\nPathways by step count:")
print(completeRouteLevelDF["numSteps"].value_counts().sort_index())

starterTargetPathwayCountsDF_wOptimizedDNAseq

### Plot reaction pathways

In [ ]:
def splitPathway(pathwayStr):
    return [] if pd.isna(pathwayStr) else [x.strip() for x in str(pathwayStr).split("||") if x.strip()]


def splitStarters(starterStr):
    return [] if pd.isna(starterStr) else [x.strip() for x in str(starterStr).split(";") if x.strip()]


def safeName(rawName):
    return re.sub(r"[^A-Za-z0-9._-]+", "_", str(rawName))


def rdkitImageToPil(imageObj):
    if isinstance(imageObj, Image.Image):
        return imageObj.convert("RGB")
    if isinstance(imageObj, (bytes, bytearray)):
        return Image.open(BytesIO(imageObj)).convert("RGB")
    return Image.open(BytesIO(imageObj.data)).convert("RGB")


def makeTextBanner(textValue, bannerWidth, bannerHeight=36, bgColor="white", fgColor="black"):
    bannerImage = Image.new("RGB", (bannerWidth, bannerHeight), bgColor)
    drawer = ImageDraw.Draw(bannerImage)
    drawer.text((10, 10), textValue, fill=fgColor)
    return bannerImage


def makeMolGridPanel(smilesList, panelTitle, molsPerRow=3, subImageSize=(300, 220)):
    molList = [Chem.MolFromSmiles(s) for s in smilesList if s]
    molList = [m for m in molList if m is not None]
    if len(molList) == 0:
        return None

    gridImage = Draw.MolsToGridImage(molList, molsPerRow=molsPerRow, subImgSize=subImageSize)
    gridImage = rdkitImageToPil(gridImage)

    titleImage = makeTextBanner(panelTitle, gridImage.width, bannerHeight=34)
    return ImageOps.expand(titleImage, border=0), ImageOps.expand(gridImage, border=1, fill="black")


def makeReactionPanel(rxnSmiles, panelTitle, subImageSize=(460, 280)):
    reactionObj = AllChem.ReactionFromSmarts(str(rxnSmiles), useSmiles=True)
    if reactionObj is None:
        return None

    reactionImage = Draw.ReactionToImage(reactionObj, subImgSize=subImageSize)
    reactionImage = rdkitImageToPil(reactionImage)

    titleImage = makeTextBanner(panelTitle, reactionImage.width, bannerHeight=34)
    return ImageOps.expand(titleImage, border=0), ImageOps.expand(reactionImage, border=1, fill="black")


def stackPanelsVertically(panelList, gapSize=10, bgColor="white"):
    validPanels = [p for p in panelList if p is not None]
    if not validPanels:
        return None

    canvasWidth = max(p.width for p in validPanels)
    canvasHeight = sum(p.height for p in validPanels) + gapSize * (len(validPanels) - 1)

    canvasImage = Image.new("RGB", (canvasWidth, canvasHeight), bgColor)
    yOffset = 0
    for panelImage in validPanels:
        xOffset = (canvasWidth - panelImage.width) // 2
        canvasImage.paste(panelImage, (xOffset, yOffset))
        yOffset += panelImage.height + gapSize

    return canvasImage


for _, rowData in completeRouteLevelDF.iterrows():
    dirNameSafe = safeName(rowData["dirName"])

    panelBlocks = []

    headerText = (
        f"{rowData['dirName']} | Job: {rowData['jobName']} | Route: {rowData['routeId']} | "
        f"Gen: {rowData['generationRun']} | Steps: {rowData['numSteps']}"
    )
    headerPanel = makeTextBanner(headerText, bannerWidth=1600, bannerHeight=42)
    panelBlocks.append(headerPanel)

    starterSmilesList = splitStarters(rowData.get("starterSMILES", np.nan))
    starterPanel = makeMolGridPanel(
        starterSmilesList,
        "Starter molecule",
        molsPerRow=3,
        subImageSize=(300, 220),
    )
    if starterPanel:
        panelBlocks.extend(starterPanel)

    pathwaySteps = splitPathway(rowData.get("reconstructedPathwayString", np.nan))
    for stepIdx, reactionSmiles in enumerate(pathwaySteps, start=1):
        stepPanel = makeReactionPanel(
            reactionSmiles,
            f"Reaction step {stepIdx}",
            subImageSize=(460, 280),
        )
        if stepPanel:
            panelBlocks.extend(stepPanel)

    targetPanel = makeMolGridPanel(
        [rowData.get("targetSMILES", "")],
        "Target molecule",
        molsPerRow=1,
        subImageSize=(320, 240),
    )
    if targetPanel:
        panelBlocks.extend(targetPanel)

    finalImage = stackPanelsVertically(panelBlocks, gapSize=10, bgColor="white")
    if finalImage is None:
        continue

    jpgOutputPath = os.path.join(DNADesignResultsDir, f"{dirNameSafe}.jpg")
    pdfOutputPath = os.path.join(DNADesignResultsDir, f"{dirNameSafe}.pdf")

    finalImage.save(jpgOutputPath, "JPEG", quality=95)
    finalImage.save(pdfOutputPath, "PDF", resolution=300.0)

    display(finalImage)

print("Saved route images to:", DNADesignResultsDir)